import ctypes
from typing import TYPE_CHECKING, Union

from .genVec2 import genVec2

if TYPE_CHECKING:

    from .bool3 import bool3
    from .bool4 import bool4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class bool2(genVec2):

    _fields_ = [
        ('x', ctypes.c_bool),
        ('y', ctypes.c_bool)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_bool

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->bool: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->bool: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->"bool2": ...

        @property
        def xy(self)->"bool2": ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->"bool2": ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->"bool2": ...

        @property
        def xxx(self)->bool3: ...

        @property
        def xxy(self)->bool3: ...

        @property
        def xyx(self)->bool3: ...

        @property
        def xyy(self)->bool3: ...

        @property
        def yxx(self)->bool3: ...

        @property
        def yxy(self)->bool3: ...

        @property
        def yyx(self)->bool3: ...

        @property
        def yyy(self)->bool3: ...

        @property
        def xxxx(self)->bool4: ...

        @property
        def xxxy(self)->bool4: ...

        @property
        def xxyx(self)->bool4: ...

        @property
        def xxyy(self)->bool4: ...

        @property
        def xyxx(self)->bool4: ...

        @property
        def xyxy(self)->bool4: ...

        @property
        def xyyx(self)->bool4: ...

        @property
        def xyyy(self)->bool4: ...

        @property
        def yxxx(self)->bool4: ...

        @property
        def yxxy(self)->bool4: ...

        @property
        def yxyx(self)->bool4: ...

        @property
        def yxyy(self)->bool4: ...

        @property
        def yyxx(self)->bool4: ...

        @property
        def yyxy(self)->bool4: ...

        @property
        def yyyx(self)->bool4: ...

        @property
        def yyyy(self)->bool4: ...

        @property
        def r(self)->bool: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->bool: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->"bool2": ...

        @property
        def rg(self)->"bool2": ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->"bool2": ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->"bool2": ...

        @property
        def rrr(self)->bool3: ...

        @property
        def rrg(self)->bool3: ...

        @property
        def rgr(self)->bool3: ...

        @property
        def rgg(self)->bool3: ...

        @property
        def grr(self)->bool3: ...

        @property
        def grg(self)->bool3: ...

        @property
        def ggr(self)->bool3: ...

        @property
        def ggg(self)->bool3: ...

        @property
        def rrrr(self)->bool4: ...

        @property
        def rrrg(self)->bool4: ...

        @property
        def rrgr(self)->bool4: ...

        @property
        def rrgg(self)->bool4: ...

        @property
        def rgrr(self)->bool4: ...

        @property
        def rgrg(self)->bool4: ...

        @property
        def rggr(self)->bool4: ...

        @property
        def rggg(self)->bool4: ...

        @property
        def grrr(self)->bool4: ...

        @property
        def grrg(self)->bool4: ...

        @property
        def grgr(self)->bool4: ...

        @property
        def grgg(self)->bool4: ...

        @property
        def ggrr(self)->bool4: ...

        @property
        def ggrg(self)->bool4: ...

        @property
        def gggr(self)->bool4: ...

        @property
        def gggg(self)->bool4: ...

        @property
        def s(self)->bool: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->bool: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->"bool2": ...

        @property
        def st(self)->"bool2": ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->"bool2": ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->"bool2": ...

        @property
        def sss(self)->bool3: ...

        @property
        def sst(self)->bool3: ...

        @property
        def sts(self)->bool3: ...

        @property
        def stt(self)->bool3: ...

        @property
        def tss(self)->bool3: ...

        @property
        def tst(self)->bool3: ...

        @property
        def tts(self)->bool3: ...

        @property
        def ttt(self)->bool3: ...

        @property
        def ssss(self)->bool4: ...

        @property
        def ssst(self)->bool4: ...

        @property
        def ssts(self)->bool4: ...

        @property
        def sstt(self)->bool4: ...

        @property
        def stss(self)->bool4: ...

        @property
        def stst(self)->bool4: ...

        @property
        def stts(self)->bool4: ...

        @property
        def sttt(self)->bool4: ...

        @property
        def tsss(self)->bool4: ...

        @property
        def tsst(self)->bool4: ...

        @property
        def tsts(self)->bool4: ...

        @property
        def tstt(self)->bool4: ...

        @property
        def ttss(self)->bool4: ...

        @property
        def ttst(self)->bool4: ...

        @property
        def ttts(self)->bool4: ...

        @property
        def tttt(self)->bool4: ...
        # --- END generated swizzles ---
