import ctypes
from typing import TYPE_CHECKING, Union

from .genVec4 import genVec4

if TYPE_CHECKING:

    from .bool2 import bool2
    from .bool3 import bool3
    from .genVec2 import genVec2
    from .genVec3 import genVec3

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class bool4(genVec4):

    _fields_ = [
        ('x', ctypes.c_bool),
        ('y', ctypes.c_bool),
        ('z', ctypes.c_bool),
        ('w', ctypes.c_bool)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_bool

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->bool: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->bool: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def z(self)->bool: ...

        @z.setter
        def z(self, value:Union[bool, int, float])->None: ...

        @property
        def w(self)->bool: ...

        @w.setter
        def w(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->bool2: ...

        @property
        def xy(self)->bool2: ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xz(self)->bool2: ...

        @xz.setter
        def xz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xw(self)->bool2: ...

        @xw.setter
        def xw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->bool2: ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->bool2: ...

        @property
        def yz(self)->bool2: ...

        @yz.setter
        def yz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yw(self)->bool2: ...

        @yw.setter
        def yw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zx(self)->bool2: ...

        @zx.setter
        def zx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zy(self)->bool2: ...

        @zy.setter
        def zy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zz(self)->bool2: ...

        @property
        def zw(self)->bool2: ...

        @zw.setter
        def zw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wx(self)->bool2: ...

        @wx.setter
        def wx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wy(self)->bool2: ...

        @wy.setter
        def wy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wz(self)->bool2: ...

        @wz.setter
        def wz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ww(self)->bool2: ...

        @property
        def xxx(self)->bool3: ...

        @property
        def xxy(self)->bool3: ...

        @property
        def xxz(self)->bool3: ...

        @property
        def xxw(self)->bool3: ...

        @property
        def xyx(self)->bool3: ...

        @property
        def xyy(self)->bool3: ...

        @property
        def xyz(self)->bool3: ...

        @xyz.setter
        def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xyw(self)->bool3: ...

        @xyw.setter
        def xyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzx(self)->bool3: ...

        @property
        def xzy(self)->bool3: ...

        @xzy.setter
        def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzz(self)->bool3: ...

        @property
        def xzw(self)->bool3: ...

        @xzw.setter
        def xzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwx(self)->bool3: ...

        @property
        def xwy(self)->bool3: ...

        @xwy.setter
        def xwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwz(self)->bool3: ...

        @xwz.setter
        def xwz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xww(self)->bool3: ...

        @property
        def yxx(self)->bool3: ...

        @property
        def yxy(self)->bool3: ...

        @property
        def yxz(self)->bool3: ...

        @yxz.setter
        def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yxw(self)->bool3: ...

        @yxw.setter
        def yxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yyx(self)->bool3: ...

        @property
        def yyy(self)->bool3: ...

        @property
        def yyz(self)->bool3: ...

        @property
        def yyw(self)->bool3: ...

        @property
        def yzx(self)->bool3: ...

        @yzx.setter
        def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yzy(self)->bool3: ...

        @property
        def yzz(self)->bool3: ...

        @property
        def yzw(self)->bool3: ...

        @yzw.setter
        def yzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywx(self)->bool3: ...

        @ywx.setter
        def ywx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywy(self)->bool3: ...

        @property
        def ywz(self)->bool3: ...

        @ywz.setter
        def ywz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yww(self)->bool3: ...

        @property
        def zxx(self)->bool3: ...

        @property
        def zxy(self)->bool3: ...

        @zxy.setter
        def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zxz(self)->bool3: ...

        @property
        def zxw(self)->bool3: ...

        @zxw.setter
        def zxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyx(self)->bool3: ...

        @zyx.setter
        def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyy(self)->bool3: ...

        @property
        def zyz(self)->bool3: ...

        @property
        def zyw(self)->bool3: ...

        @zyw.setter
        def zyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zzx(self)->bool3: ...

        @property
        def zzy(self)->bool3: ...

        @property
        def zzz(self)->bool3: ...

        @property
        def zzw(self)->bool3: ...

        @property
        def zwx(self)->bool3: ...

        @zwx.setter
        def zwx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwy(self)->bool3: ...

        @zwy.setter
        def zwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwz(self)->bool3: ...

        @property
        def zww(self)->bool3: ...

        @property
        def wxx(self)->bool3: ...

        @property
        def wxy(self)->bool3: ...

        @wxy.setter
        def wxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxz(self)->bool3: ...

        @wxz.setter
        def wxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxw(self)->bool3: ...

        @property
        def wyx(self)->bool3: ...

        @wyx.setter
        def wyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyy(self)->bool3: ...

        @property
        def wyz(self)->bool3: ...

        @wyz.setter
        def wyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyw(self)->bool3: ...

        @property
        def wzx(self)->bool3: ...

        @wzx.setter
        def wzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzy(self)->bool3: ...

        @wzy.setter
        def wzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzz(self)->bool3: ...

        @property
        def wzw(self)->bool3: ...

        @property
        def wwx(self)->bool3: ...

        @property
        def wwy(self)->bool3: ...

        @property
        def wwz(self)->bool3: ...

        @property
        def www(self)->bool3: ...

        @property
        def xxxx(self)->"bool4": ...

        @property
        def xxxy(self)->"bool4": ...

        @property
        def xxxz(self)->"bool4": ...

        @property
        def xxxw(self)->"bool4": ...

        @property
        def xxyx(self)->"bool4": ...

        @property
        def xxyy(self)->"bool4": ...

        @property
        def xxyz(self)->"bool4": ...

        @property
        def xxyw(self)->"bool4": ...

        @property
        def xxzx(self)->"bool4": ...

        @property
        def xxzy(self)->"bool4": ...

        @property
        def xxzz(self)->"bool4": ...

        @property
        def xxzw(self)->"bool4": ...

        @property
        def xxwx(self)->"bool4": ...

        @property
        def xxwy(self)->"bool4": ...

        @property
        def xxwz(self)->"bool4": ...

        @property
        def xxww(self)->"bool4": ...

        @property
        def xyxx(self)->"bool4": ...

        @property
        def xyxy(self)->"bool4": ...

        @property
        def xyxz(self)->"bool4": ...

        @property
        def xyxw(self)->"bool4": ...

        @property
        def xyyx(self)->"bool4": ...

        @property
        def xyyy(self)->"bool4": ...

        @property
        def xyyz(self)->"bool4": ...

        @property
        def xyyw(self)->"bool4": ...

        @property
        def xyzx(self)->"bool4": ...

        @property
        def xyzy(self)->"bool4": ...

        @property
        def xyzz(self)->"bool4": ...

        @property
        def xyzw(self)->"bool4": ...

        @xyzw.setter
        def xyzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xywx(self)->"bool4": ...

        @property
        def xywy(self)->"bool4": ...

        @property
        def xywz(self)->"bool4": ...

        @xywz.setter
        def xywz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xyww(self)->"bool4": ...

        @property
        def xzxx(self)->"bool4": ...

        @property
        def xzxy(self)->"bool4": ...

        @property
        def xzxz(self)->"bool4": ...

        @property
        def xzxw(self)->"bool4": ...

        @property
        def xzyx(self)->"bool4": ...

        @property
        def xzyy(self)->"bool4": ...

        @property
        def xzyz(self)->"bool4": ...

        @property
        def xzyw(self)->"bool4": ...

        @xzyw.setter
        def xzyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzzx(self)->"bool4": ...

        @property
        def xzzy(self)->"bool4": ...

        @property
        def xzzz(self)->"bool4": ...

        @property
        def xzzw(self)->"bool4": ...

        @property
        def xzwx(self)->"bool4": ...

        @property
        def xzwy(self)->"bool4": ...

        @xzwy.setter
        def xzwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzwz(self)->"bool4": ...

        @property
        def xzww(self)->"bool4": ...

        @property
        def xwxx(self)->"bool4": ...

        @property
        def xwxy(self)->"bool4": ...

        @property
        def xwxz(self)->"bool4": ...

        @property
        def xwxw(self)->"bool4": ...

        @property
        def xwyx(self)->"bool4": ...

        @property
        def xwyy(self)->"bool4": ...

        @property
        def xwyz(self)->"bool4": ...

        @xwyz.setter
        def xwyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwyw(self)->"bool4": ...

        @property
        def xwzx(self)->"bool4": ...

        @property
        def xwzy(self)->"bool4": ...

        @xwzy.setter
        def xwzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwzz(self)->"bool4": ...

        @property
        def xwzw(self)->"bool4": ...

        @property
        def xwwx(self)->"bool4": ...

        @property
        def xwwy(self)->"bool4": ...

        @property
        def xwwz(self)->"bool4": ...

        @property
        def xwww(self)->"bool4": ...

        @property
        def yxxx(self)->"bool4": ...

        @property
        def yxxy(self)->"bool4": ...

        @property
        def yxxz(self)->"bool4": ...

        @property
        def yxxw(self)->"bool4": ...

        @property
        def yxyx(self)->"bool4": ...

        @property
        def yxyy(self)->"bool4": ...

        @property
        def yxyz(self)->"bool4": ...

        @property
        def yxyw(self)->"bool4": ...

        @property
        def yxzx(self)->"bool4": ...

        @property
        def yxzy(self)->"bool4": ...

        @property
        def yxzz(self)->"bool4": ...

        @property
        def yxzw(self)->"bool4": ...

        @yxzw.setter
        def yxzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxwx(self)->"bool4": ...

        @property
        def yxwy(self)->"bool4": ...

        @property
        def yxwz(self)->"bool4": ...

        @yxwz.setter
        def yxwz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxww(self)->"bool4": ...

        @property
        def yyxx(self)->"bool4": ...

        @property
        def yyxy(self)->"bool4": ...

        @property
        def yyxz(self)->"bool4": ...

        @property
        def yyxw(self)->"bool4": ...

        @property
        def yyyx(self)->"bool4": ...

        @property
        def yyyy(self)->"bool4": ...

        @property
        def yyyz(self)->"bool4": ...

        @property
        def yyyw(self)->"bool4": ...

        @property
        def yyzx(self)->"bool4": ...

        @property
        def yyzy(self)->"bool4": ...

        @property
        def yyzz(self)->"bool4": ...

        @property
        def yyzw(self)->"bool4": ...

        @property
        def yywx(self)->"bool4": ...

        @property
        def yywy(self)->"bool4": ...

        @property
        def yywz(self)->"bool4": ...

        @property
        def yyww(self)->"bool4": ...

        @property
        def yzxx(self)->"bool4": ...

        @property
        def yzxy(self)->"bool4": ...

        @property
        def yzxz(self)->"bool4": ...

        @property
        def yzxw(self)->"bool4": ...

        @yzxw.setter
        def yzxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzyx(self)->"bool4": ...

        @property
        def yzyy(self)->"bool4": ...

        @property
        def yzyz(self)->"bool4": ...

        @property
        def yzyw(self)->"bool4": ...

        @property
        def yzzx(self)->"bool4": ...

        @property
        def yzzy(self)->"bool4": ...

        @property
        def yzzz(self)->"bool4": ...

        @property
        def yzzw(self)->"bool4": ...

        @property
        def yzwx(self)->"bool4": ...

        @yzwx.setter
        def yzwx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzwy(self)->"bool4": ...

        @property
        def yzwz(self)->"bool4": ...

        @property
        def yzww(self)->"bool4": ...

        @property
        def ywxx(self)->"bool4": ...

        @property
        def ywxy(self)->"bool4": ...

        @property
        def ywxz(self)->"bool4": ...

        @ywxz.setter
        def ywxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywxw(self)->"bool4": ...

        @property
        def ywyx(self)->"bool4": ...

        @property
        def ywyy(self)->"bool4": ...

        @property
        def ywyz(self)->"bool4": ...

        @property
        def ywyw(self)->"bool4": ...

        @property
        def ywzx(self)->"bool4": ...

        @ywzx.setter
        def ywzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywzy(self)->"bool4": ...

        @property
        def ywzz(self)->"bool4": ...

        @property
        def ywzw(self)->"bool4": ...

        @property
        def ywwx(self)->"bool4": ...

        @property
        def ywwy(self)->"bool4": ...

        @property
        def ywwz(self)->"bool4": ...

        @property
        def ywww(self)->"bool4": ...

        @property
        def zxxx(self)->"bool4": ...

        @property
        def zxxy(self)->"bool4": ...

        @property
        def zxxz(self)->"bool4": ...

        @property
        def zxxw(self)->"bool4": ...

        @property
        def zxyx(self)->"bool4": ...

        @property
        def zxyy(self)->"bool4": ...

        @property
        def zxyz(self)->"bool4": ...

        @property
        def zxyw(self)->"bool4": ...

        @zxyw.setter
        def zxyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxzx(self)->"bool4": ...

        @property
        def zxzy(self)->"bool4": ...

        @property
        def zxzz(self)->"bool4": ...

        @property
        def zxzw(self)->"bool4": ...

        @property
        def zxwx(self)->"bool4": ...

        @property
        def zxwy(self)->"bool4": ...

        @zxwy.setter
        def zxwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxwz(self)->"bool4": ...

        @property
        def zxww(self)->"bool4": ...

        @property
        def zyxx(self)->"bool4": ...

        @property
        def zyxy(self)->"bool4": ...

        @property
        def zyxz(self)->"bool4": ...

        @property
        def zyxw(self)->"bool4": ...

        @zyxw.setter
        def zyxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zyyx(self)->"bool4": ...

        @property
        def zyyy(self)->"bool4": ...

        @property
        def zyyz(self)->"bool4": ...

        @property
        def zyyw(self)->"bool4": ...

        @property
        def zyzx(self)->"bool4": ...

        @property
        def zyzy(self)->"bool4": ...

        @property
        def zyzz(self)->"bool4": ...

        @property
        def zyzw(self)->"bool4": ...

        @property
        def zywx(self)->"bool4": ...

        @zywx.setter
        def zywx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zywy(self)->"bool4": ...

        @property
        def zywz(self)->"bool4": ...

        @property
        def zyww(self)->"bool4": ...

        @property
        def zzxx(self)->"bool4": ...

        @property
        def zzxy(self)->"bool4": ...

        @property
        def zzxz(self)->"bool4": ...

        @property
        def zzxw(self)->"bool4": ...

        @property
        def zzyx(self)->"bool4": ...

        @property
        def zzyy(self)->"bool4": ...

        @property
        def zzyz(self)->"bool4": ...

        @property
        def zzyw(self)->"bool4": ...

        @property
        def zzzx(self)->"bool4": ...

        @property
        def zzzy(self)->"bool4": ...

        @property
        def zzzz(self)->"bool4": ...

        @property
        def zzzw(self)->"bool4": ...

        @property
        def zzwx(self)->"bool4": ...

        @property
        def zzwy(self)->"bool4": ...

        @property
        def zzwz(self)->"bool4": ...

        @property
        def zzww(self)->"bool4": ...

        @property
        def zwxx(self)->"bool4": ...

        @property
        def zwxy(self)->"bool4": ...

        @zwxy.setter
        def zwxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwxz(self)->"bool4": ...

        @property
        def zwxw(self)->"bool4": ...

        @property
        def zwyx(self)->"bool4": ...

        @zwyx.setter
        def zwyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwyy(self)->"bool4": ...

        @property
        def zwyz(self)->"bool4": ...

        @property
        def zwyw(self)->"bool4": ...

        @property
        def zwzx(self)->"bool4": ...

        @property
        def zwzy(self)->"bool4": ...

        @property
        def zwzz(self)->"bool4": ...

        @property
        def zwzw(self)->"bool4": ...

        @property
        def zwwx(self)->"bool4": ...

        @property
        def zwwy(self)->"bool4": ...

        @property
        def zwwz(self)->"bool4": ...

        @property
        def zwww(self)->"bool4": ...

        @property
        def wxxx(self)->"bool4": ...

        @property
        def wxxy(self)->"bool4": ...

        @property
        def wxxz(self)->"bool4": ...

        @property
        def wxxw(self)->"bool4": ...

        @property
        def wxyx(self)->"bool4": ...

        @property
        def wxyy(self)->"bool4": ...

        @property
        def wxyz(self)->"bool4": ...

        @wxyz.setter
        def wxyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxyw(self)->"bool4": ...

        @property
        def wxzx(self)->"bool4": ...

        @property
        def wxzy(self)->"bool4": ...

        @wxzy.setter
        def wxzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxzz(self)->"bool4": ...

        @property
        def wxzw(self)->"bool4": ...

        @property
        def wxwx(self)->"bool4": ...

        @property
        def wxwy(self)->"bool4": ...

        @property
        def wxwz(self)->"bool4": ...

        @property
        def wxww(self)->"bool4": ...

        @property
        def wyxx(self)->"bool4": ...

        @property
        def wyxy(self)->"bool4": ...

        @property
        def wyxz(self)->"bool4": ...

        @wyxz.setter
        def wyxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyxw(self)->"bool4": ...

        @property
        def wyyx(self)->"bool4": ...

        @property
        def wyyy(self)->"bool4": ...

        @property
        def wyyz(self)->"bool4": ...

        @property
        def wyyw(self)->"bool4": ...

        @property
        def wyzx(self)->"bool4": ...

        @wyzx.setter
        def wyzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyzy(self)->"bool4": ...

        @property
        def wyzz(self)->"bool4": ...

        @property
        def wyzw(self)->"bool4": ...

        @property
        def wywx(self)->"bool4": ...

        @property
        def wywy(self)->"bool4": ...

        @property
        def wywz(self)->"bool4": ...

        @property
        def wyww(self)->"bool4": ...

        @property
        def wzxx(self)->"bool4": ...

        @property
        def wzxy(self)->"bool4": ...

        @wzxy.setter
        def wzxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzxz(self)->"bool4": ...

        @property
        def wzxw(self)->"bool4": ...

        @property
        def wzyx(self)->"bool4": ...

        @wzyx.setter
        def wzyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzyy(self)->"bool4": ...

        @property
        def wzyz(self)->"bool4": ...

        @property
        def wzyw(self)->"bool4": ...

        @property
        def wzzx(self)->"bool4": ...

        @property
        def wzzy(self)->"bool4": ...

        @property
        def wzzz(self)->"bool4": ...

        @property
        def wzzw(self)->"bool4": ...

        @property
        def wzwx(self)->"bool4": ...

        @property
        def wzwy(self)->"bool4": ...

        @property
        def wzwz(self)->"bool4": ...

        @property
        def wzww(self)->"bool4": ...

        @property
        def wwxx(self)->"bool4": ...

        @property
        def wwxy(self)->"bool4": ...

        @property
        def wwxz(self)->"bool4": ...

        @property
        def wwxw(self)->"bool4": ...

        @property
        def wwyx(self)->"bool4": ...

        @property
        def wwyy(self)->"bool4": ...

        @property
        def wwyz(self)->"bool4": ...

        @property
        def wwyw(self)->"bool4": ...

        @property
        def wwzx(self)->"bool4": ...

        @property
        def wwzy(self)->"bool4": ...

        @property
        def wwzz(self)->"bool4": ...

        @property
        def wwzw(self)->"bool4": ...

        @property
        def wwwx(self)->"bool4": ...

        @property
        def wwwy(self)->"bool4": ...

        @property
        def wwwz(self)->"bool4": ...

        @property
        def wwww(self)->"bool4": ...

        @property
        def r(self)->bool: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->bool: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def b(self)->bool: ...

        @b.setter
        def b(self, value:Union[bool, int, float])->None: ...

        @property
        def a(self)->bool: ...

        @a.setter
        def a(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->bool2: ...

        @property
        def rg(self)->bool2: ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def rb(self)->bool2: ...

        @rb.setter
        def rb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ra(self)->bool2: ...

        @ra.setter
        def ra(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->bool2: ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->bool2: ...

        @property
        def gb(self)->bool2: ...

        @gb.setter
        def gb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ga(self)->bool2: ...

        @ga.setter
        def ga(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def br(self)->bool2: ...

        @br.setter
        def br(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bg(self)->bool2: ...

        @bg.setter
        def bg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bb(self)->bool2: ...

        @property
        def ba(self)->bool2: ...

        @ba.setter
        def ba(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ar(self)->bool2: ...

        @ar.setter
        def ar(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ag(self)->bool2: ...

        @ag.setter
        def ag(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ab(self)->bool2: ...

        @ab.setter
        def ab(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def aa(self)->bool2: ...

        @property
        def rrr(self)->bool3: ...

        @property
        def rrg(self)->bool3: ...

        @property
        def rrb(self)->bool3: ...

        @property
        def rra(self)->bool3: ...

        @property
        def rgr(self)->bool3: ...

        @property
        def rgg(self)->bool3: ...

        @property
        def rgb(self)->bool3: ...

        @rgb.setter
        def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rga(self)->bool3: ...

        @rga.setter
        def rga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbr(self)->bool3: ...

        @property
        def rbg(self)->bool3: ...

        @rbg.setter
        def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbb(self)->bool3: ...

        @property
        def rba(self)->bool3: ...

        @rba.setter
        def rba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rar(self)->bool3: ...

        @property
        def rag(self)->bool3: ...

        @rag.setter
        def rag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rab(self)->bool3: ...

        @rab.setter
        def rab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def raa(self)->bool3: ...

        @property
        def grr(self)->bool3: ...

        @property
        def grg(self)->bool3: ...

        @property
        def grb(self)->bool3: ...

        @grb.setter
        def grb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gra(self)->bool3: ...

        @gra.setter
        def gra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ggr(self)->bool3: ...

        @property
        def ggg(self)->bool3: ...

        @property
        def ggb(self)->bool3: ...

        @property
        def gga(self)->bool3: ...

        @property
        def gbr(self)->bool3: ...

        @gbr.setter
        def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gbg(self)->bool3: ...

        @property
        def gbb(self)->bool3: ...

        @property
        def gba(self)->bool3: ...

        @gba.setter
        def gba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gar(self)->bool3: ...

        @gar.setter
        def gar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gag(self)->bool3: ...

        @property
        def gab(self)->bool3: ...

        @gab.setter
        def gab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gaa(self)->bool3: ...

        @property
        def brr(self)->bool3: ...

        @property
        def brg(self)->bool3: ...

        @brg.setter
        def brg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def brb(self)->bool3: ...

        @property
        def bra(self)->bool3: ...

        @bra.setter
        def bra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgr(self)->bool3: ...

        @bgr.setter
        def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgg(self)->bool3: ...

        @property
        def bgb(self)->bool3: ...

        @property
        def bga(self)->bool3: ...

        @bga.setter
        def bga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bbr(self)->bool3: ...

        @property
        def bbg(self)->bool3: ...

        @property
        def bbb(self)->bool3: ...

        @property
        def bba(self)->bool3: ...

        @property
        def bar(self)->bool3: ...

        @bar.setter
        def bar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bag(self)->bool3: ...

        @bag.setter
        def bag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bab(self)->bool3: ...

        @property
        def baa(self)->bool3: ...

        @property
        def arr(self)->bool3: ...

        @property
        def arg(self)->bool3: ...

        @arg.setter
        def arg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def arb(self)->bool3: ...

        @arb.setter
        def arb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ara(self)->bool3: ...

        @property
        def agr(self)->bool3: ...

        @agr.setter
        def agr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def agg(self)->bool3: ...

        @property
        def agb(self)->bool3: ...

        @agb.setter
        def agb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def aga(self)->bool3: ...

        @property
        def abr(self)->bool3: ...

        @abr.setter
        def abr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abg(self)->bool3: ...

        @abg.setter
        def abg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abb(self)->bool3: ...

        @property
        def aba(self)->bool3: ...

        @property
        def aar(self)->bool3: ...

        @property
        def aag(self)->bool3: ...

        @property
        def aab(self)->bool3: ...

        @property
        def aaa(self)->bool3: ...

        @property
        def rrrr(self)->"bool4": ...

        @property
        def rrrg(self)->"bool4": ...

        @property
        def rrrb(self)->"bool4": ...

        @property
        def rrra(self)->"bool4": ...

        @property
        def rrgr(self)->"bool4": ...

        @property
        def rrgg(self)->"bool4": ...

        @property
        def rrgb(self)->"bool4": ...

        @property
        def rrga(self)->"bool4": ...

        @property
        def rrbr(self)->"bool4": ...

        @property
        def rrbg(self)->"bool4": ...

        @property
        def rrbb(self)->"bool4": ...

        @property
        def rrba(self)->"bool4": ...

        @property
        def rrar(self)->"bool4": ...

        @property
        def rrag(self)->"bool4": ...

        @property
        def rrab(self)->"bool4": ...

        @property
        def rraa(self)->"bool4": ...

        @property
        def rgrr(self)->"bool4": ...

        @property
        def rgrg(self)->"bool4": ...

        @property
        def rgrb(self)->"bool4": ...

        @property
        def rgra(self)->"bool4": ...

        @property
        def rggr(self)->"bool4": ...

        @property
        def rggg(self)->"bool4": ...

        @property
        def rggb(self)->"bool4": ...

        @property
        def rgga(self)->"bool4": ...

        @property
        def rgbr(self)->"bool4": ...

        @property
        def rgbg(self)->"bool4": ...

        @property
        def rgbb(self)->"bool4": ...

        @property
        def rgba(self)->"bool4": ...

        @rgba.setter
        def rgba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgar(self)->"bool4": ...

        @property
        def rgag(self)->"bool4": ...

        @property
        def rgab(self)->"bool4": ...

        @rgab.setter
        def rgab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgaa(self)->"bool4": ...

        @property
        def rbrr(self)->"bool4": ...

        @property
        def rbrg(self)->"bool4": ...

        @property
        def rbrb(self)->"bool4": ...

        @property
        def rbra(self)->"bool4": ...

        @property
        def rbgr(self)->"bool4": ...

        @property
        def rbgg(self)->"bool4": ...

        @property
        def rbgb(self)->"bool4": ...

        @property
        def rbga(self)->"bool4": ...

        @rbga.setter
        def rbga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbbr(self)->"bool4": ...

        @property
        def rbbg(self)->"bool4": ...

        @property
        def rbbb(self)->"bool4": ...

        @property
        def rbba(self)->"bool4": ...

        @property
        def rbar(self)->"bool4": ...

        @property
        def rbag(self)->"bool4": ...

        @rbag.setter
        def rbag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbab(self)->"bool4": ...

        @property
        def rbaa(self)->"bool4": ...

        @property
        def rarr(self)->"bool4": ...

        @property
        def rarg(self)->"bool4": ...

        @property
        def rarb(self)->"bool4": ...

        @property
        def rara(self)->"bool4": ...

        @property
        def ragr(self)->"bool4": ...

        @property
        def ragg(self)->"bool4": ...

        @property
        def ragb(self)->"bool4": ...

        @ragb.setter
        def ragb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def raga(self)->"bool4": ...

        @property
        def rabr(self)->"bool4": ...

        @property
        def rabg(self)->"bool4": ...

        @rabg.setter
        def rabg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rabb(self)->"bool4": ...

        @property
        def raba(self)->"bool4": ...

        @property
        def raar(self)->"bool4": ...

        @property
        def raag(self)->"bool4": ...

        @property
        def raab(self)->"bool4": ...

        @property
        def raaa(self)->"bool4": ...

        @property
        def grrr(self)->"bool4": ...

        @property
        def grrg(self)->"bool4": ...

        @property
        def grrb(self)->"bool4": ...

        @property
        def grra(self)->"bool4": ...

        @property
        def grgr(self)->"bool4": ...

        @property
        def grgg(self)->"bool4": ...

        @property
        def grgb(self)->"bool4": ...

        @property
        def grga(self)->"bool4": ...

        @property
        def grbr(self)->"bool4": ...

        @property
        def grbg(self)->"bool4": ...

        @property
        def grbb(self)->"bool4": ...

        @property
        def grba(self)->"bool4": ...

        @grba.setter
        def grba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def grar(self)->"bool4": ...

        @property
        def grag(self)->"bool4": ...

        @property
        def grab(self)->"bool4": ...

        @grab.setter
        def grab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def graa(self)->"bool4": ...

        @property
        def ggrr(self)->"bool4": ...

        @property
        def ggrg(self)->"bool4": ...

        @property
        def ggrb(self)->"bool4": ...

        @property
        def ggra(self)->"bool4": ...

        @property
        def gggr(self)->"bool4": ...

        @property
        def gggg(self)->"bool4": ...

        @property
        def gggb(self)->"bool4": ...

        @property
        def ggga(self)->"bool4": ...

        @property
        def ggbr(self)->"bool4": ...

        @property
        def ggbg(self)->"bool4": ...

        @property
        def ggbb(self)->"bool4": ...

        @property
        def ggba(self)->"bool4": ...

        @property
        def ggar(self)->"bool4": ...

        @property
        def ggag(self)->"bool4": ...

        @property
        def ggab(self)->"bool4": ...

        @property
        def ggaa(self)->"bool4": ...

        @property
        def gbrr(self)->"bool4": ...

        @property
        def gbrg(self)->"bool4": ...

        @property
        def gbrb(self)->"bool4": ...

        @property
        def gbra(self)->"bool4": ...

        @gbra.setter
        def gbra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbgr(self)->"bool4": ...

        @property
        def gbgg(self)->"bool4": ...

        @property
        def gbgb(self)->"bool4": ...

        @property
        def gbga(self)->"bool4": ...

        @property
        def gbbr(self)->"bool4": ...

        @property
        def gbbg(self)->"bool4": ...

        @property
        def gbbb(self)->"bool4": ...

        @property
        def gbba(self)->"bool4": ...

        @property
        def gbar(self)->"bool4": ...

        @gbar.setter
        def gbar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbag(self)->"bool4": ...

        @property
        def gbab(self)->"bool4": ...

        @property
        def gbaa(self)->"bool4": ...

        @property
        def garr(self)->"bool4": ...

        @property
        def garg(self)->"bool4": ...

        @property
        def garb(self)->"bool4": ...

        @garb.setter
        def garb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gara(self)->"bool4": ...

        @property
        def gagr(self)->"bool4": ...

        @property
        def gagg(self)->"bool4": ...

        @property
        def gagb(self)->"bool4": ...

        @property
        def gaga(self)->"bool4": ...

        @property
        def gabr(self)->"bool4": ...

        @gabr.setter
        def gabr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gabg(self)->"bool4": ...

        @property
        def gabb(self)->"bool4": ...

        @property
        def gaba(self)->"bool4": ...

        @property
        def gaar(self)->"bool4": ...

        @property
        def gaag(self)->"bool4": ...

        @property
        def gaab(self)->"bool4": ...

        @property
        def gaaa(self)->"bool4": ...

        @property
        def brrr(self)->"bool4": ...

        @property
        def brrg(self)->"bool4": ...

        @property
        def brrb(self)->"bool4": ...

        @property
        def brra(self)->"bool4": ...

        @property
        def brgr(self)->"bool4": ...

        @property
        def brgg(self)->"bool4": ...

        @property
        def brgb(self)->"bool4": ...

        @property
        def brga(self)->"bool4": ...

        @brga.setter
        def brga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brbr(self)->"bool4": ...

        @property
        def brbg(self)->"bool4": ...

        @property
        def brbb(self)->"bool4": ...

        @property
        def brba(self)->"bool4": ...

        @property
        def brar(self)->"bool4": ...

        @property
        def brag(self)->"bool4": ...

        @brag.setter
        def brag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brab(self)->"bool4": ...

        @property
        def braa(self)->"bool4": ...

        @property
        def bgrr(self)->"bool4": ...

        @property
        def bgrg(self)->"bool4": ...

        @property
        def bgrb(self)->"bool4": ...

        @property
        def bgra(self)->"bool4": ...

        @bgra.setter
        def bgra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bggr(self)->"bool4": ...

        @property
        def bggg(self)->"bool4": ...

        @property
        def bggb(self)->"bool4": ...

        @property
        def bgga(self)->"bool4": ...

        @property
        def bgbr(self)->"bool4": ...

        @property
        def bgbg(self)->"bool4": ...

        @property
        def bgbb(self)->"bool4": ...

        @property
        def bgba(self)->"bool4": ...

        @property
        def bgar(self)->"bool4": ...

        @bgar.setter
        def bgar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bgag(self)->"bool4": ...

        @property
        def bgab(self)->"bool4": ...

        @property
        def bgaa(self)->"bool4": ...

        @property
        def bbrr(self)->"bool4": ...

        @property
        def bbrg(self)->"bool4": ...

        @property
        def bbrb(self)->"bool4": ...

        @property
        def bbra(self)->"bool4": ...

        @property
        def bbgr(self)->"bool4": ...

        @property
        def bbgg(self)->"bool4": ...

        @property
        def bbgb(self)->"bool4": ...

        @property
        def bbga(self)->"bool4": ...

        @property
        def bbbr(self)->"bool4": ...

        @property
        def bbbg(self)->"bool4": ...

        @property
        def bbbb(self)->"bool4": ...

        @property
        def bbba(self)->"bool4": ...

        @property
        def bbar(self)->"bool4": ...

        @property
        def bbag(self)->"bool4": ...

        @property
        def bbab(self)->"bool4": ...

        @property
        def bbaa(self)->"bool4": ...

        @property
        def barr(self)->"bool4": ...

        @property
        def barg(self)->"bool4": ...

        @barg.setter
        def barg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def barb(self)->"bool4": ...

        @property
        def bara(self)->"bool4": ...

        @property
        def bagr(self)->"bool4": ...

        @bagr.setter
        def bagr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bagg(self)->"bool4": ...

        @property
        def bagb(self)->"bool4": ...

        @property
        def baga(self)->"bool4": ...

        @property
        def babr(self)->"bool4": ...

        @property
        def babg(self)->"bool4": ...

        @property
        def babb(self)->"bool4": ...

        @property
        def baba(self)->"bool4": ...

        @property
        def baar(self)->"bool4": ...

        @property
        def baag(self)->"bool4": ...

        @property
        def baab(self)->"bool4": ...

        @property
        def baaa(self)->"bool4": ...

        @property
        def arrr(self)->"bool4": ...

        @property
        def arrg(self)->"bool4": ...

        @property
        def arrb(self)->"bool4": ...

        @property
        def arra(self)->"bool4": ...

        @property
        def argr(self)->"bool4": ...

        @property
        def argg(self)->"bool4": ...

        @property
        def argb(self)->"bool4": ...

        @argb.setter
        def argb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arga(self)->"bool4": ...

        @property
        def arbr(self)->"bool4": ...

        @property
        def arbg(self)->"bool4": ...

        @arbg.setter
        def arbg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arbb(self)->"bool4": ...

        @property
        def arba(self)->"bool4": ...

        @property
        def arar(self)->"bool4": ...

        @property
        def arag(self)->"bool4": ...

        @property
        def arab(self)->"bool4": ...

        @property
        def araa(self)->"bool4": ...

        @property
        def agrr(self)->"bool4": ...

        @property
        def agrg(self)->"bool4": ...

        @property
        def agrb(self)->"bool4": ...

        @agrb.setter
        def agrb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agra(self)->"bool4": ...

        @property
        def aggr(self)->"bool4": ...

        @property
        def aggg(self)->"bool4": ...

        @property
        def aggb(self)->"bool4": ...

        @property
        def agga(self)->"bool4": ...

        @property
        def agbr(self)->"bool4": ...

        @agbr.setter
        def agbr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agbg(self)->"bool4": ...

        @property
        def agbb(self)->"bool4": ...

        @property
        def agba(self)->"bool4": ...

        @property
        def agar(self)->"bool4": ...

        @property
        def agag(self)->"bool4": ...

        @property
        def agab(self)->"bool4": ...

        @property
        def agaa(self)->"bool4": ...

        @property
        def abrr(self)->"bool4": ...

        @property
        def abrg(self)->"bool4": ...

        @abrg.setter
        def abrg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abrb(self)->"bool4": ...

        @property
        def abra(self)->"bool4": ...

        @property
        def abgr(self)->"bool4": ...

        @abgr.setter
        def abgr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abgg(self)->"bool4": ...

        @property
        def abgb(self)->"bool4": ...

        @property
        def abga(self)->"bool4": ...

        @property
        def abbr(self)->"bool4": ...

        @property
        def abbg(self)->"bool4": ...

        @property
        def abbb(self)->"bool4": ...

        @property
        def abba(self)->"bool4": ...

        @property
        def abar(self)->"bool4": ...

        @property
        def abag(self)->"bool4": ...

        @property
        def abab(self)->"bool4": ...

        @property
        def abaa(self)->"bool4": ...

        @property
        def aarr(self)->"bool4": ...

        @property
        def aarg(self)->"bool4": ...

        @property
        def aarb(self)->"bool4": ...

        @property
        def aara(self)->"bool4": ...

        @property
        def aagr(self)->"bool4": ...

        @property
        def aagg(self)->"bool4": ...

        @property
        def aagb(self)->"bool4": ...

        @property
        def aaga(self)->"bool4": ...

        @property
        def aabr(self)->"bool4": ...

        @property
        def aabg(self)->"bool4": ...

        @property
        def aabb(self)->"bool4": ...

        @property
        def aaba(self)->"bool4": ...

        @property
        def aaar(self)->"bool4": ...

        @property
        def aaag(self)->"bool4": ...

        @property
        def aaab(self)->"bool4": ...

        @property
        def aaaa(self)->"bool4": ...

        @property
        def s(self)->bool: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->bool: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def p(self)->bool: ...

        @p.setter
        def p(self, value:Union[bool, int, float])->None: ...

        @property
        def q(self)->bool: ...

        @q.setter
        def q(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->bool2: ...

        @property
        def st(self)->bool2: ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sp(self)->bool2: ...

        @sp.setter
        def sp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sq(self)->bool2: ...

        @sq.setter
        def sq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->bool2: ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->bool2: ...

        @property
        def tp(self)->bool2: ...

        @tp.setter
        def tp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tq(self)->bool2: ...

        @tq.setter
        def tq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ps(self)->bool2: ...

        @ps.setter
        def ps(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pt(self)->bool2: ...

        @pt.setter
        def pt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pp(self)->bool2: ...

        @property
        def pq(self)->bool2: ...

        @pq.setter
        def pq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qs(self)->bool2: ...

        @qs.setter
        def qs(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qt(self)->bool2: ...

        @qt.setter
        def qt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qp(self)->bool2: ...

        @qp.setter
        def qp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qq(self)->bool2: ...

        @property
        def sss(self)->bool3: ...

        @property
        def sst(self)->bool3: ...

        @property
        def ssp(self)->bool3: ...

        @property
        def ssq(self)->bool3: ...

        @property
        def sts(self)->bool3: ...

        @property
        def stt(self)->bool3: ...

        @property
        def stp(self)->bool3: ...

        @stp.setter
        def stp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def stq(self)->bool3: ...

        @stq.setter
        def stq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sps(self)->bool3: ...

        @property
        def spt(self)->bool3: ...

        @spt.setter
        def spt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def spp(self)->bool3: ...

        @property
        def spq(self)->bool3: ...

        @spq.setter
        def spq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqs(self)->bool3: ...

        @property
        def sqt(self)->bool3: ...

        @sqt.setter
        def sqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqp(self)->bool3: ...

        @sqp.setter
        def sqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqq(self)->bool3: ...

        @property
        def tss(self)->bool3: ...

        @property
        def tst(self)->bool3: ...

        @property
        def tsp(self)->bool3: ...

        @tsp.setter
        def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tsq(self)->bool3: ...

        @tsq.setter
        def tsq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tts(self)->bool3: ...

        @property
        def ttt(self)->bool3: ...

        @property
        def ttp(self)->bool3: ...

        @property
        def ttq(self)->bool3: ...

        @property
        def tps(self)->bool3: ...

        @tps.setter
        def tps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tpt(self)->bool3: ...

        @property
        def tpp(self)->bool3: ...

        @property
        def tpq(self)->bool3: ...

        @tpq.setter
        def tpq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqs(self)->bool3: ...

        @tqs.setter
        def tqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqt(self)->bool3: ...

        @property
        def tqp(self)->bool3: ...

        @tqp.setter
        def tqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqq(self)->bool3: ...

        @property
        def pss(self)->bool3: ...

        @property
        def pst(self)->bool3: ...

        @pst.setter
        def pst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def psp(self)->bool3: ...

        @property
        def psq(self)->bool3: ...

        @psq.setter
        def psq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pts(self)->bool3: ...

        @pts.setter
        def pts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ptt(self)->bool3: ...

        @property
        def ptp(self)->bool3: ...

        @property
        def ptq(self)->bool3: ...

        @ptq.setter
        def ptq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pps(self)->bool3: ...

        @property
        def ppt(self)->bool3: ...

        @property
        def ppp(self)->bool3: ...

        @property
        def ppq(self)->bool3: ...

        @property
        def pqs(self)->bool3: ...

        @pqs.setter
        def pqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqt(self)->bool3: ...

        @pqt.setter
        def pqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqp(self)->bool3: ...

        @property
        def pqq(self)->bool3: ...

        @property
        def qss(self)->bool3: ...

        @property
        def qst(self)->bool3: ...

        @qst.setter
        def qst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsp(self)->bool3: ...

        @qsp.setter
        def qsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsq(self)->bool3: ...

        @property
        def qts(self)->bool3: ...

        @qts.setter
        def qts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtt(self)->bool3: ...

        @property
        def qtp(self)->bool3: ...

        @qtp.setter
        def qtp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtq(self)->bool3: ...

        @property
        def qps(self)->bool3: ...

        @qps.setter
        def qps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpt(self)->bool3: ...

        @qpt.setter
        def qpt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpp(self)->bool3: ...

        @property
        def qpq(self)->bool3: ...

        @property
        def qqs(self)->bool3: ...

        @property
        def qqt(self)->bool3: ...

        @property
        def qqp(self)->bool3: ...

        @property
        def qqq(self)->bool3: ...

        @property
        def ssss(self)->"bool4": ...

        @property
        def ssst(self)->"bool4": ...

        @property
        def sssp(self)->"bool4": ...

        @property
        def sssq(self)->"bool4": ...

        @property
        def ssts(self)->"bool4": ...

        @property
        def sstt(self)->"bool4": ...

        @property
        def sstp(self)->"bool4": ...

        @property
        def sstq(self)->"bool4": ...

        @property
        def ssps(self)->"bool4": ...

        @property
        def sspt(self)->"bool4": ...

        @property
        def sspp(self)->"bool4": ...

        @property
        def sspq(self)->"bool4": ...

        @property
        def ssqs(self)->"bool4": ...

        @property
        def ssqt(self)->"bool4": ...

        @property
        def ssqp(self)->"bool4": ...

        @property
        def ssqq(self)->"bool4": ...

        @property
        def stss(self)->"bool4": ...

        @property
        def stst(self)->"bool4": ...

        @property
        def stsp(self)->"bool4": ...

        @property
        def stsq(self)->"bool4": ...

        @property
        def stts(self)->"bool4": ...

        @property
        def sttt(self)->"bool4": ...

        @property
        def sttp(self)->"bool4": ...

        @property
        def sttq(self)->"bool4": ...

        @property
        def stps(self)->"bool4": ...

        @property
        def stpt(self)->"bool4": ...

        @property
        def stpp(self)->"bool4": ...

        @property
        def stpq(self)->"bool4": ...

        @stpq.setter
        def stpq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqs(self)->"bool4": ...

        @property
        def stqt(self)->"bool4": ...

        @property
        def stqp(self)->"bool4": ...

        @stqp.setter
        def stqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqq(self)->"bool4": ...

        @property
        def spss(self)->"bool4": ...

        @property
        def spst(self)->"bool4": ...

        @property
        def spsp(self)->"bool4": ...

        @property
        def spsq(self)->"bool4": ...

        @property
        def spts(self)->"bool4": ...

        @property
        def sptt(self)->"bool4": ...

        @property
        def sptp(self)->"bool4": ...

        @property
        def sptq(self)->"bool4": ...

        @sptq.setter
        def sptq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spps(self)->"bool4": ...

        @property
        def sppt(self)->"bool4": ...

        @property
        def sppp(self)->"bool4": ...

        @property
        def sppq(self)->"bool4": ...

        @property
        def spqs(self)->"bool4": ...

        @property
        def spqt(self)->"bool4": ...

        @spqt.setter
        def spqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spqp(self)->"bool4": ...

        @property
        def spqq(self)->"bool4": ...

        @property
        def sqss(self)->"bool4": ...

        @property
        def sqst(self)->"bool4": ...

        @property
        def sqsp(self)->"bool4": ...

        @property
        def sqsq(self)->"bool4": ...

        @property
        def sqts(self)->"bool4": ...

        @property
        def sqtt(self)->"bool4": ...

        @property
        def sqtp(self)->"bool4": ...

        @sqtp.setter
        def sqtp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqtq(self)->"bool4": ...

        @property
        def sqps(self)->"bool4": ...

        @property
        def sqpt(self)->"bool4": ...

        @sqpt.setter
        def sqpt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqpp(self)->"bool4": ...

        @property
        def sqpq(self)->"bool4": ...

        @property
        def sqqs(self)->"bool4": ...

        @property
        def sqqt(self)->"bool4": ...

        @property
        def sqqp(self)->"bool4": ...

        @property
        def sqqq(self)->"bool4": ...

        @property
        def tsss(self)->"bool4": ...

        @property
        def tsst(self)->"bool4": ...

        @property
        def tssp(self)->"bool4": ...

        @property
        def tssq(self)->"bool4": ...

        @property
        def tsts(self)->"bool4": ...

        @property
        def tstt(self)->"bool4": ...

        @property
        def tstp(self)->"bool4": ...

        @property
        def tstq(self)->"bool4": ...

        @property
        def tsps(self)->"bool4": ...

        @property
        def tspt(self)->"bool4": ...

        @property
        def tspp(self)->"bool4": ...

        @property
        def tspq(self)->"bool4": ...

        @tspq.setter
        def tspq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqs(self)->"bool4": ...

        @property
        def tsqt(self)->"bool4": ...

        @property
        def tsqp(self)->"bool4": ...

        @tsqp.setter
        def tsqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqq(self)->"bool4": ...

        @property
        def ttss(self)->"bool4": ...

        @property
        def ttst(self)->"bool4": ...

        @property
        def ttsp(self)->"bool4": ...

        @property
        def ttsq(self)->"bool4": ...

        @property
        def ttts(self)->"bool4": ...

        @property
        def tttt(self)->"bool4": ...

        @property
        def tttp(self)->"bool4": ...

        @property
        def tttq(self)->"bool4": ...

        @property
        def ttps(self)->"bool4": ...

        @property
        def ttpt(self)->"bool4": ...

        @property
        def ttpp(self)->"bool4": ...

        @property
        def ttpq(self)->"bool4": ...

        @property
        def ttqs(self)->"bool4": ...

        @property
        def ttqt(self)->"bool4": ...

        @property
        def ttqp(self)->"bool4": ...

        @property
        def ttqq(self)->"bool4": ...

        @property
        def tpss(self)->"bool4": ...

        @property
        def tpst(self)->"bool4": ...

        @property
        def tpsp(self)->"bool4": ...

        @property
        def tpsq(self)->"bool4": ...

        @tpsq.setter
        def tpsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpts(self)->"bool4": ...

        @property
        def tptt(self)->"bool4": ...

        @property
        def tptp(self)->"bool4": ...

        @property
        def tptq(self)->"bool4": ...

        @property
        def tpps(self)->"bool4": ...

        @property
        def tppt(self)->"bool4": ...

        @property
        def tppp(self)->"bool4": ...

        @property
        def tppq(self)->"bool4": ...

        @property
        def tpqs(self)->"bool4": ...

        @tpqs.setter
        def tpqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpqt(self)->"bool4": ...

        @property
        def tpqp(self)->"bool4": ...

        @property
        def tpqq(self)->"bool4": ...

        @property
        def tqss(self)->"bool4": ...

        @property
        def tqst(self)->"bool4": ...

        @property
        def tqsp(self)->"bool4": ...

        @tqsp.setter
        def tqsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqsq(self)->"bool4": ...

        @property
        def tqts(self)->"bool4": ...

        @property
        def tqtt(self)->"bool4": ...

        @property
        def tqtp(self)->"bool4": ...

        @property
        def tqtq(self)->"bool4": ...

        @property
        def tqps(self)->"bool4": ...

        @tqps.setter
        def tqps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqpt(self)->"bool4": ...

        @property
        def tqpp(self)->"bool4": ...

        @property
        def tqpq(self)->"bool4": ...

        @property
        def tqqs(self)->"bool4": ...

        @property
        def tqqt(self)->"bool4": ...

        @property
        def tqqp(self)->"bool4": ...

        @property
        def tqqq(self)->"bool4": ...

        @property
        def psss(self)->"bool4": ...

        @property
        def psst(self)->"bool4": ...

        @property
        def pssp(self)->"bool4": ...

        @property
        def pssq(self)->"bool4": ...

        @property
        def psts(self)->"bool4": ...

        @property
        def pstt(self)->"bool4": ...

        @property
        def pstp(self)->"bool4": ...

        @property
        def pstq(self)->"bool4": ...

        @pstq.setter
        def pstq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psps(self)->"bool4": ...

        @property
        def pspt(self)->"bool4": ...

        @property
        def pspp(self)->"bool4": ...

        @property
        def pspq(self)->"bool4": ...

        @property
        def psqs(self)->"bool4": ...

        @property
        def psqt(self)->"bool4": ...

        @psqt.setter
        def psqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psqp(self)->"bool4": ...

        @property
        def psqq(self)->"bool4": ...

        @property
        def ptss(self)->"bool4": ...

        @property
        def ptst(self)->"bool4": ...

        @property
        def ptsp(self)->"bool4": ...

        @property
        def ptsq(self)->"bool4": ...

        @ptsq.setter
        def ptsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptts(self)->"bool4": ...

        @property
        def pttt(self)->"bool4": ...

        @property
        def pttp(self)->"bool4": ...

        @property
        def pttq(self)->"bool4": ...

        @property
        def ptps(self)->"bool4": ...

        @property
        def ptpt(self)->"bool4": ...

        @property
        def ptpp(self)->"bool4": ...

        @property
        def ptpq(self)->"bool4": ...

        @property
        def ptqs(self)->"bool4": ...

        @ptqs.setter
        def ptqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptqt(self)->"bool4": ...

        @property
        def ptqp(self)->"bool4": ...

        @property
        def ptqq(self)->"bool4": ...

        @property
        def ppss(self)->"bool4": ...

        @property
        def ppst(self)->"bool4": ...

        @property
        def ppsp(self)->"bool4": ...

        @property
        def ppsq(self)->"bool4": ...

        @property
        def ppts(self)->"bool4": ...

        @property
        def pptt(self)->"bool4": ...

        @property
        def pptp(self)->"bool4": ...

        @property
        def pptq(self)->"bool4": ...

        @property
        def ppps(self)->"bool4": ...

        @property
        def pppt(self)->"bool4": ...

        @property
        def pppp(self)->"bool4": ...

        @property
        def pppq(self)->"bool4": ...

        @property
        def ppqs(self)->"bool4": ...

        @property
        def ppqt(self)->"bool4": ...

        @property
        def ppqp(self)->"bool4": ...

        @property
        def ppqq(self)->"bool4": ...

        @property
        def pqss(self)->"bool4": ...

        @property
        def pqst(self)->"bool4": ...

        @pqst.setter
        def pqst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqsp(self)->"bool4": ...

        @property
        def pqsq(self)->"bool4": ...

        @property
        def pqts(self)->"bool4": ...

        @pqts.setter
        def pqts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqtt(self)->"bool4": ...

        @property
        def pqtp(self)->"bool4": ...

        @property
        def pqtq(self)->"bool4": ...

        @property
        def pqps(self)->"bool4": ...

        @property
        def pqpt(self)->"bool4": ...

        @property
        def pqpp(self)->"bool4": ...

        @property
        def pqpq(self)->"bool4": ...

        @property
        def pqqs(self)->"bool4": ...

        @property
        def pqqt(self)->"bool4": ...

        @property
        def pqqp(self)->"bool4": ...

        @property
        def pqqq(self)->"bool4": ...

        @property
        def qsss(self)->"bool4": ...

        @property
        def qsst(self)->"bool4": ...

        @property
        def qssp(self)->"bool4": ...

        @property
        def qssq(self)->"bool4": ...

        @property
        def qsts(self)->"bool4": ...

        @property
        def qstt(self)->"bool4": ...

        @property
        def qstp(self)->"bool4": ...

        @qstp.setter
        def qstp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qstq(self)->"bool4": ...

        @property
        def qsps(self)->"bool4": ...

        @property
        def qspt(self)->"bool4": ...

        @qspt.setter
        def qspt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qspp(self)->"bool4": ...

        @property
        def qspq(self)->"bool4": ...

        @property
        def qsqs(self)->"bool4": ...

        @property
        def qsqt(self)->"bool4": ...

        @property
        def qsqp(self)->"bool4": ...

        @property
        def qsqq(self)->"bool4": ...

        @property
        def qtss(self)->"bool4": ...

        @property
        def qtst(self)->"bool4": ...

        @property
        def qtsp(self)->"bool4": ...

        @qtsp.setter
        def qtsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtsq(self)->"bool4": ...

        @property
        def qtts(self)->"bool4": ...

        @property
        def qttt(self)->"bool4": ...

        @property
        def qttp(self)->"bool4": ...

        @property
        def qttq(self)->"bool4": ...

        @property
        def qtps(self)->"bool4": ...

        @qtps.setter
        def qtps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtpt(self)->"bool4": ...

        @property
        def qtpp(self)->"bool4": ...

        @property
        def qtpq(self)->"bool4": ...

        @property
        def qtqs(self)->"bool4": ...

        @property
        def qtqt(self)->"bool4": ...

        @property
        def qtqp(self)->"bool4": ...

        @property
        def qtqq(self)->"bool4": ...

        @property
        def qpss(self)->"bool4": ...

        @property
        def qpst(self)->"bool4": ...

        @qpst.setter
        def qpst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qpsp(self)->"bool4": ...

        @property
        def qpsq(self)->"bool4": ...

        @property
        def qpts(self)->"bool4": ...

        @qpts.setter
        def qpts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qptt(self)->"bool4": ...

        @property
        def qptp(self)->"bool4": ...

        @property
        def qptq(self)->"bool4": ...

        @property
        def qpps(self)->"bool4": ...

        @property
        def qppt(self)->"bool4": ...

        @property
        def qppp(self)->"bool4": ...

        @property
        def qppq(self)->"bool4": ...

        @property
        def qpqs(self)->"bool4": ...

        @property
        def qpqt(self)->"bool4": ...

        @property
        def qpqp(self)->"bool4": ...

        @property
        def qpqq(self)->"bool4": ...

        @property
        def qqss(self)->"bool4": ...

        @property
        def qqst(self)->"bool4": ...

        @property
        def qqsp(self)->"bool4": ...

        @property
        def qqsq(self)->"bool4": ...

        @property
        def qqts(self)->"bool4": ...

        @property
        def qqtt(self)->"bool4": ...

        @property
        def qqtp(self)->"bool4": ...

        @property
        def qqtq(self)->"bool4": ...

        @property
        def qqps(self)->"bool4": ...

        @property
        def qqpt(self)->"bool4": ...

        @property
        def qqpp(self)->"bool4": ...

        @property
        def qqpq(self)->"bool4": ...

        @property
        def qqqs(self)->"bool4": ...

        @property
        def qqqt(self)->"bool4": ...

        @property
        def qqqp(self)->"bool4": ...

        @property
        def qqqq(self)->"bool4": ...
        # --- END generated swizzles ---
