import ctypes
from typing import TYPE_CHECKING, Union

from .genVec2 import genVec2

if TYPE_CHECKING:

    from .double3 import double3
    from .double4 import double4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class double2(genVec2):

    _fields_ = [
        ('x', ctypes.c_double),
        ('y', ctypes.c_double)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_double

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->float: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->float: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->"double2": ...

        @property
        def xy(self)->"double2": ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->"double2": ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->"double2": ...

        @property
        def xxx(self)->double3: ...

        @property
        def xxy(self)->double3: ...

        @property
        def xyx(self)->double3: ...

        @property
        def xyy(self)->double3: ...

        @property
        def yxx(self)->double3: ...

        @property
        def yxy(self)->double3: ...

        @property
        def yyx(self)->double3: ...

        @property
        def yyy(self)->double3: ...

        @property
        def xxxx(self)->double4: ...

        @property
        def xxxy(self)->double4: ...

        @property
        def xxyx(self)->double4: ...

        @property
        def xxyy(self)->double4: ...

        @property
        def xyxx(self)->double4: ...

        @property
        def xyxy(self)->double4: ...

        @property
        def xyyx(self)->double4: ...

        @property
        def xyyy(self)->double4: ...

        @property
        def yxxx(self)->double4: ...

        @property
        def yxxy(self)->double4: ...

        @property
        def yxyx(self)->double4: ...

        @property
        def yxyy(self)->double4: ...

        @property
        def yyxx(self)->double4: ...

        @property
        def yyxy(self)->double4: ...

        @property
        def yyyx(self)->double4: ...

        @property
        def yyyy(self)->double4: ...

        @property
        def r(self)->float: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->float: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->"double2": ...

        @property
        def rg(self)->"double2": ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->"double2": ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->"double2": ...

        @property
        def rrr(self)->double3: ...

        @property
        def rrg(self)->double3: ...

        @property
        def rgr(self)->double3: ...

        @property
        def rgg(self)->double3: ...

        @property
        def grr(self)->double3: ...

        @property
        def grg(self)->double3: ...

        @property
        def ggr(self)->double3: ...

        @property
        def ggg(self)->double3: ...

        @property
        def rrrr(self)->double4: ...

        @property
        def rrrg(self)->double4: ...

        @property
        def rrgr(self)->double4: ...

        @property
        def rrgg(self)->double4: ...

        @property
        def rgrr(self)->double4: ...

        @property
        def rgrg(self)->double4: ...

        @property
        def rggr(self)->double4: ...

        @property
        def rggg(self)->double4: ...

        @property
        def grrr(self)->double4: ...

        @property
        def grrg(self)->double4: ...

        @property
        def grgr(self)->double4: ...

        @property
        def grgg(self)->double4: ...

        @property
        def ggrr(self)->double4: ...

        @property
        def ggrg(self)->double4: ...

        @property
        def gggr(self)->double4: ...

        @property
        def gggg(self)->double4: ...

        @property
        def s(self)->float: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->float: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->"double2": ...

        @property
        def st(self)->"double2": ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->"double2": ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->"double2": ...

        @property
        def sss(self)->double3: ...

        @property
        def sst(self)->double3: ...

        @property
        def sts(self)->double3: ...

        @property
        def stt(self)->double3: ...

        @property
        def tss(self)->double3: ...

        @property
        def tst(self)->double3: ...

        @property
        def tts(self)->double3: ...

        @property
        def ttt(self)->double3: ...

        @property
        def ssss(self)->double4: ...

        @property
        def ssst(self)->double4: ...

        @property
        def ssts(self)->double4: ...

        @property
        def sstt(self)->double4: ...

        @property
        def stss(self)->double4: ...

        @property
        def stst(self)->double4: ...

        @property
        def stts(self)->double4: ...

        @property
        def sttt(self)->double4: ...

        @property
        def tsss(self)->double4: ...

        @property
        def tsst(self)->double4: ...

        @property
        def tsts(self)->double4: ...

        @property
        def tstt(self)->double4: ...

        @property
        def ttss(self)->double4: ...

        @property
        def ttst(self)->double4: ...

        @property
        def ttts(self)->double4: ...

        @property
        def tttt(self)->double4: ...
        # --- END generated swizzles ---
