import ctypes
from typing import TYPE_CHECKING, Union

from .genVec4 import genVec4

if TYPE_CHECKING:

    from .float2 import float2
    from .float3 import float3
    from .genVec2 import genVec2
    from .genVec3 import genVec3

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class float4(genVec4):

    _fields_ = [
        ('x', ctypes.c_float),
        ('y', ctypes.c_float),
        ('z', ctypes.c_float),
        ('w', ctypes.c_float)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_float

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->float: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->float: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def z(self)->float: ...

        @z.setter
        def z(self, value:Union[bool, int, float])->None: ...

        @property
        def w(self)->float: ...

        @w.setter
        def w(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->float2: ...

        @property
        def xy(self)->float2: ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xz(self)->float2: ...

        @xz.setter
        def xz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xw(self)->float2: ...

        @xw.setter
        def xw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->float2: ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->float2: ...

        @property
        def yz(self)->float2: ...

        @yz.setter
        def yz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yw(self)->float2: ...

        @yw.setter
        def yw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zx(self)->float2: ...

        @zx.setter
        def zx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zy(self)->float2: ...

        @zy.setter
        def zy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zz(self)->float2: ...

        @property
        def zw(self)->float2: ...

        @zw.setter
        def zw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wx(self)->float2: ...

        @wx.setter
        def wx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wy(self)->float2: ...

        @wy.setter
        def wy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wz(self)->float2: ...

        @wz.setter
        def wz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ww(self)->float2: ...

        @property
        def xxx(self)->float3: ...

        @property
        def xxy(self)->float3: ...

        @property
        def xxz(self)->float3: ...

        @property
        def xxw(self)->float3: ...

        @property
        def xyx(self)->float3: ...

        @property
        def xyy(self)->float3: ...

        @property
        def xyz(self)->float3: ...

        @xyz.setter
        def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xyw(self)->float3: ...

        @xyw.setter
        def xyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzx(self)->float3: ...

        @property
        def xzy(self)->float3: ...

        @xzy.setter
        def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzz(self)->float3: ...

        @property
        def xzw(self)->float3: ...

        @xzw.setter
        def xzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwx(self)->float3: ...

        @property
        def xwy(self)->float3: ...

        @xwy.setter
        def xwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwz(self)->float3: ...

        @xwz.setter
        def xwz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xww(self)->float3: ...

        @property
        def yxx(self)->float3: ...

        @property
        def yxy(self)->float3: ...

        @property
        def yxz(self)->float3: ...

        @yxz.setter
        def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yxw(self)->float3: ...

        @yxw.setter
        def yxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yyx(self)->float3: ...

        @property
        def yyy(self)->float3: ...

        @property
        def yyz(self)->float3: ...

        @property
        def yyw(self)->float3: ...

        @property
        def yzx(self)->float3: ...

        @yzx.setter
        def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yzy(self)->float3: ...

        @property
        def yzz(self)->float3: ...

        @property
        def yzw(self)->float3: ...

        @yzw.setter
        def yzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywx(self)->float3: ...

        @ywx.setter
        def ywx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywy(self)->float3: ...

        @property
        def ywz(self)->float3: ...

        @ywz.setter
        def ywz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yww(self)->float3: ...

        @property
        def zxx(self)->float3: ...

        @property
        def zxy(self)->float3: ...

        @zxy.setter
        def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zxz(self)->float3: ...

        @property
        def zxw(self)->float3: ...

        @zxw.setter
        def zxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyx(self)->float3: ...

        @zyx.setter
        def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyy(self)->float3: ...

        @property
        def zyz(self)->float3: ...

        @property
        def zyw(self)->float3: ...

        @zyw.setter
        def zyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zzx(self)->float3: ...

        @property
        def zzy(self)->float3: ...

        @property
        def zzz(self)->float3: ...

        @property
        def zzw(self)->float3: ...

        @property
        def zwx(self)->float3: ...

        @zwx.setter
        def zwx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwy(self)->float3: ...

        @zwy.setter
        def zwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwz(self)->float3: ...

        @property
        def zww(self)->float3: ...

        @property
        def wxx(self)->float3: ...

        @property
        def wxy(self)->float3: ...

        @wxy.setter
        def wxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxz(self)->float3: ...

        @wxz.setter
        def wxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxw(self)->float3: ...

        @property
        def wyx(self)->float3: ...

        @wyx.setter
        def wyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyy(self)->float3: ...

        @property
        def wyz(self)->float3: ...

        @wyz.setter
        def wyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyw(self)->float3: ...

        @property
        def wzx(self)->float3: ...

        @wzx.setter
        def wzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzy(self)->float3: ...

        @wzy.setter
        def wzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzz(self)->float3: ...

        @property
        def wzw(self)->float3: ...

        @property
        def wwx(self)->float3: ...

        @property
        def wwy(self)->float3: ...

        @property
        def wwz(self)->float3: ...

        @property
        def www(self)->float3: ...

        @property
        def xxxx(self)->"float4": ...

        @property
        def xxxy(self)->"float4": ...

        @property
        def xxxz(self)->"float4": ...

        @property
        def xxxw(self)->"float4": ...

        @property
        def xxyx(self)->"float4": ...

        @property
        def xxyy(self)->"float4": ...

        @property
        def xxyz(self)->"float4": ...

        @property
        def xxyw(self)->"float4": ...

        @property
        def xxzx(self)->"float4": ...

        @property
        def xxzy(self)->"float4": ...

        @property
        def xxzz(self)->"float4": ...

        @property
        def xxzw(self)->"float4": ...

        @property
        def xxwx(self)->"float4": ...

        @property
        def xxwy(self)->"float4": ...

        @property
        def xxwz(self)->"float4": ...

        @property
        def xxww(self)->"float4": ...

        @property
        def xyxx(self)->"float4": ...

        @property
        def xyxy(self)->"float4": ...

        @property
        def xyxz(self)->"float4": ...

        @property
        def xyxw(self)->"float4": ...

        @property
        def xyyx(self)->"float4": ...

        @property
        def xyyy(self)->"float4": ...

        @property
        def xyyz(self)->"float4": ...

        @property
        def xyyw(self)->"float4": ...

        @property
        def xyzx(self)->"float4": ...

        @property
        def xyzy(self)->"float4": ...

        @property
        def xyzz(self)->"float4": ...

        @property
        def xyzw(self)->"float4": ...

        @xyzw.setter
        def xyzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xywx(self)->"float4": ...

        @property
        def xywy(self)->"float4": ...

        @property
        def xywz(self)->"float4": ...

        @xywz.setter
        def xywz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xyww(self)->"float4": ...

        @property
        def xzxx(self)->"float4": ...

        @property
        def xzxy(self)->"float4": ...

        @property
        def xzxz(self)->"float4": ...

        @property
        def xzxw(self)->"float4": ...

        @property
        def xzyx(self)->"float4": ...

        @property
        def xzyy(self)->"float4": ...

        @property
        def xzyz(self)->"float4": ...

        @property
        def xzyw(self)->"float4": ...

        @xzyw.setter
        def xzyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzzx(self)->"float4": ...

        @property
        def xzzy(self)->"float4": ...

        @property
        def xzzz(self)->"float4": ...

        @property
        def xzzw(self)->"float4": ...

        @property
        def xzwx(self)->"float4": ...

        @property
        def xzwy(self)->"float4": ...

        @xzwy.setter
        def xzwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzwz(self)->"float4": ...

        @property
        def xzww(self)->"float4": ...

        @property
        def xwxx(self)->"float4": ...

        @property
        def xwxy(self)->"float4": ...

        @property
        def xwxz(self)->"float4": ...

        @property
        def xwxw(self)->"float4": ...

        @property
        def xwyx(self)->"float4": ...

        @property
        def xwyy(self)->"float4": ...

        @property
        def xwyz(self)->"float4": ...

        @xwyz.setter
        def xwyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwyw(self)->"float4": ...

        @property
        def xwzx(self)->"float4": ...

        @property
        def xwzy(self)->"float4": ...

        @xwzy.setter
        def xwzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwzz(self)->"float4": ...

        @property
        def xwzw(self)->"float4": ...

        @property
        def xwwx(self)->"float4": ...

        @property
        def xwwy(self)->"float4": ...

        @property
        def xwwz(self)->"float4": ...

        @property
        def xwww(self)->"float4": ...

        @property
        def yxxx(self)->"float4": ...

        @property
        def yxxy(self)->"float4": ...

        @property
        def yxxz(self)->"float4": ...

        @property
        def yxxw(self)->"float4": ...

        @property
        def yxyx(self)->"float4": ...

        @property
        def yxyy(self)->"float4": ...

        @property
        def yxyz(self)->"float4": ...

        @property
        def yxyw(self)->"float4": ...

        @property
        def yxzx(self)->"float4": ...

        @property
        def yxzy(self)->"float4": ...

        @property
        def yxzz(self)->"float4": ...

        @property
        def yxzw(self)->"float4": ...

        @yxzw.setter
        def yxzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxwx(self)->"float4": ...

        @property
        def yxwy(self)->"float4": ...

        @property
        def yxwz(self)->"float4": ...

        @yxwz.setter
        def yxwz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxww(self)->"float4": ...

        @property
        def yyxx(self)->"float4": ...

        @property
        def yyxy(self)->"float4": ...

        @property
        def yyxz(self)->"float4": ...

        @property
        def yyxw(self)->"float4": ...

        @property
        def yyyx(self)->"float4": ...

        @property
        def yyyy(self)->"float4": ...

        @property
        def yyyz(self)->"float4": ...

        @property
        def yyyw(self)->"float4": ...

        @property
        def yyzx(self)->"float4": ...

        @property
        def yyzy(self)->"float4": ...

        @property
        def yyzz(self)->"float4": ...

        @property
        def yyzw(self)->"float4": ...

        @property
        def yywx(self)->"float4": ...

        @property
        def yywy(self)->"float4": ...

        @property
        def yywz(self)->"float4": ...

        @property
        def yyww(self)->"float4": ...

        @property
        def yzxx(self)->"float4": ...

        @property
        def yzxy(self)->"float4": ...

        @property
        def yzxz(self)->"float4": ...

        @property
        def yzxw(self)->"float4": ...

        @yzxw.setter
        def yzxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzyx(self)->"float4": ...

        @property
        def yzyy(self)->"float4": ...

        @property
        def yzyz(self)->"float4": ...

        @property
        def yzyw(self)->"float4": ...

        @property
        def yzzx(self)->"float4": ...

        @property
        def yzzy(self)->"float4": ...

        @property
        def yzzz(self)->"float4": ...

        @property
        def yzzw(self)->"float4": ...

        @property
        def yzwx(self)->"float4": ...

        @yzwx.setter
        def yzwx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzwy(self)->"float4": ...

        @property
        def yzwz(self)->"float4": ...

        @property
        def yzww(self)->"float4": ...

        @property
        def ywxx(self)->"float4": ...

        @property
        def ywxy(self)->"float4": ...

        @property
        def ywxz(self)->"float4": ...

        @ywxz.setter
        def ywxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywxw(self)->"float4": ...

        @property
        def ywyx(self)->"float4": ...

        @property
        def ywyy(self)->"float4": ...

        @property
        def ywyz(self)->"float4": ...

        @property
        def ywyw(self)->"float4": ...

        @property
        def ywzx(self)->"float4": ...

        @ywzx.setter
        def ywzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywzy(self)->"float4": ...

        @property
        def ywzz(self)->"float4": ...

        @property
        def ywzw(self)->"float4": ...

        @property
        def ywwx(self)->"float4": ...

        @property
        def ywwy(self)->"float4": ...

        @property
        def ywwz(self)->"float4": ...

        @property
        def ywww(self)->"float4": ...

        @property
        def zxxx(self)->"float4": ...

        @property
        def zxxy(self)->"float4": ...

        @property
        def zxxz(self)->"float4": ...

        @property
        def zxxw(self)->"float4": ...

        @property
        def zxyx(self)->"float4": ...

        @property
        def zxyy(self)->"float4": ...

        @property
        def zxyz(self)->"float4": ...

        @property
        def zxyw(self)->"float4": ...

        @zxyw.setter
        def zxyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxzx(self)->"float4": ...

        @property
        def zxzy(self)->"float4": ...

        @property
        def zxzz(self)->"float4": ...

        @property
        def zxzw(self)->"float4": ...

        @property
        def zxwx(self)->"float4": ...

        @property
        def zxwy(self)->"float4": ...

        @zxwy.setter
        def zxwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxwz(self)->"float4": ...

        @property
        def zxww(self)->"float4": ...

        @property
        def zyxx(self)->"float4": ...

        @property
        def zyxy(self)->"float4": ...

        @property
        def zyxz(self)->"float4": ...

        @property
        def zyxw(self)->"float4": ...

        @zyxw.setter
        def zyxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zyyx(self)->"float4": ...

        @property
        def zyyy(self)->"float4": ...

        @property
        def zyyz(self)->"float4": ...

        @property
        def zyyw(self)->"float4": ...

        @property
        def zyzx(self)->"float4": ...

        @property
        def zyzy(self)->"float4": ...

        @property
        def zyzz(self)->"float4": ...

        @property
        def zyzw(self)->"float4": ...

        @property
        def zywx(self)->"float4": ...

        @zywx.setter
        def zywx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zywy(self)->"float4": ...

        @property
        def zywz(self)->"float4": ...

        @property
        def zyww(self)->"float4": ...

        @property
        def zzxx(self)->"float4": ...

        @property
        def zzxy(self)->"float4": ...

        @property
        def zzxz(self)->"float4": ...

        @property
        def zzxw(self)->"float4": ...

        @property
        def zzyx(self)->"float4": ...

        @property
        def zzyy(self)->"float4": ...

        @property
        def zzyz(self)->"float4": ...

        @property
        def zzyw(self)->"float4": ...

        @property
        def zzzx(self)->"float4": ...

        @property
        def zzzy(self)->"float4": ...

        @property
        def zzzz(self)->"float4": ...

        @property
        def zzzw(self)->"float4": ...

        @property
        def zzwx(self)->"float4": ...

        @property
        def zzwy(self)->"float4": ...

        @property
        def zzwz(self)->"float4": ...

        @property
        def zzww(self)->"float4": ...

        @property
        def zwxx(self)->"float4": ...

        @property
        def zwxy(self)->"float4": ...

        @zwxy.setter
        def zwxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwxz(self)->"float4": ...

        @property
        def zwxw(self)->"float4": ...

        @property
        def zwyx(self)->"float4": ...

        @zwyx.setter
        def zwyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwyy(self)->"float4": ...

        @property
        def zwyz(self)->"float4": ...

        @property
        def zwyw(self)->"float4": ...

        @property
        def zwzx(self)->"float4": ...

        @property
        def zwzy(self)->"float4": ...

        @property
        def zwzz(self)->"float4": ...

        @property
        def zwzw(self)->"float4": ...

        @property
        def zwwx(self)->"float4": ...

        @property
        def zwwy(self)->"float4": ...

        @property
        def zwwz(self)->"float4": ...

        @property
        def zwww(self)->"float4": ...

        @property
        def wxxx(self)->"float4": ...

        @property
        def wxxy(self)->"float4": ...

        @property
        def wxxz(self)->"float4": ...

        @property
        def wxxw(self)->"float4": ...

        @property
        def wxyx(self)->"float4": ...

        @property
        def wxyy(self)->"float4": ...

        @property
        def wxyz(self)->"float4": ...

        @wxyz.setter
        def wxyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxyw(self)->"float4": ...

        @property
        def wxzx(self)->"float4": ...

        @property
        def wxzy(self)->"float4": ...

        @wxzy.setter
        def wxzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxzz(self)->"float4": ...

        @property
        def wxzw(self)->"float4": ...

        @property
        def wxwx(self)->"float4": ...

        @property
        def wxwy(self)->"float4": ...

        @property
        def wxwz(self)->"float4": ...

        @property
        def wxww(self)->"float4": ...

        @property
        def wyxx(self)->"float4": ...

        @property
        def wyxy(self)->"float4": ...

        @property
        def wyxz(self)->"float4": ...

        @wyxz.setter
        def wyxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyxw(self)->"float4": ...

        @property
        def wyyx(self)->"float4": ...

        @property
        def wyyy(self)->"float4": ...

        @property
        def wyyz(self)->"float4": ...

        @property
        def wyyw(self)->"float4": ...

        @property
        def wyzx(self)->"float4": ...

        @wyzx.setter
        def wyzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyzy(self)->"float4": ...

        @property
        def wyzz(self)->"float4": ...

        @property
        def wyzw(self)->"float4": ...

        @property
        def wywx(self)->"float4": ...

        @property
        def wywy(self)->"float4": ...

        @property
        def wywz(self)->"float4": ...

        @property
        def wyww(self)->"float4": ...

        @property
        def wzxx(self)->"float4": ...

        @property
        def wzxy(self)->"float4": ...

        @wzxy.setter
        def wzxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzxz(self)->"float4": ...

        @property
        def wzxw(self)->"float4": ...

        @property
        def wzyx(self)->"float4": ...

        @wzyx.setter
        def wzyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzyy(self)->"float4": ...

        @property
        def wzyz(self)->"float4": ...

        @property
        def wzyw(self)->"float4": ...

        @property
        def wzzx(self)->"float4": ...

        @property
        def wzzy(self)->"float4": ...

        @property
        def wzzz(self)->"float4": ...

        @property
        def wzzw(self)->"float4": ...

        @property
        def wzwx(self)->"float4": ...

        @property
        def wzwy(self)->"float4": ...

        @property
        def wzwz(self)->"float4": ...

        @property
        def wzww(self)->"float4": ...

        @property
        def wwxx(self)->"float4": ...

        @property
        def wwxy(self)->"float4": ...

        @property
        def wwxz(self)->"float4": ...

        @property
        def wwxw(self)->"float4": ...

        @property
        def wwyx(self)->"float4": ...

        @property
        def wwyy(self)->"float4": ...

        @property
        def wwyz(self)->"float4": ...

        @property
        def wwyw(self)->"float4": ...

        @property
        def wwzx(self)->"float4": ...

        @property
        def wwzy(self)->"float4": ...

        @property
        def wwzz(self)->"float4": ...

        @property
        def wwzw(self)->"float4": ...

        @property
        def wwwx(self)->"float4": ...

        @property
        def wwwy(self)->"float4": ...

        @property
        def wwwz(self)->"float4": ...

        @property
        def wwww(self)->"float4": ...

        @property
        def r(self)->float: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->float: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def b(self)->float: ...

        @b.setter
        def b(self, value:Union[bool, int, float])->None: ...

        @property
        def a(self)->float: ...

        @a.setter
        def a(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->float2: ...

        @property
        def rg(self)->float2: ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def rb(self)->float2: ...

        @rb.setter
        def rb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ra(self)->float2: ...

        @ra.setter
        def ra(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->float2: ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->float2: ...

        @property
        def gb(self)->float2: ...

        @gb.setter
        def gb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ga(self)->float2: ...

        @ga.setter
        def ga(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def br(self)->float2: ...

        @br.setter
        def br(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bg(self)->float2: ...

        @bg.setter
        def bg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bb(self)->float2: ...

        @property
        def ba(self)->float2: ...

        @ba.setter
        def ba(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ar(self)->float2: ...

        @ar.setter
        def ar(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ag(self)->float2: ...

        @ag.setter
        def ag(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ab(self)->float2: ...

        @ab.setter
        def ab(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def aa(self)->float2: ...

        @property
        def rrr(self)->float3: ...

        @property
        def rrg(self)->float3: ...

        @property
        def rrb(self)->float3: ...

        @property
        def rra(self)->float3: ...

        @property
        def rgr(self)->float3: ...

        @property
        def rgg(self)->float3: ...

        @property
        def rgb(self)->float3: ...

        @rgb.setter
        def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rga(self)->float3: ...

        @rga.setter
        def rga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbr(self)->float3: ...

        @property
        def rbg(self)->float3: ...

        @rbg.setter
        def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbb(self)->float3: ...

        @property
        def rba(self)->float3: ...

        @rba.setter
        def rba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rar(self)->float3: ...

        @property
        def rag(self)->float3: ...

        @rag.setter
        def rag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rab(self)->float3: ...

        @rab.setter
        def rab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def raa(self)->float3: ...

        @property
        def grr(self)->float3: ...

        @property
        def grg(self)->float3: ...

        @property
        def grb(self)->float3: ...

        @grb.setter
        def grb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gra(self)->float3: ...

        @gra.setter
        def gra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ggr(self)->float3: ...

        @property
        def ggg(self)->float3: ...

        @property
        def ggb(self)->float3: ...

        @property
        def gga(self)->float3: ...

        @property
        def gbr(self)->float3: ...

        @gbr.setter
        def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gbg(self)->float3: ...

        @property
        def gbb(self)->float3: ...

        @property
        def gba(self)->float3: ...

        @gba.setter
        def gba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gar(self)->float3: ...

        @gar.setter
        def gar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gag(self)->float3: ...

        @property
        def gab(self)->float3: ...

        @gab.setter
        def gab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gaa(self)->float3: ...

        @property
        def brr(self)->float3: ...

        @property
        def brg(self)->float3: ...

        @brg.setter
        def brg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def brb(self)->float3: ...

        @property
        def bra(self)->float3: ...

        @bra.setter
        def bra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgr(self)->float3: ...

        @bgr.setter
        def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgg(self)->float3: ...

        @property
        def bgb(self)->float3: ...

        @property
        def bga(self)->float3: ...

        @bga.setter
        def bga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bbr(self)->float3: ...

        @property
        def bbg(self)->float3: ...

        @property
        def bbb(self)->float3: ...

        @property
        def bba(self)->float3: ...

        @property
        def bar(self)->float3: ...

        @bar.setter
        def bar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bag(self)->float3: ...

        @bag.setter
        def bag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bab(self)->float3: ...

        @property
        def baa(self)->float3: ...

        @property
        def arr(self)->float3: ...

        @property
        def arg(self)->float3: ...

        @arg.setter
        def arg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def arb(self)->float3: ...

        @arb.setter
        def arb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ara(self)->float3: ...

        @property
        def agr(self)->float3: ...

        @agr.setter
        def agr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def agg(self)->float3: ...

        @property
        def agb(self)->float3: ...

        @agb.setter
        def agb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def aga(self)->float3: ...

        @property
        def abr(self)->float3: ...

        @abr.setter
        def abr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abg(self)->float3: ...

        @abg.setter
        def abg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abb(self)->float3: ...

        @property
        def aba(self)->float3: ...

        @property
        def aar(self)->float3: ...

        @property
        def aag(self)->float3: ...

        @property
        def aab(self)->float3: ...

        @property
        def aaa(self)->float3: ...

        @property
        def rrrr(self)->"float4": ...

        @property
        def rrrg(self)->"float4": ...

        @property
        def rrrb(self)->"float4": ...

        @property
        def rrra(self)->"float4": ...

        @property
        def rrgr(self)->"float4": ...

        @property
        def rrgg(self)->"float4": ...

        @property
        def rrgb(self)->"float4": ...

        @property
        def rrga(self)->"float4": ...

        @property
        def rrbr(self)->"float4": ...

        @property
        def rrbg(self)->"float4": ...

        @property
        def rrbb(self)->"float4": ...

        @property
        def rrba(self)->"float4": ...

        @property
        def rrar(self)->"float4": ...

        @property
        def rrag(self)->"float4": ...

        @property
        def rrab(self)->"float4": ...

        @property
        def rraa(self)->"float4": ...

        @property
        def rgrr(self)->"float4": ...

        @property
        def rgrg(self)->"float4": ...

        @property
        def rgrb(self)->"float4": ...

        @property
        def rgra(self)->"float4": ...

        @property
        def rggr(self)->"float4": ...

        @property
        def rggg(self)->"float4": ...

        @property
        def rggb(self)->"float4": ...

        @property
        def rgga(self)->"float4": ...

        @property
        def rgbr(self)->"float4": ...

        @property
        def rgbg(self)->"float4": ...

        @property
        def rgbb(self)->"float4": ...

        @property
        def rgba(self)->"float4": ...

        @rgba.setter
        def rgba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgar(self)->"float4": ...

        @property
        def rgag(self)->"float4": ...

        @property
        def rgab(self)->"float4": ...

        @rgab.setter
        def rgab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgaa(self)->"float4": ...

        @property
        def rbrr(self)->"float4": ...

        @property
        def rbrg(self)->"float4": ...

        @property
        def rbrb(self)->"float4": ...

        @property
        def rbra(self)->"float4": ...

        @property
        def rbgr(self)->"float4": ...

        @property
        def rbgg(self)->"float4": ...

        @property
        def rbgb(self)->"float4": ...

        @property
        def rbga(self)->"float4": ...

        @rbga.setter
        def rbga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbbr(self)->"float4": ...

        @property
        def rbbg(self)->"float4": ...

        @property
        def rbbb(self)->"float4": ...

        @property
        def rbba(self)->"float4": ...

        @property
        def rbar(self)->"float4": ...

        @property
        def rbag(self)->"float4": ...

        @rbag.setter
        def rbag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbab(self)->"float4": ...

        @property
        def rbaa(self)->"float4": ...

        @property
        def rarr(self)->"float4": ...

        @property
        def rarg(self)->"float4": ...

        @property
        def rarb(self)->"float4": ...

        @property
        def rara(self)->"float4": ...

        @property
        def ragr(self)->"float4": ...

        @property
        def ragg(self)->"float4": ...

        @property
        def ragb(self)->"float4": ...

        @ragb.setter
        def ragb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def raga(self)->"float4": ...

        @property
        def rabr(self)->"float4": ...

        @property
        def rabg(self)->"float4": ...

        @rabg.setter
        def rabg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rabb(self)->"float4": ...

        @property
        def raba(self)->"float4": ...

        @property
        def raar(self)->"float4": ...

        @property
        def raag(self)->"float4": ...

        @property
        def raab(self)->"float4": ...

        @property
        def raaa(self)->"float4": ...

        @property
        def grrr(self)->"float4": ...

        @property
        def grrg(self)->"float4": ...

        @property
        def grrb(self)->"float4": ...

        @property
        def grra(self)->"float4": ...

        @property
        def grgr(self)->"float4": ...

        @property
        def grgg(self)->"float4": ...

        @property
        def grgb(self)->"float4": ...

        @property
        def grga(self)->"float4": ...

        @property
        def grbr(self)->"float4": ...

        @property
        def grbg(self)->"float4": ...

        @property
        def grbb(self)->"float4": ...

        @property
        def grba(self)->"float4": ...

        @grba.setter
        def grba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def grar(self)->"float4": ...

        @property
        def grag(self)->"float4": ...

        @property
        def grab(self)->"float4": ...

        @grab.setter
        def grab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def graa(self)->"float4": ...

        @property
        def ggrr(self)->"float4": ...

        @property
        def ggrg(self)->"float4": ...

        @property
        def ggrb(self)->"float4": ...

        @property
        def ggra(self)->"float4": ...

        @property
        def gggr(self)->"float4": ...

        @property
        def gggg(self)->"float4": ...

        @property
        def gggb(self)->"float4": ...

        @property
        def ggga(self)->"float4": ...

        @property
        def ggbr(self)->"float4": ...

        @property
        def ggbg(self)->"float4": ...

        @property
        def ggbb(self)->"float4": ...

        @property
        def ggba(self)->"float4": ...

        @property
        def ggar(self)->"float4": ...

        @property
        def ggag(self)->"float4": ...

        @property
        def ggab(self)->"float4": ...

        @property
        def ggaa(self)->"float4": ...

        @property
        def gbrr(self)->"float4": ...

        @property
        def gbrg(self)->"float4": ...

        @property
        def gbrb(self)->"float4": ...

        @property
        def gbra(self)->"float4": ...

        @gbra.setter
        def gbra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbgr(self)->"float4": ...

        @property
        def gbgg(self)->"float4": ...

        @property
        def gbgb(self)->"float4": ...

        @property
        def gbga(self)->"float4": ...

        @property
        def gbbr(self)->"float4": ...

        @property
        def gbbg(self)->"float4": ...

        @property
        def gbbb(self)->"float4": ...

        @property
        def gbba(self)->"float4": ...

        @property
        def gbar(self)->"float4": ...

        @gbar.setter
        def gbar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbag(self)->"float4": ...

        @property
        def gbab(self)->"float4": ...

        @property
        def gbaa(self)->"float4": ...

        @property
        def garr(self)->"float4": ...

        @property
        def garg(self)->"float4": ...

        @property
        def garb(self)->"float4": ...

        @garb.setter
        def garb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gara(self)->"float4": ...

        @property
        def gagr(self)->"float4": ...

        @property
        def gagg(self)->"float4": ...

        @property
        def gagb(self)->"float4": ...

        @property
        def gaga(self)->"float4": ...

        @property
        def gabr(self)->"float4": ...

        @gabr.setter
        def gabr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gabg(self)->"float4": ...

        @property
        def gabb(self)->"float4": ...

        @property
        def gaba(self)->"float4": ...

        @property
        def gaar(self)->"float4": ...

        @property
        def gaag(self)->"float4": ...

        @property
        def gaab(self)->"float4": ...

        @property
        def gaaa(self)->"float4": ...

        @property
        def brrr(self)->"float4": ...

        @property
        def brrg(self)->"float4": ...

        @property
        def brrb(self)->"float4": ...

        @property
        def brra(self)->"float4": ...

        @property
        def brgr(self)->"float4": ...

        @property
        def brgg(self)->"float4": ...

        @property
        def brgb(self)->"float4": ...

        @property
        def brga(self)->"float4": ...

        @brga.setter
        def brga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brbr(self)->"float4": ...

        @property
        def brbg(self)->"float4": ...

        @property
        def brbb(self)->"float4": ...

        @property
        def brba(self)->"float4": ...

        @property
        def brar(self)->"float4": ...

        @property
        def brag(self)->"float4": ...

        @brag.setter
        def brag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brab(self)->"float4": ...

        @property
        def braa(self)->"float4": ...

        @property
        def bgrr(self)->"float4": ...

        @property
        def bgrg(self)->"float4": ...

        @property
        def bgrb(self)->"float4": ...

        @property
        def bgra(self)->"float4": ...

        @bgra.setter
        def bgra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bggr(self)->"float4": ...

        @property
        def bggg(self)->"float4": ...

        @property
        def bggb(self)->"float4": ...

        @property
        def bgga(self)->"float4": ...

        @property
        def bgbr(self)->"float4": ...

        @property
        def bgbg(self)->"float4": ...

        @property
        def bgbb(self)->"float4": ...

        @property
        def bgba(self)->"float4": ...

        @property
        def bgar(self)->"float4": ...

        @bgar.setter
        def bgar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bgag(self)->"float4": ...

        @property
        def bgab(self)->"float4": ...

        @property
        def bgaa(self)->"float4": ...

        @property
        def bbrr(self)->"float4": ...

        @property
        def bbrg(self)->"float4": ...

        @property
        def bbrb(self)->"float4": ...

        @property
        def bbra(self)->"float4": ...

        @property
        def bbgr(self)->"float4": ...

        @property
        def bbgg(self)->"float4": ...

        @property
        def bbgb(self)->"float4": ...

        @property
        def bbga(self)->"float4": ...

        @property
        def bbbr(self)->"float4": ...

        @property
        def bbbg(self)->"float4": ...

        @property
        def bbbb(self)->"float4": ...

        @property
        def bbba(self)->"float4": ...

        @property
        def bbar(self)->"float4": ...

        @property
        def bbag(self)->"float4": ...

        @property
        def bbab(self)->"float4": ...

        @property
        def bbaa(self)->"float4": ...

        @property
        def barr(self)->"float4": ...

        @property
        def barg(self)->"float4": ...

        @barg.setter
        def barg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def barb(self)->"float4": ...

        @property
        def bara(self)->"float4": ...

        @property
        def bagr(self)->"float4": ...

        @bagr.setter
        def bagr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bagg(self)->"float4": ...

        @property
        def bagb(self)->"float4": ...

        @property
        def baga(self)->"float4": ...

        @property
        def babr(self)->"float4": ...

        @property
        def babg(self)->"float4": ...

        @property
        def babb(self)->"float4": ...

        @property
        def baba(self)->"float4": ...

        @property
        def baar(self)->"float4": ...

        @property
        def baag(self)->"float4": ...

        @property
        def baab(self)->"float4": ...

        @property
        def baaa(self)->"float4": ...

        @property
        def arrr(self)->"float4": ...

        @property
        def arrg(self)->"float4": ...

        @property
        def arrb(self)->"float4": ...

        @property
        def arra(self)->"float4": ...

        @property
        def argr(self)->"float4": ...

        @property
        def argg(self)->"float4": ...

        @property
        def argb(self)->"float4": ...

        @argb.setter
        def argb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arga(self)->"float4": ...

        @property
        def arbr(self)->"float4": ...

        @property
        def arbg(self)->"float4": ...

        @arbg.setter
        def arbg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arbb(self)->"float4": ...

        @property
        def arba(self)->"float4": ...

        @property
        def arar(self)->"float4": ...

        @property
        def arag(self)->"float4": ...

        @property
        def arab(self)->"float4": ...

        @property
        def araa(self)->"float4": ...

        @property
        def agrr(self)->"float4": ...

        @property
        def agrg(self)->"float4": ...

        @property
        def agrb(self)->"float4": ...

        @agrb.setter
        def agrb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agra(self)->"float4": ...

        @property
        def aggr(self)->"float4": ...

        @property
        def aggg(self)->"float4": ...

        @property
        def aggb(self)->"float4": ...

        @property
        def agga(self)->"float4": ...

        @property
        def agbr(self)->"float4": ...

        @agbr.setter
        def agbr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agbg(self)->"float4": ...

        @property
        def agbb(self)->"float4": ...

        @property
        def agba(self)->"float4": ...

        @property
        def agar(self)->"float4": ...

        @property
        def agag(self)->"float4": ...

        @property
        def agab(self)->"float4": ...

        @property
        def agaa(self)->"float4": ...

        @property
        def abrr(self)->"float4": ...

        @property
        def abrg(self)->"float4": ...

        @abrg.setter
        def abrg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abrb(self)->"float4": ...

        @property
        def abra(self)->"float4": ...

        @property
        def abgr(self)->"float4": ...

        @abgr.setter
        def abgr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abgg(self)->"float4": ...

        @property
        def abgb(self)->"float4": ...

        @property
        def abga(self)->"float4": ...

        @property
        def abbr(self)->"float4": ...

        @property
        def abbg(self)->"float4": ...

        @property
        def abbb(self)->"float4": ...

        @property
        def abba(self)->"float4": ...

        @property
        def abar(self)->"float4": ...

        @property
        def abag(self)->"float4": ...

        @property
        def abab(self)->"float4": ...

        @property
        def abaa(self)->"float4": ...

        @property
        def aarr(self)->"float4": ...

        @property
        def aarg(self)->"float4": ...

        @property
        def aarb(self)->"float4": ...

        @property
        def aara(self)->"float4": ...

        @property
        def aagr(self)->"float4": ...

        @property
        def aagg(self)->"float4": ...

        @property
        def aagb(self)->"float4": ...

        @property
        def aaga(self)->"float4": ...

        @property
        def aabr(self)->"float4": ...

        @property
        def aabg(self)->"float4": ...

        @property
        def aabb(self)->"float4": ...

        @property
        def aaba(self)->"float4": ...

        @property
        def aaar(self)->"float4": ...

        @property
        def aaag(self)->"float4": ...

        @property
        def aaab(self)->"float4": ...

        @property
        def aaaa(self)->"float4": ...

        @property
        def s(self)->float: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->float: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def p(self)->float: ...

        @p.setter
        def p(self, value:Union[bool, int, float])->None: ...

        @property
        def q(self)->float: ...

        @q.setter
        def q(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->float2: ...

        @property
        def st(self)->float2: ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sp(self)->float2: ...

        @sp.setter
        def sp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sq(self)->float2: ...

        @sq.setter
        def sq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->float2: ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->float2: ...

        @property
        def tp(self)->float2: ...

        @tp.setter
        def tp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tq(self)->float2: ...

        @tq.setter
        def tq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ps(self)->float2: ...

        @ps.setter
        def ps(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pt(self)->float2: ...

        @pt.setter
        def pt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pp(self)->float2: ...

        @property
        def pq(self)->float2: ...

        @pq.setter
        def pq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qs(self)->float2: ...

        @qs.setter
        def qs(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qt(self)->float2: ...

        @qt.setter
        def qt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qp(self)->float2: ...

        @qp.setter
        def qp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qq(self)->float2: ...

        @property
        def sss(self)->float3: ...

        @property
        def sst(self)->float3: ...

        @property
        def ssp(self)->float3: ...

        @property
        def ssq(self)->float3: ...

        @property
        def sts(self)->float3: ...

        @property
        def stt(self)->float3: ...

        @property
        def stp(self)->float3: ...

        @stp.setter
        def stp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def stq(self)->float3: ...

        @stq.setter
        def stq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sps(self)->float3: ...

        @property
        def spt(self)->float3: ...

        @spt.setter
        def spt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def spp(self)->float3: ...

        @property
        def spq(self)->float3: ...

        @spq.setter
        def spq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqs(self)->float3: ...

        @property
        def sqt(self)->float3: ...

        @sqt.setter
        def sqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqp(self)->float3: ...

        @sqp.setter
        def sqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqq(self)->float3: ...

        @property
        def tss(self)->float3: ...

        @property
        def tst(self)->float3: ...

        @property
        def tsp(self)->float3: ...

        @tsp.setter
        def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tsq(self)->float3: ...

        @tsq.setter
        def tsq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tts(self)->float3: ...

        @property
        def ttt(self)->float3: ...

        @property
        def ttp(self)->float3: ...

        @property
        def ttq(self)->float3: ...

        @property
        def tps(self)->float3: ...

        @tps.setter
        def tps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tpt(self)->float3: ...

        @property
        def tpp(self)->float3: ...

        @property
        def tpq(self)->float3: ...

        @tpq.setter
        def tpq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqs(self)->float3: ...

        @tqs.setter
        def tqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqt(self)->float3: ...

        @property
        def tqp(self)->float3: ...

        @tqp.setter
        def tqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqq(self)->float3: ...

        @property
        def pss(self)->float3: ...

        @property
        def pst(self)->float3: ...

        @pst.setter
        def pst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def psp(self)->float3: ...

        @property
        def psq(self)->float3: ...

        @psq.setter
        def psq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pts(self)->float3: ...

        @pts.setter
        def pts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ptt(self)->float3: ...

        @property
        def ptp(self)->float3: ...

        @property
        def ptq(self)->float3: ...

        @ptq.setter
        def ptq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pps(self)->float3: ...

        @property
        def ppt(self)->float3: ...

        @property
        def ppp(self)->float3: ...

        @property
        def ppq(self)->float3: ...

        @property
        def pqs(self)->float3: ...

        @pqs.setter
        def pqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqt(self)->float3: ...

        @pqt.setter
        def pqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqp(self)->float3: ...

        @property
        def pqq(self)->float3: ...

        @property
        def qss(self)->float3: ...

        @property
        def qst(self)->float3: ...

        @qst.setter
        def qst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsp(self)->float3: ...

        @qsp.setter
        def qsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsq(self)->float3: ...

        @property
        def qts(self)->float3: ...

        @qts.setter
        def qts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtt(self)->float3: ...

        @property
        def qtp(self)->float3: ...

        @qtp.setter
        def qtp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtq(self)->float3: ...

        @property
        def qps(self)->float3: ...

        @qps.setter
        def qps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpt(self)->float3: ...

        @qpt.setter
        def qpt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpp(self)->float3: ...

        @property
        def qpq(self)->float3: ...

        @property
        def qqs(self)->float3: ...

        @property
        def qqt(self)->float3: ...

        @property
        def qqp(self)->float3: ...

        @property
        def qqq(self)->float3: ...

        @property
        def ssss(self)->"float4": ...

        @property
        def ssst(self)->"float4": ...

        @property
        def sssp(self)->"float4": ...

        @property
        def sssq(self)->"float4": ...

        @property
        def ssts(self)->"float4": ...

        @property
        def sstt(self)->"float4": ...

        @property
        def sstp(self)->"float4": ...

        @property
        def sstq(self)->"float4": ...

        @property
        def ssps(self)->"float4": ...

        @property
        def sspt(self)->"float4": ...

        @property
        def sspp(self)->"float4": ...

        @property
        def sspq(self)->"float4": ...

        @property
        def ssqs(self)->"float4": ...

        @property
        def ssqt(self)->"float4": ...

        @property
        def ssqp(self)->"float4": ...

        @property
        def ssqq(self)->"float4": ...

        @property
        def stss(self)->"float4": ...

        @property
        def stst(self)->"float4": ...

        @property
        def stsp(self)->"float4": ...

        @property
        def stsq(self)->"float4": ...

        @property
        def stts(self)->"float4": ...

        @property
        def sttt(self)->"float4": ...

        @property
        def sttp(self)->"float4": ...

        @property
        def sttq(self)->"float4": ...

        @property
        def stps(self)->"float4": ...

        @property
        def stpt(self)->"float4": ...

        @property
        def stpp(self)->"float4": ...

        @property
        def stpq(self)->"float4": ...

        @stpq.setter
        def stpq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqs(self)->"float4": ...

        @property
        def stqt(self)->"float4": ...

        @property
        def stqp(self)->"float4": ...

        @stqp.setter
        def stqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqq(self)->"float4": ...

        @property
        def spss(self)->"float4": ...

        @property
        def spst(self)->"float4": ...

        @property
        def spsp(self)->"float4": ...

        @property
        def spsq(self)->"float4": ...

        @property
        def spts(self)->"float4": ...

        @property
        def sptt(self)->"float4": ...

        @property
        def sptp(self)->"float4": ...

        @property
        def sptq(self)->"float4": ...

        @sptq.setter
        def sptq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spps(self)->"float4": ...

        @property
        def sppt(self)->"float4": ...

        @property
        def sppp(self)->"float4": ...

        @property
        def sppq(self)->"float4": ...

        @property
        def spqs(self)->"float4": ...

        @property
        def spqt(self)->"float4": ...

        @spqt.setter
        def spqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spqp(self)->"float4": ...

        @property
        def spqq(self)->"float4": ...

        @property
        def sqss(self)->"float4": ...

        @property
        def sqst(self)->"float4": ...

        @property
        def sqsp(self)->"float4": ...

        @property
        def sqsq(self)->"float4": ...

        @property
        def sqts(self)->"float4": ...

        @property
        def sqtt(self)->"float4": ...

        @property
        def sqtp(self)->"float4": ...

        @sqtp.setter
        def sqtp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqtq(self)->"float4": ...

        @property
        def sqps(self)->"float4": ...

        @property
        def sqpt(self)->"float4": ...

        @sqpt.setter
        def sqpt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqpp(self)->"float4": ...

        @property
        def sqpq(self)->"float4": ...

        @property
        def sqqs(self)->"float4": ...

        @property
        def sqqt(self)->"float4": ...

        @property
        def sqqp(self)->"float4": ...

        @property
        def sqqq(self)->"float4": ...

        @property
        def tsss(self)->"float4": ...

        @property
        def tsst(self)->"float4": ...

        @property
        def tssp(self)->"float4": ...

        @property
        def tssq(self)->"float4": ...

        @property
        def tsts(self)->"float4": ...

        @property
        def tstt(self)->"float4": ...

        @property
        def tstp(self)->"float4": ...

        @property
        def tstq(self)->"float4": ...

        @property
        def tsps(self)->"float4": ...

        @property
        def tspt(self)->"float4": ...

        @property
        def tspp(self)->"float4": ...

        @property
        def tspq(self)->"float4": ...

        @tspq.setter
        def tspq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqs(self)->"float4": ...

        @property
        def tsqt(self)->"float4": ...

        @property
        def tsqp(self)->"float4": ...

        @tsqp.setter
        def tsqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqq(self)->"float4": ...

        @property
        def ttss(self)->"float4": ...

        @property
        def ttst(self)->"float4": ...

        @property
        def ttsp(self)->"float4": ...

        @property
        def ttsq(self)->"float4": ...

        @property
        def ttts(self)->"float4": ...

        @property
        def tttt(self)->"float4": ...

        @property
        def tttp(self)->"float4": ...

        @property
        def tttq(self)->"float4": ...

        @property
        def ttps(self)->"float4": ...

        @property
        def ttpt(self)->"float4": ...

        @property
        def ttpp(self)->"float4": ...

        @property
        def ttpq(self)->"float4": ...

        @property
        def ttqs(self)->"float4": ...

        @property
        def ttqt(self)->"float4": ...

        @property
        def ttqp(self)->"float4": ...

        @property
        def ttqq(self)->"float4": ...

        @property
        def tpss(self)->"float4": ...

        @property
        def tpst(self)->"float4": ...

        @property
        def tpsp(self)->"float4": ...

        @property
        def tpsq(self)->"float4": ...

        @tpsq.setter
        def tpsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpts(self)->"float4": ...

        @property
        def tptt(self)->"float4": ...

        @property
        def tptp(self)->"float4": ...

        @property
        def tptq(self)->"float4": ...

        @property
        def tpps(self)->"float4": ...

        @property
        def tppt(self)->"float4": ...

        @property
        def tppp(self)->"float4": ...

        @property
        def tppq(self)->"float4": ...

        @property
        def tpqs(self)->"float4": ...

        @tpqs.setter
        def tpqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpqt(self)->"float4": ...

        @property
        def tpqp(self)->"float4": ...

        @property
        def tpqq(self)->"float4": ...

        @property
        def tqss(self)->"float4": ...

        @property
        def tqst(self)->"float4": ...

        @property
        def tqsp(self)->"float4": ...

        @tqsp.setter
        def tqsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqsq(self)->"float4": ...

        @property
        def tqts(self)->"float4": ...

        @property
        def tqtt(self)->"float4": ...

        @property
        def tqtp(self)->"float4": ...

        @property
        def tqtq(self)->"float4": ...

        @property
        def tqps(self)->"float4": ...

        @tqps.setter
        def tqps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqpt(self)->"float4": ...

        @property
        def tqpp(self)->"float4": ...

        @property
        def tqpq(self)->"float4": ...

        @property
        def tqqs(self)->"float4": ...

        @property
        def tqqt(self)->"float4": ...

        @property
        def tqqp(self)->"float4": ...

        @property
        def tqqq(self)->"float4": ...

        @property
        def psss(self)->"float4": ...

        @property
        def psst(self)->"float4": ...

        @property
        def pssp(self)->"float4": ...

        @property
        def pssq(self)->"float4": ...

        @property
        def psts(self)->"float4": ...

        @property
        def pstt(self)->"float4": ...

        @property
        def pstp(self)->"float4": ...

        @property
        def pstq(self)->"float4": ...

        @pstq.setter
        def pstq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psps(self)->"float4": ...

        @property
        def pspt(self)->"float4": ...

        @property
        def pspp(self)->"float4": ...

        @property
        def pspq(self)->"float4": ...

        @property
        def psqs(self)->"float4": ...

        @property
        def psqt(self)->"float4": ...

        @psqt.setter
        def psqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psqp(self)->"float4": ...

        @property
        def psqq(self)->"float4": ...

        @property
        def ptss(self)->"float4": ...

        @property
        def ptst(self)->"float4": ...

        @property
        def ptsp(self)->"float4": ...

        @property
        def ptsq(self)->"float4": ...

        @ptsq.setter
        def ptsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptts(self)->"float4": ...

        @property
        def pttt(self)->"float4": ...

        @property
        def pttp(self)->"float4": ...

        @property
        def pttq(self)->"float4": ...

        @property
        def ptps(self)->"float4": ...

        @property
        def ptpt(self)->"float4": ...

        @property
        def ptpp(self)->"float4": ...

        @property
        def ptpq(self)->"float4": ...

        @property
        def ptqs(self)->"float4": ...

        @ptqs.setter
        def ptqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptqt(self)->"float4": ...

        @property
        def ptqp(self)->"float4": ...

        @property
        def ptqq(self)->"float4": ...

        @property
        def ppss(self)->"float4": ...

        @property
        def ppst(self)->"float4": ...

        @property
        def ppsp(self)->"float4": ...

        @property
        def ppsq(self)->"float4": ...

        @property
        def ppts(self)->"float4": ...

        @property
        def pptt(self)->"float4": ...

        @property
        def pptp(self)->"float4": ...

        @property
        def pptq(self)->"float4": ...

        @property
        def ppps(self)->"float4": ...

        @property
        def pppt(self)->"float4": ...

        @property
        def pppp(self)->"float4": ...

        @property
        def pppq(self)->"float4": ...

        @property
        def ppqs(self)->"float4": ...

        @property
        def ppqt(self)->"float4": ...

        @property
        def ppqp(self)->"float4": ...

        @property
        def ppqq(self)->"float4": ...

        @property
        def pqss(self)->"float4": ...

        @property
        def pqst(self)->"float4": ...

        @pqst.setter
        def pqst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqsp(self)->"float4": ...

        @property
        def pqsq(self)->"float4": ...

        @property
        def pqts(self)->"float4": ...

        @pqts.setter
        def pqts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqtt(self)->"float4": ...

        @property
        def pqtp(self)->"float4": ...

        @property
        def pqtq(self)->"float4": ...

        @property
        def pqps(self)->"float4": ...

        @property
        def pqpt(self)->"float4": ...

        @property
        def pqpp(self)->"float4": ...

        @property
        def pqpq(self)->"float4": ...

        @property
        def pqqs(self)->"float4": ...

        @property
        def pqqt(self)->"float4": ...

        @property
        def pqqp(self)->"float4": ...

        @property
        def pqqq(self)->"float4": ...

        @property
        def qsss(self)->"float4": ...

        @property
        def qsst(self)->"float4": ...

        @property
        def qssp(self)->"float4": ...

        @property
        def qssq(self)->"float4": ...

        @property
        def qsts(self)->"float4": ...

        @property
        def qstt(self)->"float4": ...

        @property
        def qstp(self)->"float4": ...

        @qstp.setter
        def qstp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qstq(self)->"float4": ...

        @property
        def qsps(self)->"float4": ...

        @property
        def qspt(self)->"float4": ...

        @qspt.setter
        def qspt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qspp(self)->"float4": ...

        @property
        def qspq(self)->"float4": ...

        @property
        def qsqs(self)->"float4": ...

        @property
        def qsqt(self)->"float4": ...

        @property
        def qsqp(self)->"float4": ...

        @property
        def qsqq(self)->"float4": ...

        @property
        def qtss(self)->"float4": ...

        @property
        def qtst(self)->"float4": ...

        @property
        def qtsp(self)->"float4": ...

        @qtsp.setter
        def qtsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtsq(self)->"float4": ...

        @property
        def qtts(self)->"float4": ...

        @property
        def qttt(self)->"float4": ...

        @property
        def qttp(self)->"float4": ...

        @property
        def qttq(self)->"float4": ...

        @property
        def qtps(self)->"float4": ...

        @qtps.setter
        def qtps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtpt(self)->"float4": ...

        @property
        def qtpp(self)->"float4": ...

        @property
        def qtpq(self)->"float4": ...

        @property
        def qtqs(self)->"float4": ...

        @property
        def qtqt(self)->"float4": ...

        @property
        def qtqp(self)->"float4": ...

        @property
        def qtqq(self)->"float4": ...

        @property
        def qpss(self)->"float4": ...

        @property
        def qpst(self)->"float4": ...

        @qpst.setter
        def qpst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qpsp(self)->"float4": ...

        @property
        def qpsq(self)->"float4": ...

        @property
        def qpts(self)->"float4": ...

        @qpts.setter
        def qpts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qptt(self)->"float4": ...

        @property
        def qptp(self)->"float4": ...

        @property
        def qptq(self)->"float4": ...

        @property
        def qpps(self)->"float4": ...

        @property
        def qppt(self)->"float4": ...

        @property
        def qppp(self)->"float4": ...

        @property
        def qppq(self)->"float4": ...

        @property
        def qpqs(self)->"float4": ...

        @property
        def qpqt(self)->"float4": ...

        @property
        def qpqp(self)->"float4": ...

        @property
        def qpqq(self)->"float4": ...

        @property
        def qqss(self)->"float4": ...

        @property
        def qqst(self)->"float4": ...

        @property
        def qqsp(self)->"float4": ...

        @property
        def qqsq(self)->"float4": ...

        @property
        def qqts(self)->"float4": ...

        @property
        def qqtt(self)->"float4": ...

        @property
        def qqtp(self)->"float4": ...

        @property
        def qqtq(self)->"float4": ...

        @property
        def qqps(self)->"float4": ...

        @property
        def qqpt(self)->"float4": ...

        @property
        def qqpp(self)->"float4": ...

        @property
        def qqpq(self)->"float4": ...

        @property
        def qqqs(self)->"float4": ...

        @property
        def qqqt(self)->"float4": ...

        @property
        def qqqp(self)->"float4": ...

        @property
        def qqqq(self)->"float4": ...
        # --- END generated swizzles ---
