import ctypes
from typing import TYPE_CHECKING, Union

from .genVec3 import genVec3
from .half import half_fields, half_properties

if TYPE_CHECKING:

    from .genVec2 import genVec2
    from .half2 import half2
    from .half4 import half4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class half3(genVec3):

    _fields_ = half_fields(3)

    x, y, z = half_properties("xyz")

    @property
    def dtype(self)->type:
        return ctypes.c_uint16

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->float: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->float: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def z(self)->float: ...

        @z.setter
        def z(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->half2: ...

        @property
        def xy(self)->half2: ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xz(self)->half2: ...

        @xz.setter
        def xz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->half2: ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->half2: ...

        @property
        def yz(self)->half2: ...

        @yz.setter
        def yz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zx(self)->half2: ...

        @zx.setter
        def zx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zy(self)->half2: ...

        @zy.setter
        def zy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zz(self)->half2: ...

        @property
        def xxx(self)->"half3": ...

        @property
        def xxy(self)->"half3": ...

        @property
        def xxz(self)->"half3": ...

        @property
        def xyx(self)->"half3": ...

        @property
        def xyy(self)->"half3": ...

        @property
        def xyz(self)->"half3": ...

        @xyz.setter
        def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzx(self)->"half3": ...

        @property
        def xzy(self)->"half3": ...

        @xzy.setter
        def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzz(self)->"half3": ...

        @property
        def yxx(self)->"half3": ...

        @property
        def yxy(self)->"half3": ...

        @property
        def yxz(self)->"half3": ...

        @yxz.setter
        def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yyx(self)->"half3": ...

        @property
        def yyy(self)->"half3": ...

        @property
        def yyz(self)->"half3": ...

        @property
        def yzx(self)->"half3": ...

        @yzx.setter
        def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yzy(self)->"half3": ...

        @property
        def yzz(self)->"half3": ...

        @property
        def zxx(self)->"half3": ...

        @property
        def zxy(self)->"half3": ...

        @zxy.setter
        def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zxz(self)->"half3": ...

        @property
        def zyx(self)->"half3": ...

        @zyx.setter
        def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyy(self)->"half3": ...

        @property
        def zyz(self)->"half3": ...

        @property
        def zzx(self)->"half3": ...

        @property
        def zzy(self)->"half3": ...

        @property
        def zzz(self)->"half3": ...

        @property
        def xxxx(self)->half4: ...

        @property
        def xxxy(self)->half4: ...

        @property
        def xxxz(self)->half4: ...

        @property
        def xxyx(self)->half4: ...

        @property
        def xxyy(self)->half4: ...

        @property
        def xxyz(self)->half4: ...

        @property
        def xxzx(self)->half4: ...

        @property
        def xxzy(self)->half4: ...

        @property
        def xxzz(self)->half4: ...

        @property
        def xyxx(self)->half4: ...

        @property
        def xyxy(self)->half4: ...

        @property
        def xyxz(self)->half4: ...

        @property
        def xyyx(self)->half4: ...

        @property
        def xyyy(self)->half4: ...

        @property
        def xyyz(self)->half4: ...

        @property
        def xyzx(self)->half4: ...

        @property
        def xyzy(self)->half4: ...

        @property
        def xyzz(self)->half4: ...

        @property
        def xzxx(self)->half4: ...

        @property
        def xzxy(self)->half4: ...

        @property
        def xzxz(self)->half4: ...

        @property
        def xzyx(self)->half4: ...

        @property
        def xzyy(self)->half4: ...

        @property
        def xzyz(self)->half4: ...

        @property
        def xzzx(self)->half4: ...

        @property
        def xzzy(self)->half4: ...

        @property
        def xzzz(self)->half4: ...

        @property
        def yxxx(self)->half4: ...

        @property
        def yxxy(self)->half4: ...

        @property
        def yxxz(self)->half4: ...

        @property
        def yxyx(self)->half4: ...

        @property
        def yxyy(self)->half4: ...

        @property
        def yxyz(self)->half4: ...

        @property
        def yxzx(self)->half4: ...

        @property
        def yxzy(self)->half4: ...

        @property
        def yxzz(self)->half4: ...

        @property
        def yyxx(self)->half4: ...

        @property
        def yyxy(self)->half4: ...

        @property
        def yyxz(self)->half4: ...

        @property
        def yyyx(self)->half4: ...

        @property
        def yyyy(self)->half4: ...

        @property
        def yyyz(self)->half4: ...

        @property
        def yyzx(self)->half4: ...

        @property
        def yyzy(self)->half4: ...

        @property
        def yyzz(self)->half4: ...

        @property
        def yzxx(self)->half4: ...

        @property
        def yzxy(self)->half4: ...

        @property
        def yzxz(self)->half4: ...

        @property
        def yzyx(self)->half4: ...

        @property
        def yzyy(self)->half4: ...

        @property
        def yzyz(self)->half4: ...

        @property
        def yzzx(self)->half4: ...

        @property
        def yzzy(self)->half4: ...

        @property
        def yzzz(self)->half4: ...

        @property
        def zxxx(self)->half4: ...

        @property
        def zxxy(self)->half4: ...

        @property
        def zxxz(self)->half4: ...

        @property
        def zxyx(self)->half4: ...

        @property
        def zxyy(self)->half4: ...

        @property
        def zxyz(self)->half4: ...

        @property
        def zxzx(self)->half4: ...

        @property
        def zxzy(self)->half4: ...

        @property
        def zxzz(self)->half4: ...

        @property
        def zyxx(self)->half4: ...

        @property
        def zyxy(self)->half4: ...

        @property
        def zyxz(self)->half4: ...

        @property
        def zyyx(self)->half4: ...

        @property
        def zyyy(self)->half4: ...

        @property
        def zyyz(self)->half4: ...

        @property
        def zyzx(self)->half4: ...

        @property
        def zyzy(self)->half4: ...

        @property
        def zyzz(self)->half4: ...

        @property
        def zzxx(self)->half4: ...

        @property
        def zzxy(self)->half4: ...

        @property
        def zzxz(self)->half4: ...

        @property
        def zzyx(self)->half4: ...

        @property
        def zzyy(self)->half4: ...

        @property
        def zzyz(self)->half4: ...

        @property
        def zzzx(self)->half4: ...

        @property
        def zzzy(self)->half4: ...

        @property
        def zzzz(self)->half4: ...

        @property
        def r(self)->float: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->float: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def b(self)->float: ...

        @b.setter
        def b(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->half2: ...

        @property
        def rg(self)->half2: ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def rb(self)->half2: ...

        @rb.setter
        def rb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->half2: ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->half2: ...

        @property
        def gb(self)->half2: ...

        @gb.setter
        def gb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def br(self)->half2: ...

        @br.setter
        def br(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bg(self)->half2: ...

        @bg.setter
        def bg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bb(self)->half2: ...

        @property
        def rrr(self)->"half3": ...

        @property
        def rrg(self)->"half3": ...

        @property
        def rrb(self)->"half3": ...

        @property
        def rgr(self)->"half3": ...

        @property
        def rgg(self)->"half3": ...

        @property
        def rgb(self)->"half3": ...

        @rgb.setter
        def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbr(self)->"half3": ...

        @property
        def rbg(self)->"half3": ...

        @rbg.setter
        def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbb(self)->"half3": ...

        @property
        def grr(self)->"half3": ...

        @property
        def grg(self)->"half3": ...

        @property
        def grb(self)->"half3": ...

        @grb.setter
        def grb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ggr(self)->"half3": ...

        @property
        def ggg(self)->"half3": ...

        @property
        def ggb(self)->"half3": ...

        @property
        def gbr(self)->"half3": ...

        @gbr.setter
        def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gbg(self)->"half3": ...

        @property
        def gbb(self)->"half3": ...

        @property
        def brr(self)->"half3": ...

        @property
        def brg(self)->"half3": ...

        @brg.setter
        def brg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def brb(self)->"half3": ...

        @property
        def bgr(self)->"half3": ...

        @bgr.setter
        def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgg(self)->"half3": ...

        @property
        def bgb(self)->"half3": ...

        @property
        def bbr(self)->"half3": ...

        @property
        def bbg(self)->"half3": ...

        @property
        def bbb(self)->"half3": ...

        @property
        def rrrr(self)->half4: ...

        @property
        def rrrg(self)->half4: ...

        @property
        def rrrb(self)->half4: ...

        @property
        def rrgr(self)->half4: ...

        @property
        def rrgg(self)->half4: ...

        @property
        def rrgb(self)->half4: ...

        @property
        def rrbr(self)->half4: ...

        @property
        def rrbg(self)->half4: ...

        @property
        def rrbb(self)->half4: ...

        @property
        def rgrr(self)->half4: ...

        @property
        def rgrg(self)->half4: ...

        @property
        def rgrb(self)->half4: ...

        @property
        def rggr(self)->half4: ...

        @property
        def rggg(self)->half4: ...

        @property
        def rggb(self)->half4: ...

        @property
        def rgbr(self)->half4: ...

        @property
        def rgbg(self)->half4: ...

        @property
        def rgbb(self)->half4: ...

        @property
        def rbrr(self)->half4: ...

        @property
        def rbrg(self)->half4: ...

        @property
        def rbrb(self)->half4: ...

        @property
        def rbgr(self)->half4: ...

        @property
        def rbgg(self)->half4: ...

        @property
        def rbgb(self)->half4: ...

        @property
        def rbbr(self)->half4: ...

        @property
        def rbbg(self)->half4: ...

        @property
        def rbbb(self)->half4: ...

        @property
        def grrr(self)->half4: ...

        @property
        def grrg(self)->half4: ...

        @property
        def grrb(self)->half4: ...

        @property
        def grgr(self)->half4: ...

        @property
        def grgg(self)->half4: ...

        @property
        def grgb(self)->half4: ...

        @property
        def grbr(self)->half4: ...

        @property
        def grbg(self)->half4: ...

        @property
        def grbb(self)->half4: ...

        @property
        def ggrr(self)->half4: ...

        @property
        def ggrg(self)->half4: ...

        @property
        def ggrb(self)->half4: ...

        @property
        def gggr(self)->half4: ...

        @property
        def gggg(self)->half4: ...

        @property
        def gggb(self)->half4: ...

        @property
        def ggbr(self)->half4: ...

        @property
        def ggbg(self)->half4: ...

        @property
        def ggbb(self)->half4: ...

        @property
        def gbrr(self)->half4: ...

        @property
        def gbrg(self)->half4: ...

        @property
        def gbrb(self)->half4: ...

        @property
        def gbgr(self)->half4: ...

        @property
        def gbgg(self)->half4: ...

        @property
        def gbgb(self)->half4: ...

        @property
        def gbbr(self)->half4: ...

        @property
        def gbbg(self)->half4: ...

        @property
        def gbbb(self)->half4: ...

        @property
        def brrr(self)->half4: ...

        @property
        def brrg(self)->half4: ...

        @property
        def brrb(self)->half4: ...

        @property
        def brgr(self)->half4: ...

        @property
        def brgg(self)->half4: ...

        @property
        def brgb(self)->half4: ...

        @property
        def brbr(self)->half4: ...

        @property
        def brbg(self)->half4: ...

        @property
        def brbb(self)->half4: ...

        @property
        def bgrr(self)->half4: ...

        @property
        def bgrg(self)->half4: ...

        @property
        def bgrb(self)->half4: ...

        @property
        def bggr(self)->half4: ...

        @property
        def bggg(self)->half4: ...

        @property
        def bggb(self)->half4: ...

        @property
        def bgbr(self)->half4: ...

        @property
        def bgbg(self)->half4: ...

        @property
        def bgbb(self)->half4: ...

        @property
        def bbrr(self)->half4: ...

        @property
        def bbrg(self)->half4: ...

        @property
        def bbrb(self)->half4: ...

        @property
        def bbgr(self)->half4: ...

        @property
        def bbgg(self)->half4: ...

        @property
        def bbgb(self)->half4: ...

        @property
        def bbbr(self)->half4: ...

        @property
        def bbbg(self)->half4: ...

        @property
        def bbbb(self)->half4: ...

        @property
        def s(self)->float: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->float: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def p(self)->float: ...

        @p.setter
        def p(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->half2: ...

        @property
        def st(self)->half2: ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sp(self)->half2: ...

        @sp.setter
        def sp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->half2: ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->half2: ...

        @property
        def tp(self)->half2: ...

        @tp.setter
        def tp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ps(self)->half2: ...

        @ps.setter
        def ps(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pt(self)->half2: ...

        @pt.setter
        def pt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pp(self)->half2: ...

        @property
        def sss(self)->"half3": ...

        @property
        def sst(self)->"half3": ...

        @property
        def ssp(self)->"half3": ...

        @property
        def sts(self)->"half3": ...

        @property
        def stt(self)->"half3": ...

        @property
        def stp(self)->"half3": ...

        @stp.setter
        def stp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sps(self)->"half3": ...

        @property
        def spt(self)->"half3": ...

        @spt.setter
        def spt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def spp(self)->"half3": ...

        @property
        def tss(self)->"half3": ...

        @property
        def tst(self)->"half3": ...

        @property
        def tsp(self)->"half3": ...

        @tsp.setter
        def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tts(self)->"half3": ...

        @property
        def ttt(self)->"half3": ...

        @property
        def ttp(self)->"half3": ...

        @property
        def tps(self)->"half3": ...

        @tps.setter
        def tps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tpt(self)->"half3": ...

        @property
        def tpp(self)->"half3": ...

        @property
        def pss(self)->"half3": ...

        @property
        def pst(self)->"half3": ...

        @pst.setter
        def pst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def psp(self)->"half3": ...

        @property
        def pts(self)->"half3": ...

        @pts.setter
        def pts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ptt(self)->"half3": ...

        @property
        def ptp(self)->"half3": ...

        @property
        def pps(self)->"half3": ...

        @property
        def ppt(self)->"half3": ...

        @property
        def ppp(self)->"half3": ...

        @property
        def ssss(self)->half4: ...

        @property
        def ssst(self)->half4: ...

        @property
        def sssp(self)->half4: ...

        @property
        def ssts(self)->half4: ...

        @property
        def sstt(self)->half4: ...

        @property
        def sstp(self)->half4: ...

        @property
        def ssps(self)->half4: ...

        @property
        def sspt(self)->half4: ...

        @property
        def sspp(self)->half4: ...

        @property
        def stss(self)->half4: ...

        @property
        def stst(self)->half4: ...

        @property
        def stsp(self)->half4: ...

        @property
        def stts(self)->half4: ...

        @property
        def sttt(self)->half4: ...

        @property
        def sttp(self)->half4: ...

        @property
        def stps(self)->half4: ...

        @property
        def stpt(self)->half4: ...

        @property
        def stpp(self)->half4: ...

        @property
        def spss(self)->half4: ...

        @property
        def spst(self)->half4: ...

        @property
        def spsp(self)->half4: ...

        @property
        def spts(self)->half4: ...

        @property
        def sptt(self)->half4: ...

        @property
        def sptp(self)->half4: ...

        @property
        def spps(self)->half4: ...

        @property
        def sppt(self)->half4: ...

        @property
        def sppp(self)->half4: ...

        @property
        def tsss(self)->half4: ...

        @property
        def tsst(self)->half4: ...

        @property
        def tssp(self)->half4: ...

        @property
        def tsts(self)->half4: ...

        @property
        def tstt(self)->half4: ...

        @property
        def tstp(self)->half4: ...

        @property
        def tsps(self)->half4: ...

        @property
        def tspt(self)->half4: ...

        @property
        def tspp(self)->half4: ...

        @property
        def ttss(self)->half4: ...

        @property
        def ttst(self)->half4: ...

        @property
        def ttsp(self)->half4: ...

        @property
        def ttts(self)->half4: ...

        @property
        def tttt(self)->half4: ...

        @property
        def tttp(self)->half4: ...

        @property
        def ttps(self)->half4: ...

        @property
        def ttpt(self)->half4: ...

        @property
        def ttpp(self)->half4: ...

        @property
        def tpss(self)->half4: ...

        @property
        def tpst(self)->half4: ...

        @property
        def tpsp(self)->half4: ...

        @property
        def tpts(self)->half4: ...

        @property
        def tptt(self)->half4: ...

        @property
        def tptp(self)->half4: ...

        @property
        def tpps(self)->half4: ...

        @property
        def tppt(self)->half4: ...

        @property
        def tppp(self)->half4: ...

        @property
        def psss(self)->half4: ...

        @property
        def psst(self)->half4: ...

        @property
        def pssp(self)->half4: ...

        @property
        def psts(self)->half4: ...

        @property
        def pstt(self)->half4: ...

        @property
        def pstp(self)->half4: ...

        @property
        def psps(self)->half4: ...

        @property
        def pspt(self)->half4: ...

        @property
        def pspp(self)->half4: ...

        @property
        def ptss(self)->half4: ...

        @property
        def ptst(self)->half4: ...

        @property
        def ptsp(self)->half4: ...

        @property
        def ptts(self)->half4: ...

        @property
        def pttt(self)->half4: ...

        @property
        def pttp(self)->half4: ...

        @property
        def ptps(self)->half4: ...

        @property
        def ptpt(self)->half4: ...

        @property
        def ptpp(self)->half4: ...

        @property
        def ppss(self)->half4: ...

        @property
        def ppst(self)->half4: ...

        @property
        def ppsp(self)->half4: ...

        @property
        def ppts(self)->half4: ...

        @property
        def pptt(self)->half4: ...

        @property
        def pptp(self)->half4: ...

        @property
        def ppps(self)->half4: ...

        @property
        def pppt(self)->half4: ...

        @property
        def pppp(self)->half4: ...
        # --- END generated swizzles ---
