import ctypes
from typing import TYPE_CHECKING, Union

from .genVec4 import genVec4
from .half import half_fields, half_properties

if TYPE_CHECKING:

    from .genVec2 import genVec2
    from .genVec3 import genVec3
    from .half2 import half2
    from .half3 import half3

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class half4(genVec4):

    _fields_ = half_fields(4)

    x, y, z, w = half_properties("xyzw")

    @property
    def dtype(self)->type:
        return ctypes.c_uint16

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->float: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->float: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def z(self)->float: ...

        @z.setter
        def z(self, value:Union[bool, int, float])->None: ...

        @property
        def w(self)->float: ...

        @w.setter
        def w(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->half2: ...

        @property
        def xy(self)->half2: ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xz(self)->half2: ...

        @xz.setter
        def xz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xw(self)->half2: ...

        @xw.setter
        def xw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->half2: ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->half2: ...

        @property
        def yz(self)->half2: ...

        @yz.setter
        def yz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yw(self)->half2: ...

        @yw.setter
        def yw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zx(self)->half2: ...

        @zx.setter
        def zx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zy(self)->half2: ...

        @zy.setter
        def zy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zz(self)->half2: ...

        @property
        def zw(self)->half2: ...

        @zw.setter
        def zw(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wx(self)->half2: ...

        @wx.setter
        def wx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wy(self)->half2: ...

        @wy.setter
        def wy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def wz(self)->half2: ...

        @wz.setter
        def wz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ww(self)->half2: ...

        @property
        def xxx(self)->half3: ...

        @property
        def xxy(self)->half3: ...

        @property
        def xxz(self)->half3: ...

        @property
        def xxw(self)->half3: ...

        @property
        def xyx(self)->half3: ...

        @property
        def xyy(self)->half3: ...

        @property
        def xyz(self)->half3: ...

        @xyz.setter
        def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xyw(self)->half3: ...

        @xyw.setter
        def xyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzx(self)->half3: ...

        @property
        def xzy(self)->half3: ...

        @xzy.setter
        def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzz(self)->half3: ...

        @property
        def xzw(self)->half3: ...

        @xzw.setter
        def xzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwx(self)->half3: ...

        @property
        def xwy(self)->half3: ...

        @xwy.setter
        def xwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xwz(self)->half3: ...

        @xwz.setter
        def xwz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xww(self)->half3: ...

        @property
        def yxx(self)->half3: ...

        @property
        def yxy(self)->half3: ...

        @property
        def yxz(self)->half3: ...

        @yxz.setter
        def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yxw(self)->half3: ...

        @yxw.setter
        def yxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yyx(self)->half3: ...

        @property
        def yyy(self)->half3: ...

        @property
        def yyz(self)->half3: ...

        @property
        def yyw(self)->half3: ...

        @property
        def yzx(self)->half3: ...

        @yzx.setter
        def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yzy(self)->half3: ...

        @property
        def yzz(self)->half3: ...

        @property
        def yzw(self)->half3: ...

        @yzw.setter
        def yzw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywx(self)->half3: ...

        @ywx.setter
        def ywx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ywy(self)->half3: ...

        @property
        def ywz(self)->half3: ...

        @ywz.setter
        def ywz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yww(self)->half3: ...

        @property
        def zxx(self)->half3: ...

        @property
        def zxy(self)->half3: ...

        @zxy.setter
        def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zxz(self)->half3: ...

        @property
        def zxw(self)->half3: ...

        @zxw.setter
        def zxw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyx(self)->half3: ...

        @zyx.setter
        def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyy(self)->half3: ...

        @property
        def zyz(self)->half3: ...

        @property
        def zyw(self)->half3: ...

        @zyw.setter
        def zyw(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zzx(self)->half3: ...

        @property
        def zzy(self)->half3: ...

        @property
        def zzz(self)->half3: ...

        @property
        def zzw(self)->half3: ...

        @property
        def zwx(self)->half3: ...

        @zwx.setter
        def zwx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwy(self)->half3: ...

        @zwy.setter
        def zwy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zwz(self)->half3: ...

        @property
        def zww(self)->half3: ...

        @property
        def wxx(self)->half3: ...

        @property
        def wxy(self)->half3: ...

        @wxy.setter
        def wxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxz(self)->half3: ...

        @wxz.setter
        def wxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wxw(self)->half3: ...

        @property
        def wyx(self)->half3: ...

        @wyx.setter
        def wyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyy(self)->half3: ...

        @property
        def wyz(self)->half3: ...

        @wyz.setter
        def wyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wyw(self)->half3: ...

        @property
        def wzx(self)->half3: ...

        @wzx.setter
        def wzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzy(self)->half3: ...

        @wzy.setter
        def wzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def wzz(self)->half3: ...

        @property
        def wzw(self)->half3: ...

        @property
        def wwx(self)->half3: ...

        @property
        def wwy(self)->half3: ...

        @property
        def wwz(self)->half3: ...

        @property
        def www(self)->half3: ...

        @property
        def xxxx(self)->"half4": ...

        @property
        def xxxy(self)->"half4": ...

        @property
        def xxxz(self)->"half4": ...

        @property
        def xxxw(self)->"half4": ...

        @property
        def xxyx(self)->"half4": ...

        @property
        def xxyy(self)->"half4": ...

        @property
        def xxyz(self)->"half4": ...

        @property
        def xxyw(self)->"half4": ...

        @property
        def xxzx(self)->"half4": ...

        @property
        def xxzy(self)->"half4": ...

        @property
        def xxzz(self)->"half4": ...

        @property
        def xxzw(self)->"half4": ...

        @property
        def xxwx(self)->"half4": ...

        @property
        def xxwy(self)->"half4": ...

        @property
        def xxwz(self)->"half4": ...

        @property
        def xxww(self)->"half4": ...

        @property
        def xyxx(self)->"half4": ...

        @property
        def xyxy(self)->"half4": ...

        @property
        def xyxz(self)->"half4": ...

        @property
        def xyxw(self)->"half4": ...

        @property
        def xyyx(self)->"half4": ...

        @property
        def xyyy(self)->"half4": ...

        @property
        def xyyz(self)->"half4": ...

        @property
        def xyyw(self)->"half4": ...

        @property
        def xyzx(self)->"half4": ...

        @property
        def xyzy(self)->"half4": ...

        @property
        def xyzz(self)->"half4": ...

        @property
        def xyzw(self)->"half4": ...

        @xyzw.setter
        def xyzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xywx(self)->"half4": ...

        @property
        def xywy(self)->"half4": ...

        @property
        def xywz(self)->"half4": ...

        @xywz.setter
        def xywz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xyww(self)->"half4": ...

        @property
        def xzxx(self)->"half4": ...

        @property
        def xzxy(self)->"half4": ...

        @property
        def xzxz(self)->"half4": ...

        @property
        def xzxw(self)->"half4": ...

        @property
        def xzyx(self)->"half4": ...

        @property
        def xzyy(self)->"half4": ...

        @property
        def xzyz(self)->"half4": ...

        @property
        def xzyw(self)->"half4": ...

        @xzyw.setter
        def xzyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzzx(self)->"half4": ...

        @property
        def xzzy(self)->"half4": ...

        @property
        def xzzz(self)->"half4": ...

        @property
        def xzzw(self)->"half4": ...

        @property
        def xzwx(self)->"half4": ...

        @property
        def xzwy(self)->"half4": ...

        @xzwy.setter
        def xzwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xzwz(self)->"half4": ...

        @property
        def xzww(self)->"half4": ...

        @property
        def xwxx(self)->"half4": ...

        @property
        def xwxy(self)->"half4": ...

        @property
        def xwxz(self)->"half4": ...

        @property
        def xwxw(self)->"half4": ...

        @property
        def xwyx(self)->"half4": ...

        @property
        def xwyy(self)->"half4": ...

        @property
        def xwyz(self)->"half4": ...

        @xwyz.setter
        def xwyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwyw(self)->"half4": ...

        @property
        def xwzx(self)->"half4": ...

        @property
        def xwzy(self)->"half4": ...

        @xwzy.setter
        def xwzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def xwzz(self)->"half4": ...

        @property
        def xwzw(self)->"half4": ...

        @property
        def xwwx(self)->"half4": ...

        @property
        def xwwy(self)->"half4": ...

        @property
        def xwwz(self)->"half4": ...

        @property
        def xwww(self)->"half4": ...

        @property
        def yxxx(self)->"half4": ...

        @property
        def yxxy(self)->"half4": ...

        @property
        def yxxz(self)->"half4": ...

        @property
        def yxxw(self)->"half4": ...

        @property
        def yxyx(self)->"half4": ...

        @property
        def yxyy(self)->"half4": ...

        @property
        def yxyz(self)->"half4": ...

        @property
        def yxyw(self)->"half4": ...

        @property
        def yxzx(self)->"half4": ...

        @property
        def yxzy(self)->"half4": ...

        @property
        def yxzz(self)->"half4": ...

        @property
        def yxzw(self)->"half4": ...

        @yxzw.setter
        def yxzw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxwx(self)->"half4": ...

        @property
        def yxwy(self)->"half4": ...

        @property
        def yxwz(self)->"half4": ...

        @yxwz.setter
        def yxwz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yxww(self)->"half4": ...

        @property
        def yyxx(self)->"half4": ...

        @property
        def yyxy(self)->"half4": ...

        @property
        def yyxz(self)->"half4": ...

        @property
        def yyxw(self)->"half4": ...

        @property
        def yyyx(self)->"half4": ...

        @property
        def yyyy(self)->"half4": ...

        @property
        def yyyz(self)->"half4": ...

        @property
        def yyyw(self)->"half4": ...

        @property
        def yyzx(self)->"half4": ...

        @property
        def yyzy(self)->"half4": ...

        @property
        def yyzz(self)->"half4": ...

        @property
        def yyzw(self)->"half4": ...

        @property
        def yywx(self)->"half4": ...

        @property
        def yywy(self)->"half4": ...

        @property
        def yywz(self)->"half4": ...

        @property
        def yyww(self)->"half4": ...

        @property
        def yzxx(self)->"half4": ...

        @property
        def yzxy(self)->"half4": ...

        @property
        def yzxz(self)->"half4": ...

        @property
        def yzxw(self)->"half4": ...

        @yzxw.setter
        def yzxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzyx(self)->"half4": ...

        @property
        def yzyy(self)->"half4": ...

        @property
        def yzyz(self)->"half4": ...

        @property
        def yzyw(self)->"half4": ...

        @property
        def yzzx(self)->"half4": ...

        @property
        def yzzy(self)->"half4": ...

        @property
        def yzzz(self)->"half4": ...

        @property
        def yzzw(self)->"half4": ...

        @property
        def yzwx(self)->"half4": ...

        @yzwx.setter
        def yzwx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def yzwy(self)->"half4": ...

        @property
        def yzwz(self)->"half4": ...

        @property
        def yzww(self)->"half4": ...

        @property
        def ywxx(self)->"half4": ...

        @property
        def ywxy(self)->"half4": ...

        @property
        def ywxz(self)->"half4": ...

        @ywxz.setter
        def ywxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywxw(self)->"half4": ...

        @property
        def ywyx(self)->"half4": ...

        @property
        def ywyy(self)->"half4": ...

        @property
        def ywyz(self)->"half4": ...

        @property
        def ywyw(self)->"half4": ...

        @property
        def ywzx(self)->"half4": ...

        @ywzx.setter
        def ywzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ywzy(self)->"half4": ...

        @property
        def ywzz(self)->"half4": ...

        @property
        def ywzw(self)->"half4": ...

        @property
        def ywwx(self)->"half4": ...

        @property
        def ywwy(self)->"half4": ...

        @property
        def ywwz(self)->"half4": ...

        @property
        def ywww(self)->"half4": ...

        @property
        def zxxx(self)->"half4": ...

        @property
        def zxxy(self)->"half4": ...

        @property
        def zxxz(self)->"half4": ...

        @property
        def zxxw(self)->"half4": ...

        @property
        def zxyx(self)->"half4": ...

        @property
        def zxyy(self)->"half4": ...

        @property
        def zxyz(self)->"half4": ...

        @property
        def zxyw(self)->"half4": ...

        @zxyw.setter
        def zxyw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxzx(self)->"half4": ...

        @property
        def zxzy(self)->"half4": ...

        @property
        def zxzz(self)->"half4": ...

        @property
        def zxzw(self)->"half4": ...

        @property
        def zxwx(self)->"half4": ...

        @property
        def zxwy(self)->"half4": ...

        @zxwy.setter
        def zxwy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zxwz(self)->"half4": ...

        @property
        def zxww(self)->"half4": ...

        @property
        def zyxx(self)->"half4": ...

        @property
        def zyxy(self)->"half4": ...

        @property
        def zyxz(self)->"half4": ...

        @property
        def zyxw(self)->"half4": ...

        @zyxw.setter
        def zyxw(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zyyx(self)->"half4": ...

        @property
        def zyyy(self)->"half4": ...

        @property
        def zyyz(self)->"half4": ...

        @property
        def zyyw(self)->"half4": ...

        @property
        def zyzx(self)->"half4": ...

        @property
        def zyzy(self)->"half4": ...

        @property
        def zyzz(self)->"half4": ...

        @property
        def zyzw(self)->"half4": ...

        @property
        def zywx(self)->"half4": ...

        @zywx.setter
        def zywx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zywy(self)->"half4": ...

        @property
        def zywz(self)->"half4": ...

        @property
        def zyww(self)->"half4": ...

        @property
        def zzxx(self)->"half4": ...

        @property
        def zzxy(self)->"half4": ...

        @property
        def zzxz(self)->"half4": ...

        @property
        def zzxw(self)->"half4": ...

        @property
        def zzyx(self)->"half4": ...

        @property
        def zzyy(self)->"half4": ...

        @property
        def zzyz(self)->"half4": ...

        @property
        def zzyw(self)->"half4": ...

        @property
        def zzzx(self)->"half4": ...

        @property
        def zzzy(self)->"half4": ...

        @property
        def zzzz(self)->"half4": ...

        @property
        def zzzw(self)->"half4": ...

        @property
        def zzwx(self)->"half4": ...

        @property
        def zzwy(self)->"half4": ...

        @property
        def zzwz(self)->"half4": ...

        @property
        def zzww(self)->"half4": ...

        @property
        def zwxx(self)->"half4": ...

        @property
        def zwxy(self)->"half4": ...

        @zwxy.setter
        def zwxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwxz(self)->"half4": ...

        @property
        def zwxw(self)->"half4": ...

        @property
        def zwyx(self)->"half4": ...

        @zwyx.setter
        def zwyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def zwyy(self)->"half4": ...

        @property
        def zwyz(self)->"half4": ...

        @property
        def zwyw(self)->"half4": ...

        @property
        def zwzx(self)->"half4": ...

        @property
        def zwzy(self)->"half4": ...

        @property
        def zwzz(self)->"half4": ...

        @property
        def zwzw(self)->"half4": ...

        @property
        def zwwx(self)->"half4": ...

        @property
        def zwwy(self)->"half4": ...

        @property
        def zwwz(self)->"half4": ...

        @property
        def zwww(self)->"half4": ...

        @property
        def wxxx(self)->"half4": ...

        @property
        def wxxy(self)->"half4": ...

        @property
        def wxxz(self)->"half4": ...

        @property
        def wxxw(self)->"half4": ...

        @property
        def wxyx(self)->"half4": ...

        @property
        def wxyy(self)->"half4": ...

        @property
        def wxyz(self)->"half4": ...

        @wxyz.setter
        def wxyz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxyw(self)->"half4": ...

        @property
        def wxzx(self)->"half4": ...

        @property
        def wxzy(self)->"half4": ...

        @wxzy.setter
        def wxzy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wxzz(self)->"half4": ...

        @property
        def wxzw(self)->"half4": ...

        @property
        def wxwx(self)->"half4": ...

        @property
        def wxwy(self)->"half4": ...

        @property
        def wxwz(self)->"half4": ...

        @property
        def wxww(self)->"half4": ...

        @property
        def wyxx(self)->"half4": ...

        @property
        def wyxy(self)->"half4": ...

        @property
        def wyxz(self)->"half4": ...

        @wyxz.setter
        def wyxz(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyxw(self)->"half4": ...

        @property
        def wyyx(self)->"half4": ...

        @property
        def wyyy(self)->"half4": ...

        @property
        def wyyz(self)->"half4": ...

        @property
        def wyyw(self)->"half4": ...

        @property
        def wyzx(self)->"half4": ...

        @wyzx.setter
        def wyzx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wyzy(self)->"half4": ...

        @property
        def wyzz(self)->"half4": ...

        @property
        def wyzw(self)->"half4": ...

        @property
        def wywx(self)->"half4": ...

        @property
        def wywy(self)->"half4": ...

        @property
        def wywz(self)->"half4": ...

        @property
        def wyww(self)->"half4": ...

        @property
        def wzxx(self)->"half4": ...

        @property
        def wzxy(self)->"half4": ...

        @wzxy.setter
        def wzxy(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzxz(self)->"half4": ...

        @property
        def wzxw(self)->"half4": ...

        @property
        def wzyx(self)->"half4": ...

        @wzyx.setter
        def wzyx(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def wzyy(self)->"half4": ...

        @property
        def wzyz(self)->"half4": ...

        @property
        def wzyw(self)->"half4": ...

        @property
        def wzzx(self)->"half4": ...

        @property
        def wzzy(self)->"half4": ...

        @property
        def wzzz(self)->"half4": ...

        @property
        def wzzw(self)->"half4": ...

        @property
        def wzwx(self)->"half4": ...

        @property
        def wzwy(self)->"half4": ...

        @property
        def wzwz(self)->"half4": ...

        @property
        def wzww(self)->"half4": ...

        @property
        def wwxx(self)->"half4": ...

        @property
        def wwxy(self)->"half4": ...

        @property
        def wwxz(self)->"half4": ...

        @property
        def wwxw(self)->"half4": ...

        @property
        def wwyx(self)->"half4": ...

        @property
        def wwyy(self)->"half4": ...

        @property
        def wwyz(self)->"half4": ...

        @property
        def wwyw(self)->"half4": ...

        @property
        def wwzx(self)->"half4": ...

        @property
        def wwzy(self)->"half4": ...

        @property
        def wwzz(self)->"half4": ...

        @property
        def wwzw(self)->"half4": ...

        @property
        def wwwx(self)->"half4": ...

        @property
        def wwwy(self)->"half4": ...

        @property
        def wwwz(self)->"half4": ...

        @property
        def wwww(self)->"half4": ...

        @property
        def r(self)->float: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->float: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def b(self)->float: ...

        @b.setter
        def b(self, value:Union[bool, int, float])->None: ...

        @property
        def a(self)->float: ...

        @a.setter
        def a(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->half2: ...

        @property
        def rg(self)->half2: ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def rb(self)->half2: ...

        @rb.setter
        def rb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ra(self)->half2: ...

        @ra.setter
        def ra(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->half2: ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->half2: ...

        @property
        def gb(self)->half2: ...

        @gb.setter
        def gb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ga(self)->half2: ...

        @ga.setter
        def ga(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def br(self)->half2: ...

        @br.setter
        def br(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bg(self)->half2: ...

        @bg.setter
        def bg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bb(self)->half2: ...

        @property
        def ba(self)->half2: ...

        @ba.setter
        def ba(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ar(self)->half2: ...

        @ar.setter
        def ar(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ag(self)->half2: ...

        @ag.setter
        def ag(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ab(self)->half2: ...

        @ab.setter
        def ab(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def aa(self)->half2: ...

        @property
        def rrr(self)->half3: ...

        @property
        def rrg(self)->half3: ...

        @property
        def rrb(self)->half3: ...

        @property
        def rra(self)->half3: ...

        @property
        def rgr(self)->half3: ...

        @property
        def rgg(self)->half3: ...

        @property
        def rgb(self)->half3: ...

        @rgb.setter
        def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rga(self)->half3: ...

        @rga.setter
        def rga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbr(self)->half3: ...

        @property
        def rbg(self)->half3: ...

        @rbg.setter
        def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbb(self)->half3: ...

        @property
        def rba(self)->half3: ...

        @rba.setter
        def rba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rar(self)->half3: ...

        @property
        def rag(self)->half3: ...

        @rag.setter
        def rag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rab(self)->half3: ...

        @rab.setter
        def rab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def raa(self)->half3: ...

        @property
        def grr(self)->half3: ...

        @property
        def grg(self)->half3: ...

        @property
        def grb(self)->half3: ...

        @grb.setter
        def grb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gra(self)->half3: ...

        @gra.setter
        def gra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ggr(self)->half3: ...

        @property
        def ggg(self)->half3: ...

        @property
        def ggb(self)->half3: ...

        @property
        def gga(self)->half3: ...

        @property
        def gbr(self)->half3: ...

        @gbr.setter
        def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gbg(self)->half3: ...

        @property
        def gbb(self)->half3: ...

        @property
        def gba(self)->half3: ...

        @gba.setter
        def gba(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gar(self)->half3: ...

        @gar.setter
        def gar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gag(self)->half3: ...

        @property
        def gab(self)->half3: ...

        @gab.setter
        def gab(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gaa(self)->half3: ...

        @property
        def brr(self)->half3: ...

        @property
        def brg(self)->half3: ...

        @brg.setter
        def brg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def brb(self)->half3: ...

        @property
        def bra(self)->half3: ...

        @bra.setter
        def bra(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgr(self)->half3: ...

        @bgr.setter
        def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgg(self)->half3: ...

        @property
        def bgb(self)->half3: ...

        @property
        def bga(self)->half3: ...

        @bga.setter
        def bga(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bbr(self)->half3: ...

        @property
        def bbg(self)->half3: ...

        @property
        def bbb(self)->half3: ...

        @property
        def bba(self)->half3: ...

        @property
        def bar(self)->half3: ...

        @bar.setter
        def bar(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bag(self)->half3: ...

        @bag.setter
        def bag(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bab(self)->half3: ...

        @property
        def baa(self)->half3: ...

        @property
        def arr(self)->half3: ...

        @property
        def arg(self)->half3: ...

        @arg.setter
        def arg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def arb(self)->half3: ...

        @arb.setter
        def arb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ara(self)->half3: ...

        @property
        def agr(self)->half3: ...

        @agr.setter
        def agr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def agg(self)->half3: ...

        @property
        def agb(self)->half3: ...

        @agb.setter
        def agb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def aga(self)->half3: ...

        @property
        def abr(self)->half3: ...

        @abr.setter
        def abr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abg(self)->half3: ...

        @abg.setter
        def abg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def abb(self)->half3: ...

        @property
        def aba(self)->half3: ...

        @property
        def aar(self)->half3: ...

        @property
        def aag(self)->half3: ...

        @property
        def aab(self)->half3: ...

        @property
        def aaa(self)->half3: ...

        @property
        def rrrr(self)->"half4": ...

        @property
        def rrrg(self)->"half4": ...

        @property
        def rrrb(self)->"half4": ...

        @property
        def rrra(self)->"half4": ...

        @property
        def rrgr(self)->"half4": ...

        @property
        def rrgg(self)->"half4": ...

        @property
        def rrgb(self)->"half4": ...

        @property
        def rrga(self)->"half4": ...

        @property
        def rrbr(self)->"half4": ...

        @property
        def rrbg(self)->"half4": ...

        @property
        def rrbb(self)->"half4": ...

        @property
        def rrba(self)->"half4": ...

        @property
        def rrar(self)->"half4": ...

        @property
        def rrag(self)->"half4": ...

        @property
        def rrab(self)->"half4": ...

        @property
        def rraa(self)->"half4": ...

        @property
        def rgrr(self)->"half4": ...

        @property
        def rgrg(self)->"half4": ...

        @property
        def rgrb(self)->"half4": ...

        @property
        def rgra(self)->"half4": ...

        @property
        def rggr(self)->"half4": ...

        @property
        def rggg(self)->"half4": ...

        @property
        def rggb(self)->"half4": ...

        @property
        def rgga(self)->"half4": ...

        @property
        def rgbr(self)->"half4": ...

        @property
        def rgbg(self)->"half4": ...

        @property
        def rgbb(self)->"half4": ...

        @property
        def rgba(self)->"half4": ...

        @rgba.setter
        def rgba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgar(self)->"half4": ...

        @property
        def rgag(self)->"half4": ...

        @property
        def rgab(self)->"half4": ...

        @rgab.setter
        def rgab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rgaa(self)->"half4": ...

        @property
        def rbrr(self)->"half4": ...

        @property
        def rbrg(self)->"half4": ...

        @property
        def rbrb(self)->"half4": ...

        @property
        def rbra(self)->"half4": ...

        @property
        def rbgr(self)->"half4": ...

        @property
        def rbgg(self)->"half4": ...

        @property
        def rbgb(self)->"half4": ...

        @property
        def rbga(self)->"half4": ...

        @rbga.setter
        def rbga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbbr(self)->"half4": ...

        @property
        def rbbg(self)->"half4": ...

        @property
        def rbbb(self)->"half4": ...

        @property
        def rbba(self)->"half4": ...

        @property
        def rbar(self)->"half4": ...

        @property
        def rbag(self)->"half4": ...

        @rbag.setter
        def rbag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rbab(self)->"half4": ...

        @property
        def rbaa(self)->"half4": ...

        @property
        def rarr(self)->"half4": ...

        @property
        def rarg(self)->"half4": ...

        @property
        def rarb(self)->"half4": ...

        @property
        def rara(self)->"half4": ...

        @property
        def ragr(self)->"half4": ...

        @property
        def ragg(self)->"half4": ...

        @property
        def ragb(self)->"half4": ...

        @ragb.setter
        def ragb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def raga(self)->"half4": ...

        @property
        def rabr(self)->"half4": ...

        @property
        def rabg(self)->"half4": ...

        @rabg.setter
        def rabg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def rabb(self)->"half4": ...

        @property
        def raba(self)->"half4": ...

        @property
        def raar(self)->"half4": ...

        @property
        def raag(self)->"half4": ...

        @property
        def raab(self)->"half4": ...

        @property
        def raaa(self)->"half4": ...

        @property
        def grrr(self)->"half4": ...

        @property
        def grrg(self)->"half4": ...

        @property
        def grrb(self)->"half4": ...

        @property
        def grra(self)->"half4": ...

        @property
        def grgr(self)->"half4": ...

        @property
        def grgg(self)->"half4": ...

        @property
        def grgb(self)->"half4": ...

        @property
        def grga(self)->"half4": ...

        @property
        def grbr(self)->"half4": ...

        @property
        def grbg(self)->"half4": ...

        @property
        def grbb(self)->"half4": ...

        @property
        def grba(self)->"half4": ...

        @grba.setter
        def grba(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def grar(self)->"half4": ...

        @property
        def grag(self)->"half4": ...

        @property
        def grab(self)->"half4": ...

        @grab.setter
        def grab(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def graa(self)->"half4": ...

        @property
        def ggrr(self)->"half4": ...

        @property
        def ggrg(self)->"half4": ...

        @property
        def ggrb(self)->"half4": ...

        @property
        def ggra(self)->"half4": ...

        @property
        def gggr(self)->"half4": ...

        @property
        def gggg(self)->"half4": ...

        @property
        def gggb(self)->"half4": ...

        @property
        def ggga(self)->"half4": ...

        @property
        def ggbr(self)->"half4": ...

        @property
        def ggbg(self)->"half4": ...

        @property
        def ggbb(self)->"half4": ...

        @property
        def ggba(self)->"half4": ...

        @property
        def ggar(self)->"half4": ...

        @property
        def ggag(self)->"half4": ...

        @property
        def ggab(self)->"half4": ...

        @property
        def ggaa(self)->"half4": ...

        @property
        def gbrr(self)->"half4": ...

        @property
        def gbrg(self)->"half4": ...

        @property
        def gbrb(self)->"half4": ...

        @property
        def gbra(self)->"half4": ...

        @gbra.setter
        def gbra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbgr(self)->"half4": ...

        @property
        def gbgg(self)->"half4": ...

        @property
        def gbgb(self)->"half4": ...

        @property
        def gbga(self)->"half4": ...

        @property
        def gbbr(self)->"half4": ...

        @property
        def gbbg(self)->"half4": ...

        @property
        def gbbb(self)->"half4": ...

        @property
        def gbba(self)->"half4": ...

        @property
        def gbar(self)->"half4": ...

        @gbar.setter
        def gbar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gbag(self)->"half4": ...

        @property
        def gbab(self)->"half4": ...

        @property
        def gbaa(self)->"half4": ...

        @property
        def garr(self)->"half4": ...

        @property
        def garg(self)->"half4": ...

        @property
        def garb(self)->"half4": ...

        @garb.setter
        def garb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gara(self)->"half4": ...

        @property
        def gagr(self)->"half4": ...

        @property
        def gagg(self)->"half4": ...

        @property
        def gagb(self)->"half4": ...

        @property
        def gaga(self)->"half4": ...

        @property
        def gabr(self)->"half4": ...

        @gabr.setter
        def gabr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def gabg(self)->"half4": ...

        @property
        def gabb(self)->"half4": ...

        @property
        def gaba(self)->"half4": ...

        @property
        def gaar(self)->"half4": ...

        @property
        def gaag(self)->"half4": ...

        @property
        def gaab(self)->"half4": ...

        @property
        def gaaa(self)->"half4": ...

        @property
        def brrr(self)->"half4": ...

        @property
        def brrg(self)->"half4": ...

        @property
        def brrb(self)->"half4": ...

        @property
        def brra(self)->"half4": ...

        @property
        def brgr(self)->"half4": ...

        @property
        def brgg(self)->"half4": ...

        @property
        def brgb(self)->"half4": ...

        @property
        def brga(self)->"half4": ...

        @brga.setter
        def brga(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brbr(self)->"half4": ...

        @property
        def brbg(self)->"half4": ...

        @property
        def brbb(self)->"half4": ...

        @property
        def brba(self)->"half4": ...

        @property
        def brar(self)->"half4": ...

        @property
        def brag(self)->"half4": ...

        @brag.setter
        def brag(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def brab(self)->"half4": ...

        @property
        def braa(self)->"half4": ...

        @property
        def bgrr(self)->"half4": ...

        @property
        def bgrg(self)->"half4": ...

        @property
        def bgrb(self)->"half4": ...

        @property
        def bgra(self)->"half4": ...

        @bgra.setter
        def bgra(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bggr(self)->"half4": ...

        @property
        def bggg(self)->"half4": ...

        @property
        def bggb(self)->"half4": ...

        @property
        def bgga(self)->"half4": ...

        @property
        def bgbr(self)->"half4": ...

        @property
        def bgbg(self)->"half4": ...

        @property
        def bgbb(self)->"half4": ...

        @property
        def bgba(self)->"half4": ...

        @property
        def bgar(self)->"half4": ...

        @bgar.setter
        def bgar(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bgag(self)->"half4": ...

        @property
        def bgab(self)->"half4": ...

        @property
        def bgaa(self)->"half4": ...

        @property
        def bbrr(self)->"half4": ...

        @property
        def bbrg(self)->"half4": ...

        @property
        def bbrb(self)->"half4": ...

        @property
        def bbra(self)->"half4": ...

        @property
        def bbgr(self)->"half4": ...

        @property
        def bbgg(self)->"half4": ...

        @property
        def bbgb(self)->"half4": ...

        @property
        def bbga(self)->"half4": ...

        @property
        def bbbr(self)->"half4": ...

        @property
        def bbbg(self)->"half4": ...

        @property
        def bbbb(self)->"half4": ...

        @property
        def bbba(self)->"half4": ...

        @property
        def bbar(self)->"half4": ...

        @property
        def bbag(self)->"half4": ...

        @property
        def bbab(self)->"half4": ...

        @property
        def bbaa(self)->"half4": ...

        @property
        def barr(self)->"half4": ...

        @property
        def barg(self)->"half4": ...

        @barg.setter
        def barg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def barb(self)->"half4": ...

        @property
        def bara(self)->"half4": ...

        @property
        def bagr(self)->"half4": ...

        @bagr.setter
        def bagr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def bagg(self)->"half4": ...

        @property
        def bagb(self)->"half4": ...

        @property
        def baga(self)->"half4": ...

        @property
        def babr(self)->"half4": ...

        @property
        def babg(self)->"half4": ...

        @property
        def babb(self)->"half4": ...

        @property
        def baba(self)->"half4": ...

        @property
        def baar(self)->"half4": ...

        @property
        def baag(self)->"half4": ...

        @property
        def baab(self)->"half4": ...

        @property
        def baaa(self)->"half4": ...

        @property
        def arrr(self)->"half4": ...

        @property
        def arrg(self)->"half4": ...

        @property
        def arrb(self)->"half4": ...

        @property
        def arra(self)->"half4": ...

        @property
        def argr(self)->"half4": ...

        @property
        def argg(self)->"half4": ...

        @property
        def argb(self)->"half4": ...

        @argb.setter
        def argb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arga(self)->"half4": ...

        @property
        def arbr(self)->"half4": ...

        @property
        def arbg(self)->"half4": ...

        @arbg.setter
        def arbg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def arbb(self)->"half4": ...

        @property
        def arba(self)->"half4": ...

        @property
        def arar(self)->"half4": ...

        @property
        def arag(self)->"half4": ...

        @property
        def arab(self)->"half4": ...

        @property
        def araa(self)->"half4": ...

        @property
        def agrr(self)->"half4": ...

        @property
        def agrg(self)->"half4": ...

        @property
        def agrb(self)->"half4": ...

        @agrb.setter
        def agrb(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agra(self)->"half4": ...

        @property
        def aggr(self)->"half4": ...

        @property
        def aggg(self)->"half4": ...

        @property
        def aggb(self)->"half4": ...

        @property
        def agga(self)->"half4": ...

        @property
        def agbr(self)->"half4": ...

        @agbr.setter
        def agbr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def agbg(self)->"half4": ...

        @property
        def agbb(self)->"half4": ...

        @property
        def agba(self)->"half4": ...

        @property
        def agar(self)->"half4": ...

        @property
        def agag(self)->"half4": ...

        @property
        def agab(self)->"half4": ...

        @property
        def agaa(self)->"half4": ...

        @property
        def abrr(self)->"half4": ...

        @property
        def abrg(self)->"half4": ...

        @abrg.setter
        def abrg(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abrb(self)->"half4": ...

        @property
        def abra(self)->"half4": ...

        @property
        def abgr(self)->"half4": ...

        @abgr.setter
        def abgr(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def abgg(self)->"half4": ...

        @property
        def abgb(self)->"half4": ...

        @property
        def abga(self)->"half4": ...

        @property
        def abbr(self)->"half4": ...

        @property
        def abbg(self)->"half4": ...

        @property
        def abbb(self)->"half4": ...

        @property
        def abba(self)->"half4": ...

        @property
        def abar(self)->"half4": ...

        @property
        def abag(self)->"half4": ...

        @property
        def abab(self)->"half4": ...

        @property
        def abaa(self)->"half4": ...

        @property
        def aarr(self)->"half4": ...

        @property
        def aarg(self)->"half4": ...

        @property
        def aarb(self)->"half4": ...

        @property
        def aara(self)->"half4": ...

        @property
        def aagr(self)->"half4": ...

        @property
        def aagg(self)->"half4": ...

        @property
        def aagb(self)->"half4": ...

        @property
        def aaga(self)->"half4": ...

        @property
        def aabr(self)->"half4": ...

        @property
        def aabg(self)->"half4": ...

        @property
        def aabb(self)->"half4": ...

        @property
        def aaba(self)->"half4": ...

        @property
        def aaar(self)->"half4": ...

        @property
        def aaag(self)->"half4": ...

        @property
        def aaab(self)->"half4": ...

        @property
        def aaaa(self)->"half4": ...

        @property
        def s(self)->float: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->float: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def p(self)->float: ...

        @p.setter
        def p(self, value:Union[bool, int, float])->None: ...

        @property
        def q(self)->float: ...

        @q.setter
        def q(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->half2: ...

        @property
        def st(self)->half2: ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sp(self)->half2: ...

        @sp.setter
        def sp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sq(self)->half2: ...

        @sq.setter
        def sq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->half2: ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->half2: ...

        @property
        def tp(self)->half2: ...

        @tp.setter
        def tp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tq(self)->half2: ...

        @tq.setter
        def tq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ps(self)->half2: ...

        @ps.setter
        def ps(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pt(self)->half2: ...

        @pt.setter
        def pt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pp(self)->half2: ...

        @property
        def pq(self)->half2: ...

        @pq.setter
        def pq(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qs(self)->half2: ...

        @qs.setter
        def qs(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qt(self)->half2: ...

        @qt.setter
        def qt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qp(self)->half2: ...

        @qp.setter
        def qp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def qq(self)->half2: ...

        @property
        def sss(self)->half3: ...

        @property
        def sst(self)->half3: ...

        @property
        def ssp(self)->half3: ...

        @property
        def ssq(self)->half3: ...

        @property
        def sts(self)->half3: ...

        @property
        def stt(self)->half3: ...

        @property
        def stp(self)->half3: ...

        @stp.setter
        def stp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def stq(self)->half3: ...

        @stq.setter
        def stq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sps(self)->half3: ...

        @property
        def spt(self)->half3: ...

        @spt.setter
        def spt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def spp(self)->half3: ...

        @property
        def spq(self)->half3: ...

        @spq.setter
        def spq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqs(self)->half3: ...

        @property
        def sqt(self)->half3: ...

        @sqt.setter
        def sqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqp(self)->half3: ...

        @sqp.setter
        def sqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sqq(self)->half3: ...

        @property
        def tss(self)->half3: ...

        @property
        def tst(self)->half3: ...

        @property
        def tsp(self)->half3: ...

        @tsp.setter
        def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tsq(self)->half3: ...

        @tsq.setter
        def tsq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tts(self)->half3: ...

        @property
        def ttt(self)->half3: ...

        @property
        def ttp(self)->half3: ...

        @property
        def ttq(self)->half3: ...

        @property
        def tps(self)->half3: ...

        @tps.setter
        def tps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tpt(self)->half3: ...

        @property
        def tpp(self)->half3: ...

        @property
        def tpq(self)->half3: ...

        @tpq.setter
        def tpq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqs(self)->half3: ...

        @tqs.setter
        def tqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqt(self)->half3: ...

        @property
        def tqp(self)->half3: ...

        @tqp.setter
        def tqp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tqq(self)->half3: ...

        @property
        def pss(self)->half3: ...

        @property
        def pst(self)->half3: ...

        @pst.setter
        def pst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def psp(self)->half3: ...

        @property
        def psq(self)->half3: ...

        @psq.setter
        def psq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pts(self)->half3: ...

        @pts.setter
        def pts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ptt(self)->half3: ...

        @property
        def ptp(self)->half3: ...

        @property
        def ptq(self)->half3: ...

        @ptq.setter
        def ptq(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pps(self)->half3: ...

        @property
        def ppt(self)->half3: ...

        @property
        def ppp(self)->half3: ...

        @property
        def ppq(self)->half3: ...

        @property
        def pqs(self)->half3: ...

        @pqs.setter
        def pqs(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqt(self)->half3: ...

        @pqt.setter
        def pqt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def pqp(self)->half3: ...

        @property
        def pqq(self)->half3: ...

        @property
        def qss(self)->half3: ...

        @property
        def qst(self)->half3: ...

        @qst.setter
        def qst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsp(self)->half3: ...

        @qsp.setter
        def qsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qsq(self)->half3: ...

        @property
        def qts(self)->half3: ...

        @qts.setter
        def qts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtt(self)->half3: ...

        @property
        def qtp(self)->half3: ...

        @qtp.setter
        def qtp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qtq(self)->half3: ...

        @property
        def qps(self)->half3: ...

        @qps.setter
        def qps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpt(self)->half3: ...

        @qpt.setter
        def qpt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def qpp(self)->half3: ...

        @property
        def qpq(self)->half3: ...

        @property
        def qqs(self)->half3: ...

        @property
        def qqt(self)->half3: ...

        @property
        def qqp(self)->half3: ...

        @property
        def qqq(self)->half3: ...

        @property
        def ssss(self)->"half4": ...

        @property
        def ssst(self)->"half4": ...

        @property
        def sssp(self)->"half4": ...

        @property
        def sssq(self)->"half4": ...

        @property
        def ssts(self)->"half4": ...

        @property
        def sstt(self)->"half4": ...

        @property
        def sstp(self)->"half4": ...

        @property
        def sstq(self)->"half4": ...

        @property
        def ssps(self)->"half4": ...

        @property
        def sspt(self)->"half4": ...

        @property
        def sspp(self)->"half4": ...

        @property
        def sspq(self)->"half4": ...

        @property
        def ssqs(self)->"half4": ...

        @property
        def ssqt(self)->"half4": ...

        @property
        def ssqp(self)->"half4": ...

        @property
        def ssqq(self)->"half4": ...

        @property
        def stss(self)->"half4": ...

        @property
        def stst(self)->"half4": ...

        @property
        def stsp(self)->"half4": ...

        @property
        def stsq(self)->"half4": ...

        @property
        def stts(self)->"half4": ...

        @property
        def sttt(self)->"half4": ...

        @property
        def sttp(self)->"half4": ...

        @property
        def sttq(self)->"half4": ...

        @property
        def stps(self)->"half4": ...

        @property
        def stpt(self)->"half4": ...

        @property
        def stpp(self)->"half4": ...

        @property
        def stpq(self)->"half4": ...

        @stpq.setter
        def stpq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqs(self)->"half4": ...

        @property
        def stqt(self)->"half4": ...

        @property
        def stqp(self)->"half4": ...

        @stqp.setter
        def stqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def stqq(self)->"half4": ...

        @property
        def spss(self)->"half4": ...

        @property
        def spst(self)->"half4": ...

        @property
        def spsp(self)->"half4": ...

        @property
        def spsq(self)->"half4": ...

        @property
        def spts(self)->"half4": ...

        @property
        def sptt(self)->"half4": ...

        @property
        def sptp(self)->"half4": ...

        @property
        def sptq(self)->"half4": ...

        @sptq.setter
        def sptq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spps(self)->"half4": ...

        @property
        def sppt(self)->"half4": ...

        @property
        def sppp(self)->"half4": ...

        @property
        def sppq(self)->"half4": ...

        @property
        def spqs(self)->"half4": ...

        @property
        def spqt(self)->"half4": ...

        @spqt.setter
        def spqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def spqp(self)->"half4": ...

        @property
        def spqq(self)->"half4": ...

        @property
        def sqss(self)->"half4": ...

        @property
        def sqst(self)->"half4": ...

        @property
        def sqsp(self)->"half4": ...

        @property
        def sqsq(self)->"half4": ...

        @property
        def sqts(self)->"half4": ...

        @property
        def sqtt(self)->"half4": ...

        @property
        def sqtp(self)->"half4": ...

        @sqtp.setter
        def sqtp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqtq(self)->"half4": ...

        @property
        def sqps(self)->"half4": ...

        @property
        def sqpt(self)->"half4": ...

        @sqpt.setter
        def sqpt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def sqpp(self)->"half4": ...

        @property
        def sqpq(self)->"half4": ...

        @property
        def sqqs(self)->"half4": ...

        @property
        def sqqt(self)->"half4": ...

        @property
        def sqqp(self)->"half4": ...

        @property
        def sqqq(self)->"half4": ...

        @property
        def tsss(self)->"half4": ...

        @property
        def tsst(self)->"half4": ...

        @property
        def tssp(self)->"half4": ...

        @property
        def tssq(self)->"half4": ...

        @property
        def tsts(self)->"half4": ...

        @property
        def tstt(self)->"half4": ...

        @property
        def tstp(self)->"half4": ...

        @property
        def tstq(self)->"half4": ...

        @property
        def tsps(self)->"half4": ...

        @property
        def tspt(self)->"half4": ...

        @property
        def tspp(self)->"half4": ...

        @property
        def tspq(self)->"half4": ...

        @tspq.setter
        def tspq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqs(self)->"half4": ...

        @property
        def tsqt(self)->"half4": ...

        @property
        def tsqp(self)->"half4": ...

        @tsqp.setter
        def tsqp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tsqq(self)->"half4": ...

        @property
        def ttss(self)->"half4": ...

        @property
        def ttst(self)->"half4": ...

        @property
        def ttsp(self)->"half4": ...

        @property
        def ttsq(self)->"half4": ...

        @property
        def ttts(self)->"half4": ...

        @property
        def tttt(self)->"half4": ...

        @property
        def tttp(self)->"half4": ...

        @property
        def tttq(self)->"half4": ...

        @property
        def ttps(self)->"half4": ...

        @property
        def ttpt(self)->"half4": ...

        @property
        def ttpp(self)->"half4": ...

        @property
        def ttpq(self)->"half4": ...

        @property
        def ttqs(self)->"half4": ...

        @property
        def ttqt(self)->"half4": ...

        @property
        def ttqp(self)->"half4": ...

        @property
        def ttqq(self)->"half4": ...

        @property
        def tpss(self)->"half4": ...

        @property
        def tpst(self)->"half4": ...

        @property
        def tpsp(self)->"half4": ...

        @property
        def tpsq(self)->"half4": ...

        @tpsq.setter
        def tpsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpts(self)->"half4": ...

        @property
        def tptt(self)->"half4": ...

        @property
        def tptp(self)->"half4": ...

        @property
        def tptq(self)->"half4": ...

        @property
        def tpps(self)->"half4": ...

        @property
        def tppt(self)->"half4": ...

        @property
        def tppp(self)->"half4": ...

        @property
        def tppq(self)->"half4": ...

        @property
        def tpqs(self)->"half4": ...

        @tpqs.setter
        def tpqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tpqt(self)->"half4": ...

        @property
        def tpqp(self)->"half4": ...

        @property
        def tpqq(self)->"half4": ...

        @property
        def tqss(self)->"half4": ...

        @property
        def tqst(self)->"half4": ...

        @property
        def tqsp(self)->"half4": ...

        @tqsp.setter
        def tqsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqsq(self)->"half4": ...

        @property
        def tqts(self)->"half4": ...

        @property
        def tqtt(self)->"half4": ...

        @property
        def tqtp(self)->"half4": ...

        @property
        def tqtq(self)->"half4": ...

        @property
        def tqps(self)->"half4": ...

        @tqps.setter
        def tqps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def tqpt(self)->"half4": ...

        @property
        def tqpp(self)->"half4": ...

        @property
        def tqpq(self)->"half4": ...

        @property
        def tqqs(self)->"half4": ...

        @property
        def tqqt(self)->"half4": ...

        @property
        def tqqp(self)->"half4": ...

        @property
        def tqqq(self)->"half4": ...

        @property
        def psss(self)->"half4": ...

        @property
        def psst(self)->"half4": ...

        @property
        def pssp(self)->"half4": ...

        @property
        def pssq(self)->"half4": ...

        @property
        def psts(self)->"half4": ...

        @property
        def pstt(self)->"half4": ...

        @property
        def pstp(self)->"half4": ...

        @property
        def pstq(self)->"half4": ...

        @pstq.setter
        def pstq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psps(self)->"half4": ...

        @property
        def pspt(self)->"half4": ...

        @property
        def pspp(self)->"half4": ...

        @property
        def pspq(self)->"half4": ...

        @property
        def psqs(self)->"half4": ...

        @property
        def psqt(self)->"half4": ...

        @psqt.setter
        def psqt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def psqp(self)->"half4": ...

        @property
        def psqq(self)->"half4": ...

        @property
        def ptss(self)->"half4": ...

        @property
        def ptst(self)->"half4": ...

        @property
        def ptsp(self)->"half4": ...

        @property
        def ptsq(self)->"half4": ...

        @ptsq.setter
        def ptsq(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptts(self)->"half4": ...

        @property
        def pttt(self)->"half4": ...

        @property
        def pttp(self)->"half4": ...

        @property
        def pttq(self)->"half4": ...

        @property
        def ptps(self)->"half4": ...

        @property
        def ptpt(self)->"half4": ...

        @property
        def ptpp(self)->"half4": ...

        @property
        def ptpq(self)->"half4": ...

        @property
        def ptqs(self)->"half4": ...

        @ptqs.setter
        def ptqs(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def ptqt(self)->"half4": ...

        @property
        def ptqp(self)->"half4": ...

        @property
        def ptqq(self)->"half4": ...

        @property
        def ppss(self)->"half4": ...

        @property
        def ppst(self)->"half4": ...

        @property
        def ppsp(self)->"half4": ...

        @property
        def ppsq(self)->"half4": ...

        @property
        def ppts(self)->"half4": ...

        @property
        def pptt(self)->"half4": ...

        @property
        def pptp(self)->"half4": ...

        @property
        def pptq(self)->"half4": ...

        @property
        def ppps(self)->"half4": ...

        @property
        def pppt(self)->"half4": ...

        @property
        def pppp(self)->"half4": ...

        @property
        def pppq(self)->"half4": ...

        @property
        def ppqs(self)->"half4": ...

        @property
        def ppqt(self)->"half4": ...

        @property
        def ppqp(self)->"half4": ...

        @property
        def ppqq(self)->"half4": ...

        @property
        def pqss(self)->"half4": ...

        @property
        def pqst(self)->"half4": ...

        @pqst.setter
        def pqst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqsp(self)->"half4": ...

        @property
        def pqsq(self)->"half4": ...

        @property
        def pqts(self)->"half4": ...

        @pqts.setter
        def pqts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def pqtt(self)->"half4": ...

        @property
        def pqtp(self)->"half4": ...

        @property
        def pqtq(self)->"half4": ...

        @property
        def pqps(self)->"half4": ...

        @property
        def pqpt(self)->"half4": ...

        @property
        def pqpp(self)->"half4": ...

        @property
        def pqpq(self)->"half4": ...

        @property
        def pqqs(self)->"half4": ...

        @property
        def pqqt(self)->"half4": ...

        @property
        def pqqp(self)->"half4": ...

        @property
        def pqqq(self)->"half4": ...

        @property
        def qsss(self)->"half4": ...

        @property
        def qsst(self)->"half4": ...

        @property
        def qssp(self)->"half4": ...

        @property
        def qssq(self)->"half4": ...

        @property
        def qsts(self)->"half4": ...

        @property
        def qstt(self)->"half4": ...

        @property
        def qstp(self)->"half4": ...

        @qstp.setter
        def qstp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qstq(self)->"half4": ...

        @property
        def qsps(self)->"half4": ...

        @property
        def qspt(self)->"half4": ...

        @qspt.setter
        def qspt(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qspp(self)->"half4": ...

        @property
        def qspq(self)->"half4": ...

        @property
        def qsqs(self)->"half4": ...

        @property
        def qsqt(self)->"half4": ...

        @property
        def qsqp(self)->"half4": ...

        @property
        def qsqq(self)->"half4": ...

        @property
        def qtss(self)->"half4": ...

        @property
        def qtst(self)->"half4": ...

        @property
        def qtsp(self)->"half4": ...

        @qtsp.setter
        def qtsp(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtsq(self)->"half4": ...

        @property
        def qtts(self)->"half4": ...

        @property
        def qttt(self)->"half4": ...

        @property
        def qttp(self)->"half4": ...

        @property
        def qttq(self)->"half4": ...

        @property
        def qtps(self)->"half4": ...

        @qtps.setter
        def qtps(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qtpt(self)->"half4": ...

        @property
        def qtpp(self)->"half4": ...

        @property
        def qtpq(self)->"half4": ...

        @property
        def qtqs(self)->"half4": ...

        @property
        def qtqt(self)->"half4": ...

        @property
        def qtqp(self)->"half4": ...

        @property
        def qtqq(self)->"half4": ...

        @property
        def qpss(self)->"half4": ...

        @property
        def qpst(self)->"half4": ...

        @qpst.setter
        def qpst(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qpsp(self)->"half4": ...

        @property
        def qpsq(self)->"half4": ...

        @property
        def qpts(self)->"half4": ...

        @qpts.setter
        def qpts(self, value:Union[bool, int, float, genVec4])->None: ...

        @property
        def qptt(self)->"half4": ...

        @property
        def qptp(self)->"half4": ...

        @property
        def qptq(self)->"half4": ...

        @property
        def qpps(self)->"half4": ...

        @property
        def qppt(self)->"half4": ...

        @property
        def qppp(self)->"half4": ...

        @property
        def qppq(self)->"half4": ...

        @property
        def qpqs(self)->"half4": ...

        @property
        def qpqt(self)->"half4": ...

        @property
        def qpqp(self)->"half4": ...

        @property
        def qpqq(self)->"half4": ...

        @property
        def qqss(self)->"half4": ...

        @property
        def qqst(self)->"half4": ...

        @property
        def qqsp(self)->"half4": ...

        @property
        def qqsq(self)->"half4": ...

        @property
        def qqts(self)->"half4": ...

        @property
        def qqtt(self)->"half4": ...

        @property
        def qqtp(self)->"half4": ...

        @property
        def qqtq(self)->"half4": ...

        @property
        def qqps(self)->"half4": ...

        @property
        def qqpt(self)->"half4": ...

        @property
        def qqpp(self)->"half4": ...

        @property
        def qqpq(self)->"half4": ...

        @property
        def qqqs(self)->"half4": ...

        @property
        def qqqt(self)->"half4": ...

        @property
        def qqqp(self)->"half4": ...

        @property
        def qqqq(self)->"half4": ...
        # --- END generated swizzles ---
