import ctypes
from typing import TYPE_CHECKING, Union

from .genVec2 import genVec2

if TYPE_CHECKING:

    from .int3 import int3
    from .int4 import int4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class int2(genVec2):

    _fields_ = [
        ('x', ctypes.c_int),
        ('y', ctypes.c_int)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_int

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->int: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->int: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->"int2": ...

        @property
        def xy(self)->"int2": ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->"int2": ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->"int2": ...

        @property
        def xxx(self)->int3: ...

        @property
        def xxy(self)->int3: ...

        @property
        def xyx(self)->int3: ...

        @property
        def xyy(self)->int3: ...

        @property
        def yxx(self)->int3: ...

        @property
        def yxy(self)->int3: ...

        @property
        def yyx(self)->int3: ...

        @property
        def yyy(self)->int3: ...

        @property
        def xxxx(self)->int4: ...

        @property
        def xxxy(self)->int4: ...

        @property
        def xxyx(self)->int4: ...

        @property
        def xxyy(self)->int4: ...

        @property
        def xyxx(self)->int4: ...

        @property
        def xyxy(self)->int4: ...

        @property
        def xyyx(self)->int4: ...

        @property
        def xyyy(self)->int4: ...

        @property
        def yxxx(self)->int4: ...

        @property
        def yxxy(self)->int4: ...

        @property
        def yxyx(self)->int4: ...

        @property
        def yxyy(self)->int4: ...

        @property
        def yyxx(self)->int4: ...

        @property
        def yyxy(self)->int4: ...

        @property
        def yyyx(self)->int4: ...

        @property
        def yyyy(self)->int4: ...

        @property
        def r(self)->int: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->int: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->"int2": ...

        @property
        def rg(self)->"int2": ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->"int2": ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->"int2": ...

        @property
        def rrr(self)->int3: ...

        @property
        def rrg(self)->int3: ...

        @property
        def rgr(self)->int3: ...

        @property
        def rgg(self)->int3: ...

        @property
        def grr(self)->int3: ...

        @property
        def grg(self)->int3: ...

        @property
        def ggr(self)->int3: ...

        @property
        def ggg(self)->int3: ...

        @property
        def rrrr(self)->int4: ...

        @property
        def rrrg(self)->int4: ...

        @property
        def rrgr(self)->int4: ...

        @property
        def rrgg(self)->int4: ...

        @property
        def rgrr(self)->int4: ...

        @property
        def rgrg(self)->int4: ...

        @property
        def rggr(self)->int4: ...

        @property
        def rggg(self)->int4: ...

        @property
        def grrr(self)->int4: ...

        @property
        def grrg(self)->int4: ...

        @property
        def grgr(self)->int4: ...

        @property
        def grgg(self)->int4: ...

        @property
        def ggrr(self)->int4: ...

        @property
        def ggrg(self)->int4: ...

        @property
        def gggr(self)->int4: ...

        @property
        def gggg(self)->int4: ...

        @property
        def s(self)->int: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->int: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->"int2": ...

        @property
        def st(self)->"int2": ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->"int2": ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->"int2": ...

        @property
        def sss(self)->int3: ...

        @property
        def sst(self)->int3: ...

        @property
        def sts(self)->int3: ...

        @property
        def stt(self)->int3: ...

        @property
        def tss(self)->int3: ...

        @property
        def tst(self)->int3: ...

        @property
        def tts(self)->int3: ...

        @property
        def ttt(self)->int3: ...

        @property
        def ssss(self)->int4: ...

        @property
        def ssst(self)->int4: ...

        @property
        def ssts(self)->int4: ...

        @property
        def sstt(self)->int4: ...

        @property
        def stss(self)->int4: ...

        @property
        def stst(self)->int4: ...

        @property
        def stts(self)->int4: ...

        @property
        def sttt(self)->int4: ...

        @property
        def tsss(self)->int4: ...

        @property
        def tsst(self)->int4: ...

        @property
        def tsts(self)->int4: ...

        @property
        def tstt(self)->int4: ...

        @property
        def ttss(self)->int4: ...

        @property
        def ttst(self)->int4: ...

        @property
        def ttts(self)->int4: ...

        @property
        def tttt(self)->int4: ...
        # --- END generated swizzles ---
