import ctypes
from typing import TYPE_CHECKING, Union

from .genVec3 import genVec3

if TYPE_CHECKING:

    from .genVec2 import genVec2
    from .int2 import int2
    from .int4 import int4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class int3(genVec3):

    _fields_ = [
        ('x', ctypes.c_int),
        ('y', ctypes.c_int),
        ('z', ctypes.c_int)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_int

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->int: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->int: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def z(self)->int: ...

        @z.setter
        def z(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->int2: ...

        @property
        def xy(self)->int2: ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def xz(self)->int2: ...

        @xz.setter
        def xz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->int2: ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->int2: ...

        @property
        def yz(self)->int2: ...

        @yz.setter
        def yz(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zx(self)->int2: ...

        @zx.setter
        def zx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zy(self)->int2: ...

        @zy.setter
        def zy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def zz(self)->int2: ...

        @property
        def xxx(self)->"int3": ...

        @property
        def xxy(self)->"int3": ...

        @property
        def xxz(self)->"int3": ...

        @property
        def xyx(self)->"int3": ...

        @property
        def xyy(self)->"int3": ...

        @property
        def xyz(self)->"int3": ...

        @xyz.setter
        def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzx(self)->"int3": ...

        @property
        def xzy(self)->"int3": ...

        @xzy.setter
        def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def xzz(self)->"int3": ...

        @property
        def yxx(self)->"int3": ...

        @property
        def yxy(self)->"int3": ...

        @property
        def yxz(self)->"int3": ...

        @yxz.setter
        def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yyx(self)->"int3": ...

        @property
        def yyy(self)->"int3": ...

        @property
        def yyz(self)->"int3": ...

        @property
        def yzx(self)->"int3": ...

        @yzx.setter
        def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def yzy(self)->"int3": ...

        @property
        def yzz(self)->"int3": ...

        @property
        def zxx(self)->"int3": ...

        @property
        def zxy(self)->"int3": ...

        @zxy.setter
        def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zxz(self)->"int3": ...

        @property
        def zyx(self)->"int3": ...

        @zyx.setter
        def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def zyy(self)->"int3": ...

        @property
        def zyz(self)->"int3": ...

        @property
        def zzx(self)->"int3": ...

        @property
        def zzy(self)->"int3": ...

        @property
        def zzz(self)->"int3": ...

        @property
        def xxxx(self)->int4: ...

        @property
        def xxxy(self)->int4: ...

        @property
        def xxxz(self)->int4: ...

        @property
        def xxyx(self)->int4: ...

        @property
        def xxyy(self)->int4: ...

        @property
        def xxyz(self)->int4: ...

        @property
        def xxzx(self)->int4: ...

        @property
        def xxzy(self)->int4: ...

        @property
        def xxzz(self)->int4: ...

        @property
        def xyxx(self)->int4: ...

        @property
        def xyxy(self)->int4: ...

        @property
        def xyxz(self)->int4: ...

        @property
        def xyyx(self)->int4: ...

        @property
        def xyyy(self)->int4: ...

        @property
        def xyyz(self)->int4: ...

        @property
        def xyzx(self)->int4: ...

        @property
        def xyzy(self)->int4: ...

        @property
        def xyzz(self)->int4: ...

        @property
        def xzxx(self)->int4: ...

        @property
        def xzxy(self)->int4: ...

        @property
        def xzxz(self)->int4: ...

        @property
        def xzyx(self)->int4: ...

        @property
        def xzyy(self)->int4: ...

        @property
        def xzyz(self)->int4: ...

        @property
        def xzzx(self)->int4: ...

        @property
        def xzzy(self)->int4: ...

        @property
        def xzzz(self)->int4: ...

        @property
        def yxxx(self)->int4: ...

        @property
        def yxxy(self)->int4: ...

        @property
        def yxxz(self)->int4: ...

        @property
        def yxyx(self)->int4: ...

        @property
        def yxyy(self)->int4: ...

        @property
        def yxyz(self)->int4: ...

        @property
        def yxzx(self)->int4: ...

        @property
        def yxzy(self)->int4: ...

        @property
        def yxzz(self)->int4: ...

        @property
        def yyxx(self)->int4: ...

        @property
        def yyxy(self)->int4: ...

        @property
        def yyxz(self)->int4: ...

        @property
        def yyyx(self)->int4: ...

        @property
        def yyyy(self)->int4: ...

        @property
        def yyyz(self)->int4: ...

        @property
        def yyzx(self)->int4: ...

        @property
        def yyzy(self)->int4: ...

        @property
        def yyzz(self)->int4: ...

        @property
        def yzxx(self)->int4: ...

        @property
        def yzxy(self)->int4: ...

        @property
        def yzxz(self)->int4: ...

        @property
        def yzyx(self)->int4: ...

        @property
        def yzyy(self)->int4: ...

        @property
        def yzyz(self)->int4: ...

        @property
        def yzzx(self)->int4: ...

        @property
        def yzzy(self)->int4: ...

        @property
        def yzzz(self)->int4: ...

        @property
        def zxxx(self)->int4: ...

        @property
        def zxxy(self)->int4: ...

        @property
        def zxxz(self)->int4: ...

        @property
        def zxyx(self)->int4: ...

        @property
        def zxyy(self)->int4: ...

        @property
        def zxyz(self)->int4: ...

        @property
        def zxzx(self)->int4: ...

        @property
        def zxzy(self)->int4: ...

        @property
        def zxzz(self)->int4: ...

        @property
        def zyxx(self)->int4: ...

        @property
        def zyxy(self)->int4: ...

        @property
        def zyxz(self)->int4: ...

        @property
        def zyyx(self)->int4: ...

        @property
        def zyyy(self)->int4: ...

        @property
        def zyyz(self)->int4: ...

        @property
        def zyzx(self)->int4: ...

        @property
        def zyzy(self)->int4: ...

        @property
        def zyzz(self)->int4: ...

        @property
        def zzxx(self)->int4: ...

        @property
        def zzxy(self)->int4: ...

        @property
        def zzxz(self)->int4: ...

        @property
        def zzyx(self)->int4: ...

        @property
        def zzyy(self)->int4: ...

        @property
        def zzyz(self)->int4: ...

        @property
        def zzzx(self)->int4: ...

        @property
        def zzzy(self)->int4: ...

        @property
        def zzzz(self)->int4: ...

        @property
        def r(self)->int: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->int: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def b(self)->int: ...

        @b.setter
        def b(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->int2: ...

        @property
        def rg(self)->int2: ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def rb(self)->int2: ...

        @rb.setter
        def rb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->int2: ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->int2: ...

        @property
        def gb(self)->int2: ...

        @gb.setter
        def gb(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def br(self)->int2: ...

        @br.setter
        def br(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bg(self)->int2: ...

        @bg.setter
        def bg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def bb(self)->int2: ...

        @property
        def rrr(self)->"int3": ...

        @property
        def rrg(self)->"int3": ...

        @property
        def rrb(self)->"int3": ...

        @property
        def rgr(self)->"int3": ...

        @property
        def rgg(self)->"int3": ...

        @property
        def rgb(self)->"int3": ...

        @rgb.setter
        def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbr(self)->"int3": ...

        @property
        def rbg(self)->"int3": ...

        @rbg.setter
        def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def rbb(self)->"int3": ...

        @property
        def grr(self)->"int3": ...

        @property
        def grg(self)->"int3": ...

        @property
        def grb(self)->"int3": ...

        @grb.setter
        def grb(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ggr(self)->"int3": ...

        @property
        def ggg(self)->"int3": ...

        @property
        def ggb(self)->"int3": ...

        @property
        def gbr(self)->"int3": ...

        @gbr.setter
        def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def gbg(self)->"int3": ...

        @property
        def gbb(self)->"int3": ...

        @property
        def brr(self)->"int3": ...

        @property
        def brg(self)->"int3": ...

        @brg.setter
        def brg(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def brb(self)->"int3": ...

        @property
        def bgr(self)->"int3": ...

        @bgr.setter
        def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def bgg(self)->"int3": ...

        @property
        def bgb(self)->"int3": ...

        @property
        def bbr(self)->"int3": ...

        @property
        def bbg(self)->"int3": ...

        @property
        def bbb(self)->"int3": ...

        @property
        def rrrr(self)->int4: ...

        @property
        def rrrg(self)->int4: ...

        @property
        def rrrb(self)->int4: ...

        @property
        def rrgr(self)->int4: ...

        @property
        def rrgg(self)->int4: ...

        @property
        def rrgb(self)->int4: ...

        @property
        def rrbr(self)->int4: ...

        @property
        def rrbg(self)->int4: ...

        @property
        def rrbb(self)->int4: ...

        @property
        def rgrr(self)->int4: ...

        @property
        def rgrg(self)->int4: ...

        @property
        def rgrb(self)->int4: ...

        @property
        def rggr(self)->int4: ...

        @property
        def rggg(self)->int4: ...

        @property
        def rggb(self)->int4: ...

        @property
        def rgbr(self)->int4: ...

        @property
        def rgbg(self)->int4: ...

        @property
        def rgbb(self)->int4: ...

        @property
        def rbrr(self)->int4: ...

        @property
        def rbrg(self)->int4: ...

        @property
        def rbrb(self)->int4: ...

        @property
        def rbgr(self)->int4: ...

        @property
        def rbgg(self)->int4: ...

        @property
        def rbgb(self)->int4: ...

        @property
        def rbbr(self)->int4: ...

        @property
        def rbbg(self)->int4: ...

        @property
        def rbbb(self)->int4: ...

        @property
        def grrr(self)->int4: ...

        @property
        def grrg(self)->int4: ...

        @property
        def grrb(self)->int4: ...

        @property
        def grgr(self)->int4: ...

        @property
        def grgg(self)->int4: ...

        @property
        def grgb(self)->int4: ...

        @property
        def grbr(self)->int4: ...

        @property
        def grbg(self)->int4: ...

        @property
        def grbb(self)->int4: ...

        @property
        def ggrr(self)->int4: ...

        @property
        def ggrg(self)->int4: ...

        @property
        def ggrb(self)->int4: ...

        @property
        def gggr(self)->int4: ...

        @property
        def gggg(self)->int4: ...

        @property
        def gggb(self)->int4: ...

        @property
        def ggbr(self)->int4: ...

        @property
        def ggbg(self)->int4: ...

        @property
        def ggbb(self)->int4: ...

        @property
        def gbrr(self)->int4: ...

        @property
        def gbrg(self)->int4: ...

        @property
        def gbrb(self)->int4: ...

        @property
        def gbgr(self)->int4: ...

        @property
        def gbgg(self)->int4: ...

        @property
        def gbgb(self)->int4: ...

        @property
        def gbbr(self)->int4: ...

        @property
        def gbbg(self)->int4: ...

        @property
        def gbbb(self)->int4: ...

        @property
        def brrr(self)->int4: ...

        @property
        def brrg(self)->int4: ...

        @property
        def brrb(self)->int4: ...

        @property
        def brgr(self)->int4: ...

        @property
        def brgg(self)->int4: ...

        @property
        def brgb(self)->int4: ...

        @property
        def brbr(self)->int4: ...

        @property
        def brbg(self)->int4: ...

        @property
        def brbb(self)->int4: ...

        @property
        def bgrr(self)->int4: ...

        @property
        def bgrg(self)->int4: ...

        @property
        def bgrb(self)->int4: ...

        @property
        def bggr(self)->int4: ...

        @property
        def bggg(self)->int4: ...

        @property
        def bggb(self)->int4: ...

        @property
        def bgbr(self)->int4: ...

        @property
        def bgbg(self)->int4: ...

        @property
        def bgbb(self)->int4: ...

        @property
        def bbrr(self)->int4: ...

        @property
        def bbrg(self)->int4: ...

        @property
        def bbrb(self)->int4: ...

        @property
        def bbgr(self)->int4: ...

        @property
        def bbgg(self)->int4: ...

        @property
        def bbgb(self)->int4: ...

        @property
        def bbbr(self)->int4: ...

        @property
        def bbbg(self)->int4: ...

        @property
        def bbbb(self)->int4: ...

        @property
        def s(self)->int: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->int: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def p(self)->int: ...

        @p.setter
        def p(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->int2: ...

        @property
        def st(self)->int2: ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def sp(self)->int2: ...

        @sp.setter
        def sp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->int2: ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->int2: ...

        @property
        def tp(self)->int2: ...

        @tp.setter
        def tp(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ps(self)->int2: ...

        @ps.setter
        def ps(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pt(self)->int2: ...

        @pt.setter
        def pt(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def pp(self)->int2: ...

        @property
        def sss(self)->"int3": ...

        @property
        def sst(self)->"int3": ...

        @property
        def ssp(self)->"int3": ...

        @property
        def sts(self)->"int3": ...

        @property
        def stt(self)->"int3": ...

        @property
        def stp(self)->"int3": ...

        @stp.setter
        def stp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def sps(self)->"int3": ...

        @property
        def spt(self)->"int3": ...

        @spt.setter
        def spt(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def spp(self)->"int3": ...

        @property
        def tss(self)->"int3": ...

        @property
        def tst(self)->"int3": ...

        @property
        def tsp(self)->"int3": ...

        @tsp.setter
        def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tts(self)->"int3": ...

        @property
        def ttt(self)->"int3": ...

        @property
        def ttp(self)->"int3": ...

        @property
        def tps(self)->"int3": ...

        @tps.setter
        def tps(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def tpt(self)->"int3": ...

        @property
        def tpp(self)->"int3": ...

        @property
        def pss(self)->"int3": ...

        @property
        def pst(self)->"int3": ...

        @pst.setter
        def pst(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def psp(self)->"int3": ...

        @property
        def pts(self)->"int3": ...

        @pts.setter
        def pts(self, value:Union[bool, int, float, genVec3])->None: ...

        @property
        def ptt(self)->"int3": ...

        @property
        def ptp(self)->"int3": ...

        @property
        def pps(self)->"int3": ...

        @property
        def ppt(self)->"int3": ...

        @property
        def ppp(self)->"int3": ...

        @property
        def ssss(self)->int4: ...

        @property
        def ssst(self)->int4: ...

        @property
        def sssp(self)->int4: ...

        @property
        def ssts(self)->int4: ...

        @property
        def sstt(self)->int4: ...

        @property
        def sstp(self)->int4: ...

        @property
        def ssps(self)->int4: ...

        @property
        def sspt(self)->int4: ...

        @property
        def sspp(self)->int4: ...

        @property
        def stss(self)->int4: ...

        @property
        def stst(self)->int4: ...

        @property
        def stsp(self)->int4: ...

        @property
        def stts(self)->int4: ...

        @property
        def sttt(self)->int4: ...

        @property
        def sttp(self)->int4: ...

        @property
        def stps(self)->int4: ...

        @property
        def stpt(self)->int4: ...

        @property
        def stpp(self)->int4: ...

        @property
        def spss(self)->int4: ...

        @property
        def spst(self)->int4: ...

        @property
        def spsp(self)->int4: ...

        @property
        def spts(self)->int4: ...

        @property
        def sptt(self)->int4: ...

        @property
        def sptp(self)->int4: ...

        @property
        def spps(self)->int4: ...

        @property
        def sppt(self)->int4: ...

        @property
        def sppp(self)->int4: ...

        @property
        def tsss(self)->int4: ...

        @property
        def tsst(self)->int4: ...

        @property
        def tssp(self)->int4: ...

        @property
        def tsts(self)->int4: ...

        @property
        def tstt(self)->int4: ...

        @property
        def tstp(self)->int4: ...

        @property
        def tsps(self)->int4: ...

        @property
        def tspt(self)->int4: ...

        @property
        def tspp(self)->int4: ...

        @property
        def ttss(self)->int4: ...

        @property
        def ttst(self)->int4: ...

        @property
        def ttsp(self)->int4: ...

        @property
        def ttts(self)->int4: ...

        @property
        def tttt(self)->int4: ...

        @property
        def tttp(self)->int4: ...

        @property
        def ttps(self)->int4: ...

        @property
        def ttpt(self)->int4: ...

        @property
        def ttpp(self)->int4: ...

        @property
        def tpss(self)->int4: ...

        @property
        def tpst(self)->int4: ...

        @property
        def tpsp(self)->int4: ...

        @property
        def tpts(self)->int4: ...

        @property
        def tptt(self)->int4: ...

        @property
        def tptp(self)->int4: ...

        @property
        def tpps(self)->int4: ...

        @property
        def tppt(self)->int4: ...

        @property
        def tppp(self)->int4: ...

        @property
        def psss(self)->int4: ...

        @property
        def psst(self)->int4: ...

        @property
        def pssp(self)->int4: ...

        @property
        def psts(self)->int4: ...

        @property
        def pstt(self)->int4: ...

        @property
        def pstp(self)->int4: ...

        @property
        def psps(self)->int4: ...

        @property
        def pspt(self)->int4: ...

        @property
        def pspp(self)->int4: ...

        @property
        def ptss(self)->int4: ...

        @property
        def ptst(self)->int4: ...

        @property
        def ptsp(self)->int4: ...

        @property
        def ptts(self)->int4: ...

        @property
        def pttt(self)->int4: ...

        @property
        def pttp(self)->int4: ...

        @property
        def ptps(self)->int4: ...

        @property
        def ptpt(self)->int4: ...

        @property
        def ptpp(self)->int4: ...

        @property
        def ppss(self)->int4: ...

        @property
        def ppst(self)->int4: ...

        @property
        def ppsp(self)->int4: ...

        @property
        def ppts(self)->int4: ...

        @property
        def pptt(self)->int4: ...

        @property
        def pptp(self)->int4: ...

        @property
        def ppps(self)->int4: ...

        @property
        def pppt(self)->int4: ...

        @property
        def pppp(self)->int4: ...
        # --- END generated swizzles ---
