import ctypes
from typing import TYPE_CHECKING, Union

from .genVec2 import genVec2

if TYPE_CHECKING:

    from .uint3 import uint3
    from .uint4 import uint4

# --- BEGIN generated swizzle imports ---
# --- END generated swizzle imports ---

class uint2(genVec2):

    _fields_ = [
        ('x', ctypes.c_uint),
        ('y', ctypes.c_uint)
    ]

    @property
    def dtype(self)->type:
        return ctypes.c_uint

    if TYPE_CHECKING:

        # Every swizzle genVec can build, as declarations only. This block never
        # executes, so the runtime path stays genVec.__getattr__.
        # Regenerate with tools/sync_swizzle_blocks.py.
        # --- BEGIN generated swizzles ---

        @property
        def x(self)->int: ...

        @x.setter
        def x(self, value:Union[bool, int, float])->None: ...

        @property
        def y(self)->int: ...

        @y.setter
        def y(self, value:Union[bool, int, float])->None: ...

        @property
        def xx(self)->"uint2": ...

        @property
        def xy(self)->"uint2": ...

        @xy.setter
        def xy(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yx(self)->"uint2": ...

        @yx.setter
        def yx(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def yy(self)->"uint2": ...

        @property
        def xxx(self)->uint3: ...

        @property
        def xxy(self)->uint3: ...

        @property
        def xyx(self)->uint3: ...

        @property
        def xyy(self)->uint3: ...

        @property
        def yxx(self)->uint3: ...

        @property
        def yxy(self)->uint3: ...

        @property
        def yyx(self)->uint3: ...

        @property
        def yyy(self)->uint3: ...

        @property
        def xxxx(self)->uint4: ...

        @property
        def xxxy(self)->uint4: ...

        @property
        def xxyx(self)->uint4: ...

        @property
        def xxyy(self)->uint4: ...

        @property
        def xyxx(self)->uint4: ...

        @property
        def xyxy(self)->uint4: ...

        @property
        def xyyx(self)->uint4: ...

        @property
        def xyyy(self)->uint4: ...

        @property
        def yxxx(self)->uint4: ...

        @property
        def yxxy(self)->uint4: ...

        @property
        def yxyx(self)->uint4: ...

        @property
        def yxyy(self)->uint4: ...

        @property
        def yyxx(self)->uint4: ...

        @property
        def yyxy(self)->uint4: ...

        @property
        def yyyx(self)->uint4: ...

        @property
        def yyyy(self)->uint4: ...

        @property
        def r(self)->int: ...

        @r.setter
        def r(self, value:Union[bool, int, float])->None: ...

        @property
        def g(self)->int: ...

        @g.setter
        def g(self, value:Union[bool, int, float])->None: ...

        @property
        def rr(self)->"uint2": ...

        @property
        def rg(self)->"uint2": ...

        @rg.setter
        def rg(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gr(self)->"uint2": ...

        @gr.setter
        def gr(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def gg(self)->"uint2": ...

        @property
        def rrr(self)->uint3: ...

        @property
        def rrg(self)->uint3: ...

        @property
        def rgr(self)->uint3: ...

        @property
        def rgg(self)->uint3: ...

        @property
        def grr(self)->uint3: ...

        @property
        def grg(self)->uint3: ...

        @property
        def ggr(self)->uint3: ...

        @property
        def ggg(self)->uint3: ...

        @property
        def rrrr(self)->uint4: ...

        @property
        def rrrg(self)->uint4: ...

        @property
        def rrgr(self)->uint4: ...

        @property
        def rrgg(self)->uint4: ...

        @property
        def rgrr(self)->uint4: ...

        @property
        def rgrg(self)->uint4: ...

        @property
        def rggr(self)->uint4: ...

        @property
        def rggg(self)->uint4: ...

        @property
        def grrr(self)->uint4: ...

        @property
        def grrg(self)->uint4: ...

        @property
        def grgr(self)->uint4: ...

        @property
        def grgg(self)->uint4: ...

        @property
        def ggrr(self)->uint4: ...

        @property
        def ggrg(self)->uint4: ...

        @property
        def gggr(self)->uint4: ...

        @property
        def gggg(self)->uint4: ...

        @property
        def s(self)->int: ...

        @s.setter
        def s(self, value:Union[bool, int, float])->None: ...

        @property
        def t(self)->int: ...

        @t.setter
        def t(self, value:Union[bool, int, float])->None: ...

        @property
        def ss(self)->"uint2": ...

        @property
        def st(self)->"uint2": ...

        @st.setter
        def st(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def ts(self)->"uint2": ...

        @ts.setter
        def ts(self, value:Union[bool, int, float, genVec2])->None: ...

        @property
        def tt(self)->"uint2": ...

        @property
        def sss(self)->uint3: ...

        @property
        def sst(self)->uint3: ...

        @property
        def sts(self)->uint3: ...

        @property
        def stt(self)->uint3: ...

        @property
        def tss(self)->uint3: ...

        @property
        def tst(self)->uint3: ...

        @property
        def tts(self)->uint3: ...

        @property
        def ttt(self)->uint3: ...

        @property
        def ssss(self)->uint4: ...

        @property
        def ssst(self)->uint4: ...

        @property
        def ssts(self)->uint4: ...

        @property
        def sstt(self)->uint4: ...

        @property
        def stss(self)->uint4: ...

        @property
        def stst(self)->uint4: ...

        @property
        def stts(self)->uint4: ...

        @property
        def sttt(self)->uint4: ...

        @property
        def tsss(self)->uint4: ...

        @property
        def tsst(self)->uint4: ...

        @property
        def tsts(self)->uint4: ...

        @property
        def tstt(self)->uint4: ...

        @property
        def ttss(self)->uint4: ...

        @property
        def ttst(self)->uint4: ...

        @property
        def ttts(self)->uint4: ...

        @property
        def tttt(self)->uint4: ...
        # --- END generated swizzles ---
